.github/actions/build/action.yaml, .github/actions/test/action.yaml, .github/workflows/pr.yaml, tsconfig.json, yamllint-config.yaml
=> chore(ci): Fix remote fetch and yarn args

plugins/keycloak-backend/.eslintrc.js, plugins/keycloak-backend/README.md, plugins/keycloak-backend/package.json, plugins/keycloak-backend/src/index.ts, plugins/keycloak-backend/src/lib/config.ts, plugins/keycloak-backend/src/lib/constants.ts, plugins/keycloak-backend/src/lib/index.ts, plugins/keycloak-backend/src/lib/read.ts, plugins/keycloak-backend/src/lib/types.ts, plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts, plugins/keycloak-backend/src/providers/index.ts, plugins/keycloak-backend/src/setupTests.ts, tsconfig.json, yarn.lock
Initial version for the Keycloak backstage plugin
=> Added Keycloak backstage plugin

plugins/keycloak-backend/package.json
=> feat: rename and release keycloak plugin

.prettierignore, plugins/keycloak-backend/package.json, plugins/ocm-backend/package.json, plugins/ocm-common/package.json, plugins/ocm/package.json
=> chore: Make OCM plugins public and fix main for keycloak

plugins/ocm/src/components/ClusterStatusPage/ClusterStatusPage.tsx
=> fix: Fix typo in cluster status page ocm

plugins/ocm-backend/package.json
=> fix(ocm-backend): Package config schema with the plugin

plugins/ocm-backend/package.json
=> fix(ocm-backend): Package config schema with the plugin - retry

plugins/keycloak-backend/package.json, plugins/keycloak-backend/src/lib/config.ts, plugins/keycloak-backend/src/lib/read.ts, plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts
First chunk of refactoring on this. Simplify some of the calls, use inlines where it made sense, remove async from where it was not needed.
=> refactor: Use arrow functions, maps and inlines

plugins/quay/README.md
=> fix(quay) Fix Readme Typos

plugins/topology/src/utils/pod-resource-utils.test.ts, plugins/topology/src/utils/pod-resource-utils.ts
Fixes: https://github.com/janus-idp/backstage-plugins/issues/163
**Before:**
**After:**
=> fix(topology): getDeploymentRevision always return false but not the revision for deployment

plugins/topology/src/components/Topology/TopologyToolbar.css, plugins/topology/src/components/Topology/TopologyToolbar.tsx
**Fixes:**
https://github.com/janus-idp/backstage-plugins/issues/200
https://github.com/janus-idp/backstage-plugins/issues/199
=> fix(topology): Change toolbar text and spacing

plugins/artifactory/.eslintrc.js, plugins/artifactory/README.md, plugins/artifactory/config.d.ts, plugins/artifactory/dev/index.tsx, plugins/artifactory/package.json, plugins/artifactory/src/api/index.ts, plugins/artifactory/src/components/ArtifactoryDashboardPage/ArtifactoryDashboardPage.tsx, plugins/artifactory/src/components/ArtifactoryDashboardPage/index.ts, plugins/artifactory/src/components/ArtifactoryRepository/ArtifactoryRepository.tsx, plugins/artifactory/src/components/ArtifactoryRepository/index.ts, plugins/artifactory/src/components/ArtifactoryRepository/tableHeading.tsx, plugins/artifactory/src/components/useArtifactoryAppData.ts, plugins/artifactory/src/components/utils.tsx, plugins/artifactory/src/index.ts, plugins/artifactory/src/plugin.test.ts, plugins/artifactory/src/plugin.ts, plugins/artifactory/src/routes.ts, plugins/artifactory/src/setupTests.ts, plugins/artifactory/src/types.ts
Resolves #117 
Get the image data from an Artifactory/JCR registry
=> feat(artifactory) First funtional version of the plugin

plugins/sonarqube-actions/README.md
=> fix(sonarqube): Fix formatting issue in markdown table

plugins/tekton/.eslintrc.js, plugins/tekton/README.md, plugins/tekton/dev/index.tsx, plugins/tekton/package.json, plugins/tekton/src/__fixtures__/1-pipelinesData.ts, plugins/tekton/src/components/Tekton/TektonComponent.test.tsx, plugins/tekton/src/components/Tekton/TektonComponent.tsx, plugins/tekton/src/components/Tekton/index.ts, plugins/tekton/src/index.ts, plugins/tekton/src/plugin.test.ts, plugins/tekton/src/plugin.ts, plugins/tekton/src/routes.ts, plugins/tekton/src/setupTests.ts, yarn.lock
Tracks: https://github.com/janus-idp/backstage-plugins/issues/201
**Description:** 
Setup a frontend plugin for tekton with dev setup
**Todo**
=> feat(tekton): tekton plugin init with backstage k8s plugin

plugins/topology/src/__fixtures__/1-deployments.ts, plugins/topology/src/__fixtures__/kubernetesObject.ts, plugins/topology/src/components/Topology/TopologyComponent.tsx, plugins/topology/src/data-transforms/data-transformer.test.ts, plugins/topology/src/hooks/useAllWatchResources.test.ts, plugins/topology/src/models.ts, plugins/topology/src/types/types.ts, plugins/topology/src/utils/pod-resource-utils.test.ts, plugins/topology/src/utils/pod-resource-utils.ts, plugins/topology/src/utils/pod-ring-utils.ts, plugins/topology/src/utils/resource-utils.test.ts, plugins/topology/src/utils/resource-utils.ts, plugins/topology/src/utils/topology-utils.ts, plugins/topology/src/utils/transform-utils.test.ts
Resolves: https://github.com/janus-idp/backstage-plugins/issues/183
Fixes: https://github.com/janus-idp/backstage-plugins/issues/197
Changes:
- Added StatefulSet, DaemonSet, CronJob, and Job in the watch resources' list
- Fixed a minor issue with the standalone job not showing up even when it is watched
- Modified existing tests to verify the presence of the newly added resource types in the watched resources
Screenshot:
=> feat(topology): added visualization of SS, DS, CJ and Jobs in the topology view

plugins/ocm-backend/src/helpers/kubernetes.ts
If the returned error body is a string the resulting error object contains the error body as an array of chars instead of a single string because of the `...` operator. For example: 
```json
{
"error": {
"0": "<",
"1": "!",
"2": "d",
"3": "o",
"4": "c",
"5": "t",
"6": "y",
"7": "p",
"8": "e",
"9": " ",
"10": "h",
"11": "t",
"12": "m",
"13": "l",
"14": ">",
"15": "\n",
"16": "<",
"17": "h",
"18": "t",
"19": "m",
"20": "l",
"21": ">",
"22": "\n",
"23": "<",
"24": "h",
"25": "e",
"26": "a",
"27": "d",
"28": ">",
"29": "\n",
"30": " ",
"31": " ",
"32": " ",
"33": " ",
"34": "<",
"35": "t",
"36": "i",
"37": "t",
"38": "l",
"39": "e",
"40": ">",
"41": "E",
"42": "x",
"43": "a",
"44": "m",
"45": "p",
"46": "l",
"47": "e",
"48": " ",
"49": "D",
"50": "o",
"51": "m",
"52": "a",
"53": "i",
"54": …
```
=> fix(ocm-backend): Handle a case when the error is a string

plugins/topology/src/components/Topology/TopologyComponent.tsx, plugins/topology/src/plugin.ts
Fixes: https://github.com/janus-idp/backstage-plugins/issues/251
=> fix(topology): moves base styles to plugin form component

plugins/topology/package.json, yarn.lock
Fixes: https://github.com/janus-idp/backstage-plugins/issues/260
=> fix(topology): updates pf react-topology to standalone release

plugins/topology/package.json, plugins/topology/src/components/Topology/TopologySideBar/IngressRules.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanel.tsx
Story: https://github.com/janus-idp/backstage-plugins/issues/229
This PR adds ingress rules in each ingress shown in the sidebar.
=> feat(topology): Show ingress rules in sidebar

plugins/ocm-backend/__fixtures__/cluster.open-cluster-management.io/managedclusters/offline-cluster.json, plugins/ocm-backend/__fixtures__/handlers.ts, plugins/ocm-backend/__fixtures__/internal.open-cluster-management.io/managedclusterinfos/offline-cluster.json, plugins/ocm-backend/dev/index.ts, plugins/ocm-backend/src/run.ts, plugins/ocm/README.md, plugins/ocm/dev/index.tsx, plugins/ocm/package.json, yarn.lock
The development setup for the `ocm` fronted plugin was not working correctly. 
- Fix the initial development setup for `ClusterStatusPage` page by supplying mocked APIs (`catalog` and `search`)
- Add pages for the individual cluster entities together with using the `ocm-backend` dev setup
- Add configuration option for `cors` in the `ocm-backend` plugin so that the fronted can communicate with the backend while using the development setup
- Update `README`
- Add an offline mocked cluster
=> dev(ocm): Improve setup

plugins/ocm-backend/src/service/router.test.ts
=> test(ocm): fix typo in testsuite

plugins/tekton/src/components/PipelineRunList/PipelineRunHeader.tsx, plugins/tekton/src/components/PipelineRunList/PipelineRunList.test.tsx, plugins/tekton/src/components/PipelineRunList/PipelineRunList.tsx, plugins/tekton/src/components/Table/Table.tsx, plugins/tekton/src/components/Tekton/TektonComponent.test.tsx, plugins/tekton/src/components/Tekton/TektonErrorPanel.tsx, plugins/tekton/src/components/common/ClusterSelector.tsx, plugins/tekton/src/hooks/useTableData.test.ts, plugins/tekton/src/hooks/useTableData.ts
Tracks : https://github.com/janus-idp/backstage-plugins/issues/237
- Pipeline Run List with data
- Empty state (will show warning if unable to fetch resource else just empty state)
=> feat(tekton): tekton pipeline run list sort

plugins/quay/README.md
GitHub issue: https://github.com/janus-idp/backstage-plugins/issues/129
=> docs: review for Quay plugin

plugins/openshift-image-registry/.eslintrc.js, plugins/openshift-image-registry/README.md, plugins/openshift-image-registry/config.d.ts, plugins/openshift-image-registry/dev/index.tsx, plugins/openshift-image-registry/package.json, plugins/openshift-image-registry/src/api/index.ts, plugins/openshift-image-registry/src/components/OcirImagesComponent/OcirImagesComponent.tsx, plugins/openshift-image-registry/src/components/OcirImagesComponent/index.ts, plugins/openshift-image-registry/src/components/OcirPage/OcirPage.tsx, plugins/openshift-image-registry/src/components/OcirPage/index.ts, plugins/openshift-image-registry/src/index.ts, plugins/openshift-image-registry/src/plugin.test.ts, plugins/openshift-image-registry/src/plugin.ts, plugins/openshift-image-registry/src/routes.ts, plugins/openshift-image-registry/src/setupTests.ts, plugins/tekton/README.md
Fixes: https://github.com/janus-idp/backstage-plugins/issues/300
=> Add image registry plugin and api client

plugins/tekton/src/components/pipeline-topology/PipelineVisualization.tsx
**Fixes:**
https://github.com/janus-idp/backstage-plugins/issues/317
=> fix(tekton): fix task node status

plugins/topology/CHANGELOG.md
This PR does a meaningless change to force a release of https://github.com/janus-idp/backstage-plugins/pull/287
=> chore(topology): upgrade pf react-core package

plugins/topology/src/common/components/CamelCaseWrap.tsx, plugins/topology/src/common/components/ResourceName.css, plugins/topology/src/common/components/ResourceName.tsx, plugins/topology/src/common/components/ResourceStatus.css, plugins/topology/src/common/components/ResourceStatus.tsx, plugins/topology/src/common/components/Status.tsx, plugins/topology/src/common/components/StatusIconAndText.css, plugins/topology/src/common/components/StatusIconAndText.tsx, plugins/topology/src/common/components/icons.css, plugins/topology/src/common/components/icons.tsx, plugins/topology/src/common/utils/getResources.ts, plugins/topology/src/components/Graph/BaseNode.css, plugins/topology/src/components/Graph/BaseNode.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanel.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologySideBarHeading.css, plugins/topology/src/components/Topology/TopologySideBar/TopologySideBarHeading.tsx, plugins/topology/src/const.ts, plugins/topology/src/models.ts, plugins/topology/src/types/types.ts, plugins/topology/src/utils/workload-node-utils.ts
Fixes:
- https://github.com/janus-idp/backstage-plugins/issues/282
- https://github.com/janus-idp/backstage-plugins/issues/283
Screenshot:
=> fix(topology): Fix topology sidepanel css

plugins/ocm-backend/README.md, plugins/ocm-common/README.md, plugins/ocm/README.md
GitHub issue: https://github.com/janus-idp/backstage-plugins/issues/131
=> docs: review for OCM plugin

plugins/topology/README.md
GitHub issue: https://github.com/janus-idp/backstage-plugins/issues/132
=> docs: review for Topology plugin

plugins/keycloak-backend/README.md
Changed layout to distinguish between admin and user doc.
Issue: https://github.com/janus-idp/backstage-plugins/issues/307
=> docs(keycloak): update user doc

package.json
SSIA, remove clutter from changelogs.
=> chore: remove chores from changelog

README.md, packages/backend/README.md, plugins/3scale-backend/README.md, plugins/analytics-provider-segment/README.md, plugins/jfrog-artifactory/README.md, plugins/keycloak-backend/README.md, plugins/ocm-backend/README.md, plugins/ocm/README.md, plugins/openshift-image-registry/README.md, plugins/quay/README.md, plugins/regex-actions/README.md, plugins/sonarqube-actions/README.md, plugins/tekton/README.md, plugins/topology/README.md
Currently we are ingesting the plugin READMEs in the community website and this pr will help with the following:
- Better syntax highlighting
- Fix broken links
=> docs: update plugin READMEs

.github/actions/build-website/action.yaml, .github/workflows/pr-website.yaml, .github/workflows/push-website.yaml
Adds dispatch event to build website
related: https://github.com/janus-idp/janus-idp.github.io/pull/66
=> chore(ci): add dispatch event to build website

plugins/topology/src/__fixtures__/1-deployments.ts, plugins/topology/src/__fixtures__/workloadNodeData.ts, plugins/topology/src/components/Topology/TopologySideBar/TopologyCronJobDetails.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologyDaemonSetDetails.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologyDeploymentDetails.css, plugins/topology/src/components/Topology/TopologySideBar/TopologyDeploymentDetails.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologyDetailsTabPanel.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologyJobDetails.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanel.css, plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanel.test.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanel.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologyWorkloadDetails.tsx, plugins/topology/src/data-transforms/data-transformer.ts, plugins/topology/src/types/jobs.ts, plugins/topology/src/utils/resource-utils.ts, plugins/topology/src/utils/topology-utils.ts
**Story:** https://github.com/janus-idp/backstage-plugins/issues/270
Added specific detail items for SS/DS/CJ/J resources as per OCP. Also added Jobs section in resources tab of CJ resource.
https://github.com/janus-idp/backstage-plugins/assets/20724543/a9750051-5e22-405e-905a-46ce01c56067
=> feat(topology): add specific details for all supported workloads

plugins/topology/src/components/Graph/WorkloadNode.css, plugins/topology/src/components/Graph/WorkloadNode.tsx, plugins/topology/src/components/Topology/TopologyViewWorkloadComponent.tsx, plugins/topology/src/hooks/useSideBar.tsx
**Fixes:**
https://github.com/janus-idp/backstage-plugins/issues/361
**GIF:**
=> fix(topology): persist selected topology node id in new tab

plugins/tekton/src/hooks/useAllWatchResources.ts, plugins/tekton/src/hooks/useResourcesClusters.ts, plugins/tekton/src/hooks/useTektonObjectsResponse.ts
Fixes: https://github.com/janus-idp/backstage-plugins/issues/389
=> fix(tekton): handles unnecessary rerenders on tekton

.gitignore
chore: since .nvmrc is committed to the repo, remove it from .gitignore
N/A
N/A
=> chore: since .nvmrc is committed to the repo, remove it from .gitignore

plugins/keycloak-backend/__fixtures__/data.ts, plugins/keycloak-backend/__fixtures__/helpers.ts, plugins/keycloak-backend/package.json, plugins/keycloak-backend/src/lib/config.test.ts, plugins/keycloak-backend/src/lib/read.test.ts, plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.test.ts, yarn.lock
=> test(keycloak): add tests

plugins/topology/README.md
GitHub issue: https://github.com/janus-idp/backstage-plugins/issues/393
JIRA: https://issues.redhat.com/browse/RHIDP-127
=> docs(topology): fixes to topology readme

plugins/jfrog-artifactory/README.md
GitHub issue: https://github.com/janus-idp/backstage-plugins/issues/472
JIRA: https://issues.redhat.com/browse/RHIDP-128
=> docs(jfrog): adding admin sections in readme

plugins/3scale-backend/README.md
GitHub issue: https://github.com/janus-idp/backstage-plugins/issues/470
JIRA: https://issues.redhat.com/browse/RHIDP-128
=> docs(3scale): adding admin section in readme

plugins/keycloak-backend/README.md
GitHub issue: https://github.com/janus-idp/backstage-plugins/issues/392
JIRA: https://issues.redhat.com/browse/RHIDP-127
=> docs(keycloak): fixes in readme file

plugins/topology/README.md, plugins/topology/src/__fixtures__/1-deployments.ts, plugins/topology/src/__fixtures__/tektonResources.ts, plugins/topology/src/__fixtures__/workloadNodeData.ts, plugins/topology/src/common/components/Status.tsx, plugins/topology/src/common/utils/datetime.test.ts, plugins/topology/src/common/utils/datetime.ts, plugins/topology/src/components/Topology/TopologyComponent.css, plugins/topology/src/components/Topology/TopologyComponent.tsx, plugins/topology/src/components/Topology/TopologySideBar/PLRlastUpdated.tsx, plugins/topology/src/components/Topology/TopologySideBar/PLRlist.css, plugins/topology/src/components/Topology/TopologySideBar/PLRlist.test.tsx, plugins/topology/src/components/Topology/TopologySideBar/PLRlist.tsx, plugins/topology/src/components/Topology/TopologySideBar/Resources/IngressListSidebar.tsx, plugins/topology/src/components/Topology/TopologySideBar/Resources/RouteListSidebar.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanel.test.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanel.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPaneltem.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologySideBarDetailsItem.tsx, plugins/topology/src/data-transforms/data-transformer.ts, plugins/topology/src/models.ts, plugins/topology/src/types/pipeline.ts, plugins/topology/src/types/pipelineRun.ts, plugins/topology/src/types/types.ts, plugins/topology/src/utils/pipeline-utils.test.ts, plugins/topology/src/utils/pipeline-utils.ts, plugins/topology/src/utils/topology-utils.ts
Story - https://github.com/janus-idp/backstage-plugins/issues/284
This PR adds pipelines and its pipeline-runs in workload sidepanel.
=> feat(topology): show pipeline-runs list in sidepanel

package.json
chore: bump to 1.0.1 in package.json as 1.0.0. is released
N/A
N/A
=> chore: bump to 1.0.1 in package.json as 1.0.0. is released

plugins/tekton/README.md, plugins/tekton/manifests/clusterrole.yaml, plugins/topology/README.md, plugins/topology/manifests/clusterrole.yaml
Resolves: https://github.com/janus-idp/backstage-plugins/issues/501
=> chore(tekton,topology): add clusterrole manifests

plugins/shared-react/src/__fixtures__/1-pipelinesData.ts, plugins/shared-react/src/components/pipeline/HorizontalStackedBars.css, plugins/shared-react/src/components/pipeline/HorizontalStackedBars.tsx, plugins/shared-react/src/utils/pipeline-utils/pipeline-utils.test.ts, plugins/shared-react/src/utils/pipeline-utils/pipeline-utils.ts, plugins/topology/src/components/Graph/decorators/PipelineRunDecoratorTooltip.tsx
**Resolves:**
https://github.com/janus-idp/backstage-plugins/issues/539
Updated a shared component
Added more tests
=> feat(shared-react): update shared plugin

plugins/jfrog-artifactory/src/api/index.ts, plugins/jfrog-artifactory/src/plugin.ts, plugins/ocm/src/api/index.ts, plugins/ocm/src/plugin.ts, plugins/openshift-image-registry/src/api/index.ts, plugins/openshift-image-registry/src/plugin.ts, plugins/quay/src/api/index.test.ts, plugins/quay/src/api/index.ts, plugins/quay/src/plugin.ts
=> fix(plugins): add bearer token to request headers when sending requests, authmiddleware issue

plugins/topology/README.md, plugins/topology/manifests/clusterrole.yaml, plugins/topology/package.json, plugins/topology/src/__fixtures__/1-deployments.ts, plugins/topology/src/components/DecoratorIcons/CheIcon.tsx, plugins/topology/src/components/DecoratorIcons/RouteDecoratorIcon.tsx, plugins/topology/src/components/Graph/WorkloadNode.tsx, plugins/topology/src/components/Graph/decorators/EditDecorator.test.tsx, plugins/topology/src/components/Graph/decorators/EditDecorator.tsx, plugins/topology/src/components/Topology/TopologyComponent.tsx, plugins/topology/src/data-transforms/data-transformer.ts, plugins/topology/src/models.ts, plugins/topology/src/utils/edit-decorator-utils.test.ts, plugins/topology/src/utils/edit-decorator-utils.ts, plugins/topology/src/utils/git-utils.test.ts, plugins/topology/src/utils/git-utils.ts, plugins/topology/src/utils/resource-utils.test.ts, plugins/topology/src/utils/resource-utils.ts, plugins/topology/src/utils/topology-utils.ts, yarn.lock
**Stories:** https://github.com/janus-idp/backstage-plugins/issues/480, https://github.com/janus-idp/backstage-plugins/issues/250
This PR adds code decorator on topology node for git and devspace url
Demo:
With Git repo URL:
https://github.com/janus-idp/backstage-plugins/assets/20724543/ae66cd32-3711-4acf-a943-22b9217de6a8
With Che URL:
https://github.com/janus-idp/backstage-plugins/assets/20724543/1285994e-c64a-46bc-ba37-d9b34aff7e28
=> feat(topology): add edit code node decorator

plugins/kiali-backend/package.json, plugins/kiali-backend/src/clients/KialiAPIConnector.ts, plugins/kiali-backend/src/clients/fetch.ts, plugins/kiali-common/src/types/Fetch.ts, plugins/kiali/DEVELOPMENT.md, plugins/kiali/README.md, plugins/kiali/src/components/Overview/Overview.tsx, plugins/kiali/src/components/Overview/OverviewCard/OverviewCard.tsx
Move node-fetch to axios.
Related with https://github.com/janus-idp/backstage-plugins/pull/460
=> feat(kiali): move from node-fetch to axios

plugins/topology/src/__fixtures__/1-tektonResources.ts, plugins/topology/src/__fixtures__/workloadNodeData.ts, plugins/topology/src/common/components/ResourceName.tsx, plugins/topology/src/components/Topology/TopologySideBar/PLRlist.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanel.test.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanel.tsx, plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanelItem.css, plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPaneltem.tsx, plugins/topology/src/const.ts, plugins/topology/src/utils/pipeline-utils.ts, plugins/topology/src/utils/resource-utils.ts
Story - https://github.com/janus-idp/backstage-plugins/issues/490
Added PLR icon
=> feat(topology): show only latest 3 pods/plrs in node sidebar

plugins/rh-rbac-backend/model/rbac-policy.csv, plugins/rh-rbac-backend/package.json, plugins/rh-rbac-backend/src/service/casbin-adapter-factory.test.ts, plugins/rh-rbac-backend/src/service/casbin-adapter-factory.ts, plugins/rh-rbac-backend/src/service/permission-policy.test.ts, plugins/rh-rbac-backend/src/service/permission-policy.ts, plugins/rh-rbac-backend/src/service/test/data/rbac-policy.csv, yarn.lock
Make file based Auth policy configurable
fixes:  janus-idp/backstage-showcase#360
https://github.com/janus-idp/backstage-plugins/pull/544
I temporary included all(three) commits from pr: https://github.com/janus-idp/backstage-plugins/pull/544
https://www.youtube.com/watch?v=1h0PWaaXKtw
=> feat(rbac): make file based Auth policies configurable

plugins/shared-react/src/components/pipeline/HorizontalStackedBars.tsx, plugins/shared-react/src/utils/pipeline-utils/pipeline-utils.ts, plugins/shared-react/src/utils/pipeline-utils/taskRun-utils.ts
**Resolves:**
https://github.com/janus-idp/backstage-plugins/issues/627
=> fix(shared-react): minor fixes

plugins/quay/src/components/QuayTagDetails/component.tsx, plugins/quay/src/components/QuayTagPage/component.tsx
=> chore(quay): fix optional chain expression and unnecessary assertion code smells #597

plugins/topology/src/components/Pods/pod.ts, plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanel.tsx, plugins/topology/src/utils/pod-resource-utils.test.ts, plugins/topology/src/utils/pod-resource-utils.ts
**Resolves:**
https://github.com/janus-idp/backstage-plugins/issues/504
=> fix(topology): fix pod status info in topology side panel

plugins/shared-react/package.json, plugins/shared-react/src/components/common/CamelCaseWrap.tsx, plugins/shared-react/src/hooks/debounce.ts, plugins/shared-react/src/hooks/useDeepCompareMemoize.ts, plugins/shared-react/src/utils/pipeline/pipeline.test.ts, plugins/shared-react/src/utils/pipeline/pipeline.ts
**Resolves:**
https://github.com/janus-idp/backstage-plugins/issues/595
**Solution description:**
- fixed code smells
- added common utils
- added more tests
=> fix(shared-react): fix code smells

plugins/shared-react/src/hooks/index.ts, plugins/shared-react/src/index.ts
part of PR https://github.com/janus-idp/backstage-plugins/pull/631/files
=> fix(shared-react): export hooks

plugins/sonarqube-actions/src/actions/createSonarQubeProject.ts
=> chore(sonarqube): reduce code smells

plugins/3scale-backend/src/providers/ThreeScaleApiEntityProvider.ts
=> chore(3scale): fixed the vulnerablity scope in the 3scale plugin

plugins/aap-backend/src/providers/AapResourceEntityProvider.ts
Fixes: https://github.com/janus-idp/backstage-plugins/issues/589
=> fix(aap): fixes codesmells for aap plugin

plugins/keycloak-backend/config.d.ts, plugins/keycloak-backend/src/lib/types.ts
=> fix(keycloak): fix config loader issue on backstage v1.17

plugins/tekton/README.md, plugins/tekton/manifests/clusterrole.yaml, plugins/topology/README.md, plugins/topology/manifests/clusterrole.yaml
=> docs: update tekton and topology documentation with pod log permissions

plugins/jfrog-artifactory/src/components/JfrogArtifactoryDashboardPage/JfrogArtifactoryDashboardPage.tsx, plugins/jfrog-artifactory/src/components/JfrogArtifactoryRepository/JfrogArtifactoryRepository.tsx
Resolves: [#617](https://github.com/janus-idp/backstage-plugins/issues/617)
=> chore(JFrog Artifactory): remove <component-name>.defaultProps

plugins/kiali-backend/src/clients/KialiAPIConnector.ts, plugins/kiali-backend/src/clients/fetch.ts, plugins/kiali-backend/src/filters/byAnnotation.ts, plugins/kiali-backend/src/plugin.ts, plugins/kiali-backend/src/service/router.test.ts, plugins/kiali-backend/src/service/router.ts, plugins/kiali-backend/src/service/standaloneServer.ts, plugins/kiali-common/src/config/Config.ts, plugins/kiali-common/src/types/Auth.ts, plugins/kiali-common/src/types/Fetch.ts, plugins/kiali-common/src/types/index.ts, plugins/kiali/DEVELOPMENT.md, plugins/kiali/README.md, plugins/kiali/src/api/apiClient.ts, plugins/kiali/src/components/Icons/index.ts, plugins/kiali/src/components/KialiComponent/Header/Header.tsx, plugins/kiali/src/components/KialiComponent/Header/StatusContent.tsx, plugins/kiali/src/components/KialiComponent/Header/index.ts, plugins/kiali/src/components/KialiComponent/KialiComponent.tsx, plugins/kiali/src/components/Overview/Overview.tsx, plugins/kiali/src/components/Overview/OverviewCard/OverviewCardBody/IstioConfigStatus.tsx, plugins/kiali/src/components/Overview/OverviewCard/OverviewCardBody/OverviewCardBody.tsx, plugins/kiali/src/components/Overview/OverviewCard/OverviewCardHeader/OverviewCardHeader.tsx, plugins/kiali/src/components/Overview/OverviewCard/OverviewMetrics/OverviewMetrics.tsx, plugins/kiali/src/helper/handlerError.ts, plugins/kiali/src/helper/index.ts, plugins/kiali/src/helper/utils.ts, plugins/kiali/src/plugin.ts
Require https://github.com/janus-idp/backstage-plugins/pull/607
=> feat(kiali): show kiali information in header

plugins/kiali/DEVELOPMENT.md, plugins/kiali/dev/__fixtures__/1-overview.json, plugins/kiali/dev/__fixtures__/config.json, plugins/kiali/dev/__fixtures__/status.json, plugins/kiali/dev/index.tsx, plugins/kiali/src/Router.tsx, plugins/kiali/src/components/KialiComponent/KialiComponent.tsx, plugins/kiali/src/components/KialiComponent/KialiNoPath.tsx, plugins/kiali/src/components/KialiComponent/index.ts
Frontend Dev environment fir kiali ;) 
cc @tumido
=> feat(kiali): frontend dev environment

.husky/pre-commit, package.json, yarn.lock
fixes https://github.com/janus-idp/backstage-plugins/issues/684
=> fix(lint-staged): add lint-staged

plugins/analytics-provider-segment/src/plugin.ts
=> chore(segment): remove @deprecated comment in segment plugin

plugins/topology/src/utils/pod-resource-utils.test.ts, plugins/topology/src/utils/pod-resource-utils.ts, plugins/topology/src/utils/resource-utils.ts, plugins/topology/src/utils/transform-utils.ts, plugins/topology/src/utils/workload-node-utils.ts
**Resolves:**
https://github.com/janus-idp/backstage-plugins/issues/587
=> fix(topology): fix code smells

plugins/keycloak-backend/package.json, yarn.lock
=> chore(keycloak): make dev setup work on linux

plugins/acr/README.md
Fixes: https://github.com/janus-idp/backstage-plugins/issues/702
=> docs(acr): updated serviceEntityPage in README

plugins/nexus-repository-manager/README.md
GH issue: https://github.com/janus-idp/backstage-plugins/issues/569
=> docs(nexus): nexus plugin documentation

plugins/acr/CONTRIBUTING.md, plugins/acr/README.md
=> docs(acr): update acr README.md to show how to create bearer/basic tokens

plugins/keycloak-backend/src/lib/read.test.ts, plugins/keycloak-backend/src/lib/read.ts
=> fix(keycloak): fix keycloak user displayname

plugins/topology/src/__fixtures__/1-deployments.ts
**Fixes:** https://github.com/janus-idp/backstage-plugins/issues/646
**Before:**
**After:**
=> fix(topology): fixes crash on dev setup for k8s tab

plugins/topology/README.md
Resolves:
https://github.com/janus-idp/backstage-plugins/issues/681
Screenshots:
=> fix(topology): checluster resource to have matching labels for catalog entity

.github/workflows/publish-backend-plugin-manager.yaml
Avoid concurrent or useless runs
=> fix: avoid concurrent or useless workflow runs.

plugins/rh-rbac-backend/package.json, plugins/rh-rbac-backend/src/service/casbin-adapter-factory.ts, plugins/rh-rbac-backend/src/service/policies-rest-api.test.ts, plugins/rh-rbac-backend/src/service/policies-rest-api.ts, plugins/rh-rbac-backend/src/service/policy-builder.test.ts, plugins/rh-rbac-backend/tsconfig.json, plugins/rh-rbac-backend/turbo.json, plugins/rh-rbac-common/package.json, plugins/rh-rbac-common/tsconfig.json, plugins/rh-rbac-common/turbo.json, yarn.lock
Fix compilation and tests after rebase to the main branch.
https://github.com/janus-idp/backstage-plugins/pull/485
=> fix(rbac): fix compilation and tests

plugins/topology/README.md
Fixes: https://github.com/janus-idp/backstage-plugins/issues/681
handles https://github.com/janus-idp/backstage-plugins/pull/730#discussion_r1328623384 (missed review comment)
=> docs(topology): updates topology readme

plugins/rbac-backend/package.json, plugins/rbac-common/package.json
Removes the private designation from the package.json
=> fix(rbac): remove private package

plugins/rbac-backend/package.json, plugins/rbac-backend/src/service/policy-builder.ts
Adds the policy conf file to package.
fixes #821
=> fix(rbac): add models folder to package

plugins/tekton/README.md, plugins/tekton/dev/index.tsx, plugins/tekton/src/components/PipelineVisualizationRouter.tsx, plugins/tekton/src/consts/tekton-const.ts
**Resolves:**
https://github.com/janus-idp/backstage-plugins/issues/700
=> feat(tekton)!: enable tekton related features when the tekton annotation is present

plugins/analytics-module-matomo/.eslintrc.js, plugins/analytics-module-matomo/README.md, plugins/analytics-module-matomo/config.d.ts, plugins/analytics-module-matomo/dev/Playground.tsx, plugins/analytics-module-matomo/dev/index.tsx, plugins/analytics-module-matomo/package.json, plugins/analytics-module-matomo/src/api/index.ts, plugins/analytics-module-matomo/src/api/loadMatomo.ts, plugins/analytics-module-matomo/src/index.ts, plugins/analytics-module-matomo/src/plugin.test.ts, plugins/analytics-module-matomo/src/plugin.ts, plugins/analytics-module-matomo/src/routes.ts, plugins/analytics-module-matomo/src/setupTests.ts, plugins/analytics-module-matomo/tsconfig.json, plugins/analytics-module-matomo/turbo.json, yarn.lock
> Related to: backstage/backstage#15644
- Implemented analytics module for matomo
- Also includes the updated README documentation for usage guidelines
Developed by following the analytics plugin guidelines: https://backstage.io/docs/plugins/analytics/
=> feat(matomo): analytics module plugin for matomo

.github/workflows/pr-semantic.yaml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Resolves #204
This `CONTRIBUTING.md` is fairly extensive, though I hope it covers all aspects that potential contributor needs to know so they can contribute efficiently.
Please review from all angles - factual, technical, stylistic, and grammatical. I'm not a native speaker.
=> docs: add contributing guide

.github/workflows/publish-backend-plugin-manager.yaml
chore: fix copyrights to be consistent with other files
The Janus IDP Authors instead of just Janus Authors
N/A
N/A
=> chore: fix copyrights to be consistent with other files

plugins/tekton/src/hooks/useTektonObjectsResponse.ts
Resolves
https://github.com/janus-idp/backstage-plugins/issues/884
TODO:
_upload GIF_
=> fix(tekton): handle flaky cluster error gracefully

plugins/rbac-backend/package.json
This PR adds the models folder with the policy conf file and `config.d.ts` to the package.json
=> fix(rbac): add models folder and config.d.ts to package

plugins/rbac-backend/package.json
add migration folder to rbac-backend package
=> fix(rbac): add migration folder to rbac-backend package

plugins/acr/README.md, plugins/jfrog-artifactory/README.md, plugins/kiali/DEVELOPMENT.md, plugins/kiali/README.md, plugins/nexus-repository-manager/README.md, plugins/quay/README.md, plugins/topology/README.md
=> docs: update frontend plugin docs to use EntityLayout instead of EntityPageLayout

plugins/keycloak-backend/package.json, plugins/keycloak-backend/src/alpha.ts, plugins/keycloak-backend/src/module/catalogModuleKeycloakEntityProvider.test.ts, plugins/keycloak-backend/src/module/catalogModuleKeycloakEntityProvider.ts, plugins/keycloak-backend/src/module/index.ts, yarn.lock
Add dynamic backend module capabilities for the Keycloak backend plugin.
=> feat: update Keycloak plugin for dynamic backend

plugins/ocm/src/index.ts, yarn.lock
Part of: https://github.com/janus-idp/backstage-showcase/issues/725
Export default OCM icon as part of the dynamic plugin assets.
=> feat(ocm): export default icon for use in dynamic plugins

plugins/servicenow-actions/README.md
https://github.com/janus-idp/backstage-plugins/issues/925
=> docs(servicenow): add missing ServiceNow config in README

plugins/rbac-backend/src/database/casbin-adapter-factory.test.ts, plugins/rbac-backend/src/database/casbin-adapter-factory.ts
https://github.com/janus-idp/backstage-plugins/issues/913
=> fix(rbac): handle postgres ssl connection for rbac backend plugin

plugins/rbac-backend/package.json, yarn.lock
Use the same Knex version with backstage to make build more stable.
=> fix(rbac): use the same Knex version with Backstage

plugins/ocm-backend/src/index.ts
share the dynamic entrypoint in ocm backend
This was missed in a previous PR.
- Fixes #?
Please make sure that the following steps are complete:
=> fix: share the dynamic entrypoint in ocm backend

packages/cli/src/commands/export-dynamic-plugin/backend.ts
Fix possible dependency conflict with the resolutions added by the `export-dynamic-plugins` command.
- This PR is the basis to fix issue https://github.com/janus-idp/backstage-showcase/issues/790 ?
Please make sure that the following steps are complete:
=> fix(cli): fix possible dependency conflict

package.json
Revert push of derived package to fix the release pipeline.
=> fix: do not fail release on missing dist-dynamic

plugins/analytics-provider-segment/config.d.ts
Resolves: https://github.com/janus-idp/backstage-plugins/issues/959
=> fix: segment config schema visibility typo

plugins/analytics-provider-segment/package.json, plugins/analytics-provider-segment/src/index.ts
SSIA, makes segment frontend plugin dynamic
=> feat(segment): expose plugin also as a dynamic

plugins/analytics-provider-segment/package.json
=> chore: fix yarn.lock

plugins/shared-react/src/__fixtures__/1-pipelinesData.ts, plugins/tekton/README.md, plugins/tekton/src/__fixtures__/1-pipelinesData.ts, plugins/tekton/src/models.ts, plugins/topology/README.md, plugins/topology/src/__fixtures__/1-tektonResources.ts, plugins/topology/src/__fixtures__/workloadNodeData.ts, plugins/topology/src/pipeline-models.ts
**Resolves:**
https://github.com/janus-idp/backstage-plugins/issues/948
Updated tekton version from v1beta1 to v1
https://github.com/janus-idp/backstage-plugins/assets/22490998/36029d4d-6a0f-49eb-8b1c-24fd5e699c4e
=> fix(tekton): update tekton version in the documentation

plugins/aap-backend/app-config.janus-idp.yaml, plugins/acr/README.md, plugins/acr/app-config.janus-idp.yaml, plugins/acr/package.json, plugins/analytics-provider-segment/app-config.janus-idp.yaml, plugins/analytics-provider-segment/package.json, plugins/jfrog-artifactory/README.md, plugins/jfrog-artifactory/app-config.janus-idp.yaml, plugins/jfrog-artifactory/package.json, plugins/matomo-backend/README.md, plugins/matomo-backend/app-config.janus-idp.yaml, plugins/matomo/app-config.janus-idp.yaml, plugins/matomo/package.json, plugins/nexus-repository-manager/README.md, plugins/nexus-repository-manager/app-config.janus-idp.yaml, plugins/nexus-repository-manager/package.json, plugins/ocm-backend/app-config.janus-idp.yaml, plugins/ocm/app-config.janus-idp.yaml, plugins/ocm/package.json, plugins/openshift-image-registry/README.md, plugins/openshift-image-registry/app-config.janus-idp.yaml, plugins/openshift-image-registry/package.json, plugins/quay/app-config.janus-idp.yaml, plugins/tekton/README.md, plugins/tekton/app-config.janus-idp.yaml, plugins/tekton/package.json, plugins/topology/app-config.janus-idp.yaml, plugins/topology/package.json
Fixes: https://github.com/janus-idp/backstage-plugins/issues/960
=> fix: add config partials for dynamic frontend plugins

plugins/rbac-backend/README.md, plugins/rbac/src/components/RolesList.tsx, plugins/rbac/src/hooks/useRoles.test.ts, plugins/rbac/src/hooks/useRoles.ts
**Resolves:**
https://github.com/janus-idp/backstage-plugins/issues/997
Role with no associated permission policies
Role with an associated permission policy with effect deny
=> feat(rbac): list roles with no permission policies

app-config.yaml
Reverting  former mistakenly  committed change to the `app-config.yaml`.
=> chore: fix app-config for unintended change

yarn.lock
Running `yarn  install` on main results in the following diff
=> chore: sync yarn.lock

plugins/rbac/src/components/RbacPage.test.tsx, plugins/rbac/src/components/RolesList/RolesList.test.tsx, plugins/rbac/src/components/RolesList/RolesList.tsx, plugins/rbac/src/components/RolesList/RolesListToolbar.tsx, plugins/rbac/src/hooks/useRoles.ts
=> feat(rbac): show warning alert when user is not authorised to create roles

plugins/kiali-backend/OWNERS, plugins/kiali/OWNERS
Add owners to kiali* plugin
All of them are in the  [kiali GOVERNANCE](https://github.com/kiali/kiali/blob/master/GOVERNANCE.md)
=> feat(kiali): add OWNERS file to kiali* plugin

plugins/orchestrator-backend/dist-dynamic/package.json
Follow-up after https://github.com/janus-idp/backstage-plugins/pull/1080
=> fix(orchestrator): regenerate `orchestrator-backend/dist-dynamic/package.json`

plugins/notifications-backend/README.md
[FLPATH-875](https://issues.redhat.com//browse/FLPATH-875)
https://issues.redhat.com/browse/FLPATH-875
=> fix(notifications): create DB upon startup

plugins/rbac/src/api/RBACBackendClient.ts, plugins/rbac/src/components/RbacPage.test.tsx, plugins/rbac/src/components/RolesList/RolesList.test.tsx, plugins/rbac/src/components/RolesList/RolesList.tsx, plugins/rbac/src/hooks/useRoles.ts
**Resolves:**
https://github.com/janus-idp/backstage-plugins/issues/1030
**GIF:**
https://github.com/janus-idp/backstage-plugins/assets/22490998/92d08248-00b4-4f54-aa4b-35292291e03a
Error scenarios
https://github.com/janus-idp/backstage-plugins/assets/22490998/7e3c9464-9b87-4950-a4f6-5a5e6ccbf7fa
=> fix(rbac): fix the roles table to also watch policies

plugins/rbac-backend/docs/permissions.md, plugins/rbac-backend/src/service/permission-policy.test.ts, plugins/rbac-backend/src/service/permission-policy.ts, plugins/rbac-backend/src/service/role-manager.test.ts, plugins/rbac-backend/src/service/role-manager.ts
https://github.com/janus-idp/backstage-plugins/issues/935
=> fix(rbac): fix work resource permission specified by name

plugins/notifications-backend/src/service/handlers.ts
[FLPATH-876](https://issues.redhat.com//browse/FLPATH-876)
https://issues.redhat.com/browse/FLPATH-876
=> fix(notifications): filtering by text does not work with sqlite

plugins/rbac/src/components/RolesList/RolesListToolbar.tsx, plugins/rbac/src/components/SnackbarAlert.tsx
Fixes: https://github.com/janus-idp/backstage-plugins/issues/1069
=> feat(rbac): center align toast

plugins/notifications-backend/package.json, plugins/notifications-backend/src/service/standaloneServer.ts, plugins/notifications-backend/src/service/types.ts
=> chore: replace winston rependency by LoggerService

plugins/notifications-backend/src/service/handlers.ts
[FLPATH-885](https://issues.redhat.com//browse/FLPATH-885)
https://issues.redhat.com/browse/FLPATH-885
=> fix(notifications): create fails when array fields are empty

plugins/kiali-backend/app-config.janus-idp.yaml, plugins/kiali-backend/dist-dynamic/package.json
Remove the strategy parameter in dinamic plugin
=> fix(kiali): remove strategy in dinamyc plugin

plugins/orchestrator/src/__fixtures__/fakeLongProcessInstanceList.ts, plugins/orchestrator/src/components/WorkflowRunsTabContent.stories.tsx, plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx, plugins/orchestrator/src/constants.ts
Addresses:
- https://issues.redhat.com/browse/FLPATH-887
Replaces: https://github.com/janus-idp/backstage-plugins/pull/1124
=> fix(orchestrator): set default workflow runs table size to 20

plugins/orchestrator/src/components/WorkflowsTable.tsx
Addresses:
- https://issues.redhat.com/browse/FLPATH-886
=> fix(orchestrator): fixes sorting by name in the workflows list

plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx
They  should be sorted by started date in descending order.
Addresses:
- https://issues.redhat.com/browse/FLPATH-888
=> fix(orchestrator): fixes sorting workflow runs

plugins/rbac/src/components/RoleOverview/MembersCard.test.tsx, plugins/rbac/src/components/RoleOverview/MembersCard.tsx, plugins/rbac/src/components/RoleOverview/PermissionsCard.test.tsx, plugins/rbac/src/components/RoleOverview/PermissionsCard.tsx, plugins/rbac/src/hooks/useMembers.ts, plugins/rbac/src/hooks/usePermissionPolicies.ts
Resolves:
https://github.com/janus-idp/backstage-plugins/issues/1101
GIF:
https://github.com/janus-idp/backstage-plugins/assets/22490998/388b7c2d-5e64-498c-9e61-06ce536a5c6e
=> fix(rbac): watch users and permission-policies

plugins/rbac-backend/src/service/permission-policy.test.ts, plugins/rbac-backend/src/service/permission-policy.ts
What does this pull request do:
Enable create button for default role:default/rbac_admin
=> fix(rbac): enable create button for default role:default/rbac_admin

plugins/kiali/src/pages/Kiali/Header/Header.tsx, plugins/kiali/src/pages/Overview/OverviewPage.tsx, plugins/kiali/src/pages/Overview/OverviewToolbar.tsx
Fix https://github.com/janus-idp/backstage-plugins/issues/1108
=> fix(kiali): show username when auth is anonymous

plugins/rbac-backend/config.d.ts, plugins/rbac-backend/migrations/20231212224526_migrations.js, plugins/rbac-backend/migrations/20231221113214_migrations.js, plugins/rbac-backend/package.json, plugins/rbac-backend/src/database/conditional-storage.ts, plugins/rbac-backend/src/database/migration.ts, plugins/rbac-backend/src/database/policy-metadata-storage.test.ts, plugins/rbac-backend/src/database/policy-metadata-storage.ts, plugins/rbac-backend/src/database/role-metadata.test.ts, plugins/rbac-backend/src/database/role-metadata.ts, plugins/rbac-backend/src/helper.ts, plugins/rbac-backend/src/service/enforcer-delegate.ts, plugins/rbac-backend/src/service/permission-policy.test.ts, plugins/rbac-backend/src/service/permission-policy.ts, plugins/rbac-backend/src/service/policies-rest-api.test.ts, plugins/rbac-backend/src/service/policies-rest-api.ts, plugins/rbac-backend/src/service/policies-validation.ts, plugins/rbac-backend/src/service/policy-builder.ts, plugins/rbac-backend/src/service/test/data/rbac-policy.csv, plugins/rbac-common/src/types.ts, yarn.lock
https://github.com/janus-idp/backstage-showcase/issues/776
https://github.com/janus-idp/backstage-plugins/issues/944
https://github.com/janus-idp/backstage-plugins/issues/1103
=> fix(rbac): split policies and roles by source

plugins/ocm-backend/src/alpha.ts, plugins/orchestrator-backend/src/alpha.ts
Add missing alpha  dynamic plugin entry points for the new backend system.
Signed-off-by: David Festal <dfestal@redhat.com>
=> fix: add missing alpha  dynamic plugin entry points

plugins/rbac/README.md
**Resolves:**
https://github.com/janus-idp/backstage-plugins/issues/1114
=> fix(rbac): update the RBAC frontend plugin readme

plugins/3scale-backend/app-config.janus-idp.yaml
See https://github.com/janus-idp/backstage-showcase/pull/948
JIRA: https://issues.redhat.com/browse/RHIDP-1030
Fixes https://github.com/janus-idp/backstage-showcase/issues/849
This is a PR to adopt Hugo's suggestions, see: https://github.com/janus-idp/backstage-showcase/pull/948#issuecomment-1927575321
Merge with: https://github.com/janus-idp/backstage-showcase/pull/951
=> fix(3scale): modify 3scale environment variables - using THREESCALE

plugins/orchestrator-backend/OWNERS, plugins/orchestrator-common/OWNERS, plugins/orchestrator/OWNERS
@kadel Could you please invite @batzionb? Thanks!
=> chore(orchestrator): add new code owner

plugins/tekton/README.md, plugins/tekton/src/hooks/usePodLogsOfPipelineRun.ts, plugins/topology/src/components/Topology/TopologySideBar/PodLogs/PodLogs.test.tsx, plugins/topology/src/components/Topology/TopologySideBar/PodLogs/PodLogs.tsx, plugins/topology/src/components/Topology/TopologySideBar/PodLogs/PodLogsDialog.test.tsx, plugins/topology/src/components/Topology/TopologySideBar/PodLogs/PodLogsDialog.tsx, plugins/topology/src/hooks/usePodLogs.test.ts, plugins/topology/src/hooks/usePodLogs.ts
Resolves:
https://github.com/janus-idp/backstage-plugins/issues/1017
=> fix(topology/tekton): stop polling after log streaming completes

plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
Addresses:
- https://issues.redhat.com/browse/FLPATH-961
=> fix(orchestrator): removes the divider from the workflow definition card

plugins/rbac/src/components/CreateRole/AddedMembersTableColumn.tsx, plugins/rbac/src/utils/create-role-utils.ts
Fixes: https://github.com/janus-idp/backstage-plugins/issues/1109
=> fix(rbac): show 0 if no members in a group

plugins/rbac/src/utils/create-role-utils.test.ts
Add test for https://github.com/janus-idp/backstage-plugins/pull/1187
=> fix(rbac): add test for 0 members in group

plugins/orchestrator/package.json, plugins/orchestrator/src/components/InfoDialog.stories.tsx, plugins/orchestrator/src/components/InfoDialog.tsx
Jira: [https://issues.redhat.com/browse/FLPATH-853](https://issues.redhat.com/browse/FLPATH-853)
Build a information dialog component to ask user to confirm or show alert to user.
=> feat: build Information dialog component to show confirmation or alert

plugins/orchestrator/src/__fixtures__/fakeWorkflowRunDetails.ts, plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx, plugins/orchestrator/src/components/WorkflowRunDetails.stories.tsx, plugins/orchestrator/src/components/WorkflowRunDetails.tsx
Addresses:
- https://issues.redhat.com/browse/FLPATH-959
[Screencast from 2024-02-11 15-21-42.webm](https://github.com/janus-idp/backstage-plugins/assets/77008341/2eaec5c0-265d-4be7-bb91-198eb37f7d0b)
=> fix(orchestrator): the instance details card content is cropped

CONTRIBUTING.md
Add additional responsibilities related to following upstream ADRs and upgrading Backstage versions to align with Showcase
https://issues.redhat.com/browse/RHIDP-1310
=> chore: update the contributing guide with plugin provider responsibilities

packages/backend/package.json, plugins/rbac/src/components/RbacPage.tsx
**Fixes:**
https://issues.redhat.com/browse/RHIDP-1323
- Fixes the tab route
- using the latest rbac-backend package
**GIF:**
https://github.com/janus-idp/backstage-plugins/assets/22490998/44e0a92f-cd79-4b61-ac3e-f3919412e8a4
=> fix(rbac): fix rbac tab route

plugins/quay/OWNERS, plugins/tekton/OWNERS
Add OWNERS file to tekton and quay plugin.
=> chore(tekton,quay): add OWNERS file to tekton and quay plugins

plugins/orchestrator-backend/__fixtures__/mockComposedGreetingWorfklow.ts, plugins/orchestrator-backend/__fixtures__/mockGreetingWorkflowData.ts, plugins/orchestrator-backend/__fixtures__/mockSpringBootWorkflowData.ts, plugins/orchestrator-backend/src/service/DataInputSchemaService.test.ts, plugins/orchestrator-backend/src/service/DataInputSchemaService.ts, plugins/orchestrator-backend/src/service/router.ts, plugins/orchestrator-common/src/types.ts, plugins/orchestrator/src/__fixtures__/fakeWorkflowDataInputSchemaDifferentTypes.ts, plugins/orchestrator/src/__fixtures__/fakeWorkflowDataInputSchemaResponseMultiStep.ts, plugins/orchestrator/src/__fixtures__/fakeWorkflowDataInputSchemaResponseMultiStepInitialState.ts, plugins/orchestrator/src/__fixtures__/fakeWorkflowInputSchemaResponse.ts, plugins/orchestrator/src/api/MockOrchestratorClient.ts, plugins/orchestrator/src/api/OrchestratorClient.ts, plugins/orchestrator/src/api/api.ts, plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.stories.tsx, plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.tsx, plugins/orchestrator/src/components/ExecuteWorkflowPage/StepperForm.tsx
[FLPATH-992](https://issues.redhat.com/browse/FLPATH-992)
review step of multi step schema:
=> fix(orchestrator): resolve mismatch between execution data and composed schema

plugins/orchestrator/src/components/InfoDialog.tsx, plugins/orchestrator/src/components/WorkflowInstancePage.tsx
Jira: [https://issues.redhat.com/browse/FLPATH-978](https://issues.redhat.com/browse/FLPATH-978)
Display a confirmation dialog before the user aborts a running workflow.
=> feat(orchestrator): display a confirmation dialog before the user aborts a running workflow

plugins/kiali/src/components/VirtualList/Renderers.tsx, plugins/kiali/src/components/VirtualList/VirtualList.tsx, plugins/kiali/src/pages/WorkloadList/WorkloadListPage.tsx, plugins/kiali/src/styles/StyleUtils.ts
- Fix scroll and avoid table resize based on context
- Remove links for items details
=> fix(kiali): update styles, remove item details links

plugins/rbac/src/components/CreateRole/AddMembersForm.tsx, plugins/rbac/src/components/CreateRole/MembersDropdownOption.tsx, plugins/rbac/src/components/CreateRole/PermissionPoliciesForm.tsx, plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx, plugins/rbac/src/components/CreateRole/PoliciesCheckboxGroup.tsx, plugins/rbac/src/components/RolesList/DeleteRoleDialog.tsx, plugins/rbac/src/components/RolesList/RolesList.test.tsx, plugins/rbac/src/components/RolesList/RolesListColumns.tsx, plugins/rbac/src/components/SnackbarAlert.tsx
**Resolves:**
https://issues.redhat.com/browse/RHIDP-1341
=> fix(rbac): add data-testid, names and aria-label to RBAC UI components

plugins/rbac-backend/README.md, plugins/rbac-backend/config.d.ts, plugins/rbac-backend/migrations/20240215154456_migrations.js, plugins/rbac-backend/model/rbac-policy.csv, plugins/rbac-backend/package.json, plugins/rbac-backend/src/service/policy-builder.test.ts, plugins/rbac-backend/src/service/policy-builder.ts
Drop database disabled mode.
https://issues.redhat.com/browse/RHIDP-1244
=> fix(rbac): drop database disabled mode

packages/backend/package.json, plugins/rbac/src/components/RolesList/DeleteRoleDialog.tsx, yarn.lock
Part of https://github.com/janus-idp/backstage-plugins/pull/1224
=> fix(rbac): add test selectors

CONTRIBUTING.md
Update guide to include suggestion for installing the pre-commit hook
https://issues.redhat.com/browse/RHIDP-867
=> chore(docs): update contributing guide to include pre-commit hook

plugins/orchestrator-backend/src/service/CloudEventService.ts, plugins/orchestrator-backend/src/service/DataIndexService.ts, plugins/orchestrator-backend/src/service/JiraService.ts, plugins/orchestrator-backend/src/service/router.ts, plugins/orchestrator-common/config.d.ts, plugins/orchestrator-common/src/constants.ts
- Fix interaction with JIRA for demo purposes: the `targetUrl` was missing when sending the cloud event
- Update the DevMode image tag to `main-2024-02-19`
- Change the default editor path to a URL that works on the VPN and has a fixed version `0.32.0`
=> fix(orchestrator): minor improvements and fixes

plugins/analytics-module-matomo/README.md
Tried using the Matomo Plugin but had to take a look in the Code to make it work. Fixed the documentiation for future users.
=> docs(matomo-plugin): fix config example and replace GA with Matomo

plugins/orchestrator/src/components/WorkflowInstancePage.tsx
Jira: [https://issues.redhat.com/browse/FLPATH-995](https://issues.redhat.com/browse/FLPATH-995)
Display a alert dialog when the user fails to abort a running workflow
=> feat(orchestrator): display a alert dialog when the user fails to abort a running workflow

plugins/rbac/src/components/CreateRole/EditRolePage.tsx, plugins/rbac/src/components/RoleOverview/AboutCard.test.tsx, plugins/rbac/src/components/RoleOverview/AboutCard.tsx, plugins/rbac/src/components/RoleOverview/RoleOverviewPage.tsx, plugins/rbac/src/hooks/useRole.test.ts, plugins/rbac/src/hooks/useRole.ts, plugins/rbac/src/hooks/useRoles.ts, plugins/rbac/src/hooks/useSelectedMembers.test.ts, plugins/rbac/src/hooks/useSelectedMembers.ts, plugins/rbac/src/utils/create-role-utils.test.ts, plugins/rbac/src/utils/create-role-utils.ts
https://github.com/janus-idp/backstage-showcase/issues/898
P.S.: It would be nice to merge it for GA 1.1
=> feat(rbac): save and display role description in the frontend

plugins/notifications-backend/README.md
[FLPATH-901](https://issues.redhat.com//browse/FLPATH-901)
https://issues.redhat.com/browse/FLPATH-901
=> fix(notifications): bug flpath-901 spelling messageID

plugins/notifications-backend/package.json
To address change towards `backend-next` of the Backstage.
Fixes: [FLPATH-997](https://issues.redhat.com//browse/FLPATH-997)
=> fix(notifications): add dynamicPluginInstaller

plugins/notifications-backend/src/service/handlers.ts
[RHIDP-1210](https://issues.redhat.com//browse/RHIDP-1210)
https://github.com/janus-idp/backstage-plugins/issues/1175
=> fix(notifications): rhidp-1210 Unable to get group notifications

plugins/notifications/README.md
[FLPATH-1055](https://issues.redhat.com//browse/FLPATH-1055)
https://issues.redhat.com/browse/FLPATH-1055
=> fix(notifications): replace NotificationsSidebarItem with NotificationsActiveIcon

plugins/notifications-backend/README.md
[FLPATH-1057](https://issues.redhat.com//browse/FLPATH-1057)
https://issues.redhat.com/browse/FLPATH-1057
=> fix(notifications): users.yaml path is wrong

plugins/orchestrator/src/components/WorkflowDescriptionModal.tsx, plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
Jira: [https://issues.redhat.com/browse/FLPATH-924](https://issues.redhat.com/browse/FLPATH-924)
Display a description modal before triggering infra-wfs that resulted from an assessment wf
=> feat(orchestrator): display a description modal before triggering infra-wfs that resulted from an assessment wf

plugins/rbac/package.json, plugins/rbac/playwright.config.ts, plugins/rbac/tests/rbac.spec.ts, plugins/rbac/tests/rbacHelper.ts
playwright tests for the RBAC plugin in dev setup
Tracks: https://issues.redhat.com/browse/RHIDP-1463
=> test(rbac): add playwright tests for the plugin

plugins/notifications-backend/src/service/db.ts, plugins/notifications-backend/src/service/handlers.test.ts, plugins/notifications-backend/src/service/handlers.ts
[FLPATH-1076](https://issues.redhat.com//browse/FLPATH-1076)
https://issues.redhat.com/browse/FLPATH-1076
=> fix(notifications): notifications time is wrong when using sqlite

plugins/orchestrator-common/src/auto-generated/api/definition.ts, plugins/orchestrator-common/src/auto-generated/api/models/schema.ts, plugins/orchestrator-common/src/auto-generated/docs/index.adoc/index.adoc, plugins/orchestrator-common/src/openapi/openapi.yaml
Added missing openapi-spec changes required to identify newly introduced query parameters.
=> fix(orchestrator): add missing query parameter changes for /overview endpoint

plugins/notifications-backend/src/service/router.ts
[FLPATH-1091](https://issues.redhat.com//browse/FLPATH-1091)
https://issues.redhat.com/browse/FLPATH-1091
=> fix(notifications): return a detailed message for validation errors

plugins/kiali/src/components/MessageCenter/MessageCenter.tsx, plugins/kiali/src/components/VirtualList/Config.tsx, plugins/kiali/src/components/VirtualList/Renderers.tsx, plugins/kiali/src/components/VirtualList/VirtualItem.tsx, plugins/kiali/src/components/VirtualList/VirtualList.tsx, plugins/kiali/src/pages/AppDetails/AppDetailsPage.tsx, plugins/kiali/src/pages/AppList/AppListPage.tsx, plugins/kiali/src/pages/Kiali/Header/HelpKiali.tsx, plugins/kiali/src/pages/Kiali/Header/KialiHeaderEntity.tsx, plugins/kiali/src/pages/Kiali/KialiEntity.tsx, plugins/kiali/src/pages/Overview/ListView/ListViewPage.tsx, plugins/kiali/src/pages/Overview/OverviewPage.tsx, plugins/kiali/src/pages/ServiceDetails/ServiceDetailsPage.tsx, plugins/kiali/src/pages/ServiceList/ServiceListPage.tsx, plugins/kiali/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, plugins/kiali/src/pages/WorkloadList/WorkloadListPage.tsx, plugins/kiali/src/types/types.ts
Update entity view with a list card.
- Updated general styles 
- Reduced view of the table
=> feat(kiali): include a new List entity view

plugins/analytics-module-matomo/OWNERS, plugins/analytics-module-matomo/app-config.janus-idp.yaml, plugins/analytics-module-matomo/package.json, plugins/analytics-module-matomo/src/api/Matomo.ts, plugins/analytics-module-matomo/src/api/index.ts, yarn.lock
Adding dynamic plugin support for the matomo analytics module.
=> feat(matomo-analytics): export apifactory for dynamic plugin

plugins/orchestrator/src/components/Selector.tsx
https://issues.redhat.com/browse/FLPATH-897
Give it a width and remove the `native` property.
=> fix(orchestrator): fix dropdown look

plugins/rbac/src/api/RBACBackendClient.test.ts, plugins/rbac/src/components/Administration.test.tsx, plugins/rbac/src/components/CreateRole/AddMembersForm.test.tsx, plugins/rbac/src/components/CreateRole/AddMembersForm.tsx, plugins/rbac/src/components/CreateRole/AddedMembersTable.test.tsx, plugins/rbac/src/components/CreateRole/CreateRolePage.test.tsx, plugins/rbac/src/components/CreateRole/EditRolePage.test.tsx, plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.test.tsx, plugins/rbac/src/components/CreateRole/ReviewStep.test.tsx, plugins/rbac/src/components/CreateRole/ReviewStepTable.tsx, plugins/rbac/src/components/CreateRole/RoleForm.test.tsx, plugins/rbac/src/components/EditRole.test.tsx, plugins/rbac/src/components/RolesList/DeleteRole.test.tsx, plugins/rbac/src/components/RolesList/DeleteRoleDialog.test.tsx, plugins/rbac/src/components/Router.test.tsx, plugins/rbac/src/components/SnackbarAlert.test.tsx
[RHIDP-1281](https://issues.redhat.com/browse/RHIDP-1281): Increase unit test coverage of RBAC UI plugin
Increased test coverage to 80.84%.
And fixed some console warnings/errors.
=> chore(rbac): increase rbac test coverage

.github/dependabot.yml
Fix the prettier lint issue in dependabot.yml file which is causing the Test checks to fails in all PR
cc: @invincibleJai
=> chore(prettier): fix prettier lint issue in test check

package.json
regen lockfiles when updating backstage
=> chore(scripts): regen lockfiles when updating backstage

plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.tsx, plugins/orchestrator/src/components/ExecuteWorkflowPage/StepperForm.tsx
Fixes: [FLPATH-1129](https://issues.redhat.com//browse/FLPATH-1129)
=> fix(orchestrator): remove error on Reset workflow

plugins/3scale-backend/dist-dynamic/yarn.lock, plugins/aap-backend/dist-dynamic/yarn.lock, plugins/keycloak-backend/dist-dynamic/yarn.lock, plugins/kiali-backend/dist-dynamic/package.json, plugins/kiali-backend/dist-dynamic/yarn.lock, plugins/kubernetes-actions/dist-dynamic/package.json, plugins/kubernetes-actions/dist-dynamic/yarn.lock, plugins/matomo-backend/dist-dynamic/yarn.lock, plugins/notifications-backend/dist-dynamic/yarn.lock, plugins/ocm-backend/dist-dynamic/yarn.lock, plugins/orchestrator-backend/dist-dynamic/yarn.lock, plugins/quay-actions/dist-dynamic/yarn.lock, plugins/regex-actions/dist-dynamic/yarn.lock, plugins/servicenow-actions/dist-dynamic/yarn.lock, plugins/sonarqube-actions/dist-dynamic/yarn.lock, yarn.lock
=> chore(lockfiles): regen lockfiles

plugins/notifications-backend/src/service/handlers.ts
https://issues.redhat.com/browse/FLPATH-1163
=> fix(notifications): flpath-1163

plugins/orchestrator-common/src/constants.ts
Nightly tags are back so I'm updating the one we use to the most recent one.
=> fix(orchestrator): update devmode container tag

packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts
In some corner cases, the `node_modules` folder of the main plugin was unexpectedly copied to the `dist-dynamic` folder. This leads to an erroneous situation where shared packages are added in the dynamic plugin private dependencies.
=> fix(cli): `node_modules` of the main plugin unexpectedly copied to the `dist-dynamic` folder.

.github/actions/build/action.yaml, .github/actions/test/action.yaml, .github/workflows/pr-website.yaml, plugins/rbac-node/README.md, plugins/shared-react/README.md
chore(deps): [RHIDP-1203](https://issues.redhat.com//browse/RHIDP-1203) fail the build if workspace dirty after a yarn install (yarn.lock changed)
N/A
https://issues.redhat.com/browse/RHIDP-1203
N/A
=> chore(deps): fail the build if workspace dirty after a yarn install (yarn.lock changed) (RHIDP-1203)

plugins/feedback/README.md
As @awanlin suggested here https://github.com/backstage/backstage/pull/24184\#discussion_r1560988756 it would be good if screenshots are not hidden
=> fix(feedback-docs): move out collapsed screenshots

plugins/notifications-backend/src/service/handlers.ts
cherry-pick https://github.com/janus-idp/backstage-plugins/commit/836e161d822536874833e8b1d6f535c4bfcbb5a6
=> fix(notifications): flpath-1163 (#1394)

yarn.lock
resolve CI failure because of dirty yarn.lock
=> chore(deps): update yarn.lock to make CI Pass

yarn.lock
Signed-off-by: Nick...
chore: yarn install
N/A
N/A
=> chore: yarn install

.github/workflows/push.yaml, package.json
chore: allow semantic-release from main and 1.1.x+ branches (but not 1.0.x) [RHIDP-1720](https://issues.redhat.com//browse/RHIDP-1720)
N/A
N/A
=> chore: allow semantic-release from main and 1.1.x+ branches (but not 1.0.x) RHIDP-1720

plugins/bulk-import/src/components/AddRepositories/AddRepositoriesDrawer.tsx, plugins/bulk-import/src/components/AddRepositories/AddRepositoriesTableToolbar.tsx, plugins/bulk-import/src/components/AddRepositories/OrganizationTableRow.tsx, plugins/bulk-import/src/components/AddRepositories/ReposSelectDrawerColumnHeader.ts, plugins/bulk-import/src/components/AddRepositories/RepositoriesHeader.tsx, plugins/bulk-import/src/components/AddRepositories/RepositoriesTable.tsx, plugins/bulk-import/src/components/AddRepositories/RepositoryTableRow.tsx, plugins/bulk-import/src/components/AddRepositories/mockData.ts, plugins/bulk-import/src/types.ts, plugins/bulk-import/src/utils/repository-utils.tsx, plugins/bulk-import/tests/bulkImport.spec.ts
For [RHIDP-1665](https://issues.redhat.com/browse/RHIDP-1665): Allow users to select repositories from organization
Updated screen recording(updated on **4/16**):
https://github.com/janus-idp/backstage-plugins/assets/26255262/c0461e5b-459c-4960-a6d3-36dce17d5db6
=> feat(bulk-import): allow user to select repositories from side panel

plugins/rbac-backend/src/service/enforcer-delegate.ts, plugins/rbac-backend/src/service/permission-policy.ts
This PR aims to improve the performance of the RBAC Backend Plugin by doing two things. First, when we go to create a temporary enforcer during enforcement, we will set lazy load to true. This will prevent the permission policies and roles from all being loaded in at once. Second, we further decrease the permission policies that we wish to load in after initializing by gathering the roles that a particular user is associated with.
- [RHIDP-2005](https://issues.redhat.com/browse/RHIDP-2005)
=> feat(rbac): lazy load temporary enforcer

.github/actions/build/action.yaml, .github/actions/test/action.yaml, .github/workflows/pr.yaml, package.json
Seeing how CI fares here. 
I think we many want to consider testing on both Node.js 18 and 20 in the workflow, though.
=> chore(ci): matrix build/test multiple Node.js versions

yarn.lock
chore: bore: snore: regen yarn lock
Signed-off-by: Nick Boldt...
regen yarn lock
N/A
N/A
=> chore: bore: snore: regen yarn lock

OWNERS
- Add additional owners for NA coverage
- Removed @tumido since he no longer works on the project (required for annual access re-validation)
=> chore(owners): add NA Roster

plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx
https://issues.redhat.com/browse/FLPATH-1226
=> fix(orchestrator): disable sorting ID column in workflow runs table

package.json
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
=> feat: tagRelease.sh bump versions in 1.1.x for 1.1 release

plugins/ocm-backend/src/helpers/parser.ts, plugins/ocm/README.md, plugins/rbac-backend/docs/permissions.md
**Resolves:**
https://issues.redhat.com/browse/RHIDP-2240
=> fix(ocm): update ocm frontend plugin readme

plugins/kiali-backend/package.json, yarn.lock
Remove kiali-common that was removed so time ago.
=> fix(kiali): remove kiali-common from package.

yarn.lock
the lockfile in main is out of sync, failing CI builds, this should bring it up to date
=> fix: sync lockfile

plugins/argocd/dev/__data__/applications.ts, plugins/argocd/dev/__data__/config.ts, plugins/argocd/package.json, plugins/argocd/playwright.config.ts, plugins/argocd/tests/argocd.spec.ts, plugins/argocd/tests/utils.ts
just adding some UI tests for #1540
=> test(argocd): add playwright dev mode tests

plugins/rbac-backend/src/service/policies-rest-api.test.ts, plugins/rbac-backend/src/service/policies-rest-api.ts, plugins/rbac-backend/src/service/policy-builder.test.ts, plugins/rbac-backend/src/service/policy-builder.ts
Implement ability to disable rbac-backend plugin
Fixes: https://issues.redhat.com/browse/RHIDP-1449
=> fix(rbac): implement ability to disable rbac-backend plugin

plugins/orchestrator/README.md
This PR aligns the README file in the stable branch with its version in the  main branch
Addresses:
- https://issues.redhat.com/browse/FLPATH-1145
=> docs(orchestrator): align readme file with main

plugins/argocd/dev/__data__/applications.ts, plugins/argocd/src/components/AppStatus/AppNamespace.tsx, plugins/argocd/src/components/AppStatus/__tests__/AppNamespace.test.tsx, plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleCard.tsx, plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleDrawer.tsx, plugins/argocd/tests/argocd.spec.ts
Fixes sonarcloud warnings in the argocd test data file and extracted common code into a separate component
=> fix(argocd): fix sonarcloud lint warnings in argocd plugin

.github/CODEOWNERS
- Created github teams for renovate.  They can also be used in the codeowners file
=> chore(codeowners): clean up codeowners file

plugins/analytics-module-matomo/OWNERS, plugins/argocd/OWNERS, plugins/feedback-backend/OWNERS, plugins/feedback/OWNERS, plugins/quay/OWNERS, plugins/tekton/OWNERS
* got confirmation from the devex and rhtap teams that these files can be removed from their plugins
=> chore(owners): remove OWNERS files from devex and rhtap plugins

plugins/feedback-backend/README.md, plugins/feedback-backend/dist-dynamic/package.json, plugins/feedback-backend/dist-dynamic/yarn.lock, plugins/feedback-backend/package.json, plugins/feedback-backend/src/database/feedbackStore.ts, plugins/feedback-backend/src/index.ts, plugins/feedback-backend/src/plugin.ts, plugins/feedback-backend/src/service/emails.ts, plugins/feedback-backend/src/service/router.test.ts, plugins/feedback-backend/src/service/router.ts, plugins/feedback-backend/src/service/standaloneServer.ts, plugins/feedback/app-config.janus-idp.yaml, plugins/feedback/src/api/index.ts, plugins/feedback/src/plugin.ts, yarn.lock
- use backstage AuthService to get token for catalog api
- use backstage LoggerSevice
- use backstage FetchApi in frontend plugin ( fixes #1626 )
- updated tests
=> feat(feedback): use backstage auth service in backend plugin

plugins/orchestrator/README.md
Signed-off-by: Roy Golan <rgolan@redhat.com>
=> chore(orchestrator): point the README at the new backstage-orchestrator-workflows repo

plugins/servicenow-actions/.eslintrc.js
For [RHIDP-2308](https://issues.redhat.com/browse/RHIDP-2308)
=> fix(lint): ignore lint rules on generated code

plugins/quay/src/components/QuayRepository/QuayRepository.test.tsx, plugins/quay/src/components/QuayRepository/QuayRepository.tsx
For [RHIDP-1283](https://issues.redhat.com/browse/RHIDP-1283)
=> fix(quay): remove unuseful link

plugins/orchestrator-backend/src/service/DataIndexService.ts, plugins/orchestrator-backend/src/service/router.ts, plugins/orchestrator/src/__fixtures__/fakeWorkflowDataInputSchemaResponseMultiStep.ts
Addresses:
- https://issues.redhat.com/browse/FLPATH-1316
=> fix(orchestrator): fixes many security-related issues

plugins/rbac/src/components/CreateRole/AddMembersForm.tsx, plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
Fixes: https://issues.redhat.com/browse/RHIDP-1775
=> fix(rbac): fix mui autocomplete related warnings

plugins/audit-log-node/package.json
Update the audit log common package to public so that it can be published.
=> chore(audit-log): change package to public

plugins/rbac/src/components/ConditionalAccess/ConditionalAccessSidebar.tsx, plugins/rbac/src/components/ConditionalAccess/ConditionsForm.test.tsx, plugins/rbac/src/components/ConditionalAccess/ConditionsForm.tsx, plugins/rbac/src/components/ConditionalAccess/ConditionsFormRow.tsx, plugins/rbac/src/components/ConditionalAccess/ConditionsFormRowFields.tsx, plugins/rbac/src/components/CreateRole/PermissionPoliciesForm.tsx, plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
Fixes: https://issues.redhat.com/browse/RHIDP-2369
https://github.com/janus-idp/backstage-plugins/assets/20724543/704af55f-1a46-4c7a-9dbd-6f06794eb525
=> fix(rbac): enable save on remove-all button click

plugins/orchestrator-backend/turbo.json, plugins/orchestrator-common/.gitignore, plugins/orchestrator-common/package.json, plugins/orchestrator-common/scripts/openapi.sh, plugins/orchestrator-common/src/generated/client/core/ApiError.ts, plugins/orchestrator-common/src/generated/client/core/ApiRequestOptions.ts, plugins/orchestrator-common/src/generated/client/core/ApiResult.ts, plugins/orchestrator-common/src/generated/client/core/CancelablePromise.ts, plugins/orchestrator-common/src/generated/client/core/OpenAPI.ts, plugins/orchestrator-common/src/generated/client/core/request.ts, plugins/orchestrator-common/src/generated/client/core/types.ts, plugins/orchestrator-common/src/generated/client/index.ts, plugins/orchestrator-common/src/generated/client/models.ts, plugins/orchestrator-common/src/generated/client/schemas.ts, plugins/orchestrator-common/src/generated/client/services.ts, plugins/orchestrator-common/turbo.json, plugins/orchestrator/turbo.json
This is necessary to fix all the build and test issues we're facing for missing generated code.
Removing turborun dependencies too, we'll revise this choice in following PRs.
=> chore(orchestrator): add genenerated client

yarn.lock
Signed-off-by:...
chore(deps): regen yarn lock
N/A
N/A
=> chore(deps): regen yarn lock

package.json, plugins/topology-common/package.json, plugins/topology/package.json, yarn.lock
This PR just merges #1744 (+ an updated `yarn.lock` from a single `yarn install` run) and #1740
/cc @nickboldt @ciiay
=> chore(deps): fix dependency issues on main

plugins/topology-common/package.json
chore(release): manually release v1.0.0 of topology-common
using 'cd plugins/topology-common; npm publish --cwd . --access public -w .'
N/A
N/A
=> chore(release): manually release v1.0.0 of topology-common

plugins/rbac/src/types.ts, plugins/rbac/src/utils/rbac-utils.test.ts, plugins/rbac/src/utils/rbac-utils.ts, plugins/rbac/tests/rbac.spec.ts
**Resolves:**
https://issues.redhat.com/browse/RHIDP-2346
=> fix(rbac): show configure-access cta for existing simple permission policies in edit form

packages/cli/README.md, packages/cli/package.json, packages/cli/src/commands/index.ts, packages/cli/src/commands/metadata/command.ts, packages/cli/src/commands/metadata/index.ts, packages/cli/src/types.d.ts, yarn.lock
feat: add method for janus-cli package metadata (simpler PR) - [RHIDP-1502](https://issues.redhat.com//browse/RHIDP-1502)
N/A
N/A
=> feat: add method for janus-cli package metadata (simpler PR) - RHIDP-1502

plugins/rbac-backend/src/database/conditional-storage.ts, plugins/rbac-backend/src/database/conditional.storage.test.ts, plugins/rbac-backend/src/service/permission-policy.test.ts, plugins/rbac-backend/src/service/policies-rest-api.test.ts
Fix handling condition action conflicts
https://issues.redhat.com/browse/RHIDP-2322
=> fix(rbac): fix handling condition action conflicts

plugins/kiali-backend/src/service/router.test.ts, plugins/kiali/src/components/DebugInformation/DebugInformation.tsx, plugins/kiali/src/utils/Common.ts
- Sanitize input before appendChild
- Remove 'x-powered-by' from test express
=> fix(kiali): sanitize input

plugins/feedback/src/components/CreateFeedbackModal/CreateFeedbackModal.tsx, plugins/feedback/src/components/EntityFeedbackPage/EntityFeedbackPage.tsx
- changed button variant to contained
- change secondary color to error for Create Modal
- Moved jira note above in modal to make it more noticable
=> fix(feedback): update EntityPage component

plugins/orchestrator-backend/src/service/OrchestratorService.test.ts, plugins/orchestrator-backend/src/service/OrchestratorService.ts
cherry pick https://github.com/janus-idp/backstage-plugins/pull/1804
=> fix(orchestrator): fix error handling in case data index failed to start

plugins/orchestrator-backend/src/service/WorkflowCacheService.ts
Reduce the cache log messages noise by changing the log level to debug
=> fix(orchestrator): change log level of cache messages to be debug

plugins/kiali/src/components/Health/HealthIndicator.tsx, plugins/kiali/src/config/KialiIcon.tsx, plugins/kiali/src/dynamic/EntityKialiResourcesCard.tsx, plugins/kiali/tests/entityResources.spec.ts
Increase test coverage for resources card
=> feat(kiali): resources card test coverage

plugins/bulk-import/dev/index.tsx, plugins/bulk-import/src/components/BulkImportIcon.tsx, plugins/bulk-import/src/images/BulkImportIcon-White.svg, plugins/bulk-import/src/utils/icons.ts
**Resolves:**
https://issues.redhat.com/browse/RHIDP-2802
=> feat(bulk-import): update bulk import icon

plugins/rbac/src/components/CreateRole/ReviewStep.tsx, plugins/rbac/src/components/CreateRole/ReviewStepTable.tsx, plugins/rbac/src/components/CreateRole/SelectedPermissionPoliciesColumn.tsx, plugins/rbac/src/utils/create-role-utils.ts
Story: https://issues.redhat.com/browse/RHIDP-2771
Screenshot
=> feat(rbac): show total no. of rules in review and create step

package.json
=> feat: tagRelease.sh bump versions in 1.2.x for 1.2 release

package.json
…tream versioning (3.3 ~= 1.3)
=> Update package.json - bump to new version in main to align with downstream versioning (3.3 ~= 1.3)

plugins/orchestrator-backend/dist-dynamic/package.json, plugins/orchestrator-backend/dist-dynamic/yarn.lock, plugins/orchestrator-backend/package.json, plugins/orchestrator-backend/src/OrchestratorPlugin.ts, plugins/orchestrator-backend/src/routerWrapper/index.ts, plugins/orchestrator-backend/src/service/router.ts, plugins/orchestrator/src/components/WorkflowEditor/WorkflowEditor.tsx
Add AudditLogger to Orchestrator router
Take on the opportunity to also:
* re-organize endpoint declarations order
* fix a typo
=> feat(orchestrator): add auditLog and reorganize endpoints declaration

plugins/bulk-import/package.json, plugins/bulk-import/src/components/AddRepositories/RepositoriesTable.tsx, plugins/bulk-import/src/components/BulkImportPage.tsx, plugins/bulk-import/src/components/PreviewFile/PreviewFile.tsx, plugins/bulk-import/src/components/PreviewFile/PreviewPullRequest.tsx, plugins/bulk-import/src/components/Repositories/DeleteRepository.tsx, plugins/bulk-import/src/components/Repositories/DeleteRepositoryDialog.tsx, plugins/bulk-import/src/components/Repositories/EditCatalogInfo.tsx, plugins/bulk-import/src/components/Repositories/RepositoriesList.test.tsx, plugins/bulk-import/src/components/Repositories/RepositoriesList.tsx, plugins/bulk-import/src/components/Repositories/RepositoriesListColumns.tsx, plugins/bulk-import/src/components/Repositories/RepositoriesListForm.tsx, plugins/bulk-import/src/components/Repositories/SyncRepository.tsx, plugins/bulk-import/src/types.ts, plugins/bulk-import/src/utils/repository-utils.tsx, plugins/bulk-import/tests/bulkImport.spec.ts, yarn.lock
Resolves:
[RHDIP-1769](https://issues.redhat.com/browse/RHIDP-1769): Add row actions to the Added repositories table
**Note**:
This PR is based off #1541 .
Screen recording(updated 6/4):
https://github.com/janus-idp/backstage-plugins/assets/26255262/ef1e7d49-ffad-4b5b-92a0-93422bd090e3
Updates(5/1):
Update(6/4)
=> feat(bulk-import): add repo row actions

plugins/rbac-backend/docs/apis.md, plugins/rbac-backend/src/audit-log/audit-logger.ts, plugins/rbac-backend/src/service/plugin-endpoint.test.ts, plugins/rbac-backend/src/service/plugin-endpoints.ts, plugins/rbac-backend/src/service/policies-rest-api.test.ts, plugins/rbac-common/src/types.ts, plugins/rbac/dev/index.tsx, plugins/rbac/src/__fixtures__/mockPermissionPolicies.ts, plugins/rbac/src/api/RBACBackendClient.ts, plugins/rbac/src/utils/create-role-utils.test.ts, plugins/rbac/src/utils/create-role-utils.ts, plugins/rbac/src/utils/rbac-utils.test.ts, plugins/rbac/src/utils/rbac-utils.ts
What does this pull request fix:
https://issues.redhat.com/browse/RHIDP-2374
=> fix(rbac): correct plugin ID matching to permission policy

plugins/rbac/src/components/CreateRole/EditRolePage.tsx, plugins/rbac/src/hooks/useSelectedMembers.ts
[RHIDP-3012](https://issues.redhat.com/browse/RHIDP-3012): [RBAC] Edit role page shows error page when loading data
=> fix(rbac): edit role page loads error page

plugins/orchestrator-backend/dist-dynamic/package.json, plugins/orchestrator-backend/dist-dynamic/yarn.lock, plugins/orchestrator-backend/package.json, plugins/rbac-backend/package.json, plugins/rbac/package.json, yarn.lock
Update rbac common to fix RBAC plugin compilation .
=> fix(rbac): update rbac common to fix compilation

plugins/rbac/src/__fixtures__/mockFormValues.tsx, plugins/rbac/src/components/CreateRole/EditRolePage.test.tsx, plugins/rbac/src/components/CreateRole/EditRolePage.tsx, plugins/rbac/src/components/CreateRole/ReviewStep.tsx, plugins/rbac/src/components/RoleOverview/PermissionsCard.test.tsx, plugins/rbac/src/components/RoleOverview/PermissionsCard.tsx, plugins/rbac/src/components/RoleOverview/PermissionsListColumns.tsx, plugins/rbac/src/hooks/usePermissionPolicies.test.ts, plugins/rbac/src/hooks/usePermissionPolicies.ts, plugins/rbac/src/types.ts, plugins/rbac/src/utils/rbac-utils.test.ts, plugins/rbac/src/utils/rbac-utils.ts, plugins/rbac/tests/rbac.spec.ts
Story: https://issues.redhat.com/browse/RHIDP-2770
Screenshot:
=> feat(rbac): show rules count in overview page

yarn.lock
Fixes https://issues.redhat.com/browse/RHIDP-3080
=> chore(deps): fix CVE-2024-39008

plugins/kiali/src/components/About/AboutUIModal.tsx, plugins/kiali/src/components/Banners/TechPreviewWarning.tsx, plugins/kiali/src/components/BreadcrumbView/BreadcrumbView.tsx, plugins/kiali/src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx, plugins/kiali/src/components/Router.tsx, plugins/kiali/src/config/Icons.ts, plugins/kiali/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, plugins/kiali/src/pages/Kiali/Header/KialiHeader.tsx
Some styles updated: 
- Cluster chip
- Tech preview banner style
- About close button fix
- Use Material UI icons
- Ace editor styles
- Breadcrumb styles
=> feat(kiali): improve styles

plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
cherry picked https://github.com/janus-idp/backstage-plugins/pull/1880
=> fix(orchestrator): returned scrolling bars to instance page cards

plugins/orchestrator-backend/dist-dynamic/package.json, plugins/orchestrator-backend/dist-dynamic/yarn.lock, plugins/orchestrator-backend/package.json
Issue was conflicting dependencies that caused dist-dynamic to contain @backstage dependencies that should be taken from host application.
Moving @janus-idp dependencies to peerDependencies resolved the issue.
=> fix(orchestrator): resolve broken dynamic plugin publish

plugins/argocd/README.md
nit: Argocd is spelled Argo CD
=> docs: fix argocd naming

plugins/rbac/README.md
fix intention and closing JSX/TSX tag
=> docs: fix rbac integration code samples

yarn.lock
Signed-off-by: Roy Golan <rgolan@redhat.com>
=> chore(dependencies): clean install and commit the yarn.lock

.github/workflows/pr-playwright.yaml
chore(tests) let playright kill a process that doesn't exist anymore; if it's already been killed, don't fail when trying to re-kill it
N/A
N/A
=> chore(tests): let playright kill a process if it's already dead

package.json, plugins/acr/package.json
chore(release): explicitly ignore private packages to avoid MSR failures
N/A
Ongoing problems using MSR:
```
npm ERR! code EPRIVATE
npm ERR! This package has been marked as private
npm ERR! Remove the 'private' field from the package.json to publish it.
```
-- https://github.com/janus-idp/backstage-plugins/actions/runs/10066839123/job/27829588157
N/A
=> chore(release): explicitly ignore private packages to avoid MSR failures

yarn.lock
=> chore(deps): fix dirty yarn.lock file

package.json
chore(releases): don't exclude packages, only private plugins
N/A
N/A
=> chore(releases): don't exclude packages, only private plugins

package.json, plugins/bulk-import-backend/package.json, plugins/bulk-import-common/package.json, plugins/bulk-import/package.json
chore(release): remove workspace restrictions from root package.json after releasing the three bulk-import plugins manually
N/A
N/A
=> chore(release): remove workspace restrictions from root package.json after releasing the three bulk-import plugins manually

plugins/catalog-backend-module-scaffolder-relation-processor/dist-dynamic/package.json, plugins/catalog-backend-module-scaffolder-relation-processor/package.json
chore(deps): because we're updating this plugin even though it's moved to community-plugins, we might as well release it with the updates to BS 1.29, even though it's deprecated
N/A
N/A
=> chore(deps): make plugin non-private

plugins/acr/package.json, plugins/bulk-import/package.json
chore(deps): revert to @janus-idp/shared-react 2.8 since 2.9 isn't released yet
N/A
N/A
=> chore(deps): revert to @janus-idp/shared-react 2.8 since 2.9 isn't released yet

.github/actions/build/action.yaml, .github/actions/test/action.yaml, .github/actions/yarn-lock/action.yaml, .github/workflows/pr.yaml, .github/workflows/push.yaml, .github/workflows/yarn-lock.yaml, yarn.lock
chore(deps): instead of failing for a dirty workspace when pushing an MSR release, generate a PR to regen yarn.lock
also adds a manual workflow for yarn lock regen PR creation
NOTE: PR checks will continue to fail if the workspace is dirty
N/A
N/A
=> chore(deps): generate PRs to regen yarn.lock when dirty workspace found during a MSR push

.github/actions/yarn-lock/action.yaml
Signed-off-by: Nick...
chore: fix pr creation
N/A
N/A
=> chore: fix pr creation

plugins/rbac-backend/src/service/enforcer-delegate.ts
Fix uncommited knex transaction in the addGroupingPolicies
=> fix(rbac): fix uncommited knex transaction in the addGroupingPolicies

plugins/rbac/src/components/RolesList/RolesList.test.tsx, plugins/rbac/src/components/RolesList/RolesListColumns.tsx, plugins/rbac/src/hooks/useRoles.ts, plugins/rbac/src/types.ts, plugins/rbac/src/utils/rbac-utils.ts, plugins/rbac/tests/rbac.spec.ts
Story: https://issues.redhat.com/browse/RHIDP-2769
=> feat(rbac): show list of accessible plugins in roles list page

plugins/lightspeed/package.json
Remove the private field now that the lightspeed plugin has been released
=> chore(release): remove private from manually released lightspeed plugin

plugins/argocd/package.json
Fix incorrect argocd-common plugin reference.
cc: @invincibleJai
=> fix(argocd): fix argocd-common plugin version

plugins/keycloak-backend/package.json
chore(metadata): add works-with metadata annotations re: rhsso and keycloak, using npm version notation
N/A
https://issues.redhat.com/browse/RHIDP-2680
N/A
=> chore(metadata): add works-with metadata annotations re: rhsso and keycloak, using npm version notation (RHIDP-2680)

plugins/argocd-common/package.json
Manually release the argocd-common `1.0.0` plugin
=> chore(release): manually release argocd-common 1.0.0

plugins/topology/package.json, yarn.lock
Failing `yarn tsc` is causing our CI to fail.
=> fix(topology): bump shared-react dependency

plugins/orchestrator/src/components/WorkflowInstancePage.tsx
simplified logic of rerun, abort and retrigger
[FLPATH-1489](https://issues.redhat.com/browse/FLPATH-1489)
=> fix(orchestrator): remove retrigger button in active state

plugins/orchestrator/package.json, plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.tsx, plugins/orchestrator/src/components/ExecuteWorkflowPage/JsonTextAreaForm.tsx, plugins/orchestrator/src/components/ExecuteWorkflowPage/StepperForm.tsx, plugins/orchestrator/src/components/InfoDialog.stories.tsx, plugins/orchestrator/src/components/InfoDialog.tsx, plugins/orchestrator/src/components/OrchestratorIcon.tsx, plugins/orchestrator/src/components/Paragraph.tsx, plugins/orchestrator/src/components/Selector.tsx, plugins/orchestrator/src/components/SubmitButton.tsx, plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionDetailsCard.tsx, plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionViewerPage.tsx, plugins/orchestrator/src/components/WorkflowDescriptionModal.tsx, plugins/orchestrator/src/components/WorkflowDialog.tsx, plugins/orchestrator/src/components/WorkflowInstancePage.tsx, plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx, plugins/orchestrator/src/components/WorkflowInstanceStatusIndicator.tsx, plugins/orchestrator/src/components/WorkflowProgressNode.tsx, plugins/orchestrator/src/components/WorkflowRunDetails.tsx, plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx, plugins/orchestrator/src/components/WorkflowVariablesViewer.tsx, plugins/orchestrator/src/components/WorkflowsTabContent.tsx, plugins/orchestrator/src/components/WorkflowsTable.tsx, plugins/orchestrator/src/components/ui/OverrideBackstageTable.tsx, plugins/orchestrator/src/hooks/useWorkflowInstanceStatusColors.ts, yarn.lock
cherry pick https://github.com/janus-idp/backstage-plugins/pull/2035
=> fix(orchestrator): downgrade back to material 4 to solve dark theme incompatibliity

OWNERS
/cc @invincibleJai 
/assign @jerolimov
=> chore: add jerolimov/myself as owner

plugins/lightspeed/package.json, plugins/lightspeed/src/components/LightspeedPage.tsx, plugins/lightspeed/src/components/Message.tsx, yarn.lock
Story: https://issues.redhat.com/browse/RHIDP-3543
=> feat(lightspeed): improved chat experience with added context from previous responses

plugins/bulk-import-backend/api-docs/Models/Import_github_pullRequest.md, plugins/bulk-import-backend/src/openapi.d.ts, plugins/bulk-import-backend/src/openapidocument.ts, plugins/bulk-import-backend/src/schema/openapi.yaml, plugins/bulk-import-backend/src/service/githubApiService.ts, plugins/bulk-import-backend/src/service/handlers/bulkImports.ts, plugins/bulk-import-backend/src/service/router.ts
This PR adds more details about the PR in the `GET /import/by-repo` response. The following fields are being added o the response:
- `github.pullRequest.title`
- `github.pullRequest.body`
- `github.pullRequest.catalogInfoContent`
This is needed in the UI to be able to edit the catalog-info file for existing imports with open PRs (a.k.a. waiting for approval).
Fixes https://issues.redhat.com/browse/RHIDP-3669
Example request/response:
```
$ http -A bearer -a "${ADMIN_CURL_TOKEN}" GET http://localhost:7007/api/bulk-import/import/by-repo repo==https://github.com/lemra-org-ent-2/animated-happiness defaultBranch==main
{ …
```
=> feat(bulk-import): include more details about PR (title, description, catalog-info content) when fetching import status by repo

plugins/orchestrator/src/components/WorkflowsTable.tsx
[FLPATH-1573](https://issues.redhat.com//browse/FLPATH-1573)
=> fix: add more space for workflow description

plugins/audit-log-node/README.md
fixes https://issues.redhat.com/browse/RHIDP-3717
=> chore(doc): add audit log event naming convention

plugins/rbac/src/components/CreateRole/RoleForm.tsx
Fixes: https://issues.redhat.com/browse/RHIDP-3665
https://github.com/user-attachments/assets/8a9dbeaa-2e3e-41e5-845f-e66009581ce2
=> fix(rbac): role name update should redirect to correct overview page

plugins/orchestrator/src/components/WorkflowInstancePage.tsx
[FLPATH-1600](https://issues.redhat.com//browse/FLPATH-1600)
=> fix(orchestrator): make "Retrigger" clear to the user

plugins/rbac/README.md, plugins/rbac/src/components/RolesList/RolesListToolbar.tsx
Fixes: https://issues.redhat.com/browse/RHIDP-3492
=> fix(rbac): add more details to unable to create role alert

plugins/bulk-import-backend/dist-dynamic/package.json, plugins/bulk-import-backend/package.json
Another attempt at downgrading plugins by MSR, which will break the rest of our release process.
[Attempted upgrade](https://github.com/janus-idp/backstage-plugins/commit/1b83ea131227017e05d204d79f8840e14078f48c)
=> chore(release): fix more msr problems

plugins/rbac/dev/index.tsx, plugins/rbac/src/api/LicensedUsersClient.ts, plugins/rbac/src/components/DownloadUserStatistics.tsx, plugins/rbac/src/components/RbacPage.test.tsx, plugins/rbac/src/components/RolesList/RolesList.test.tsx, plugins/rbac/src/components/RolesList/RolesList.tsx, plugins/rbac/src/hooks/useCheckIfLicensePluginEnabled.ts, plugins/rbac/src/plugin.ts
Add licensed users download link to RBAC plugin
- Fixes https://issues.redhat.com/browse/RHIDP-3603
=> feat(licensed-users): add licensed users download link

plugins/feedback-backend/README.md, plugins/feedback-backend/package.json, plugins/feedback/README.md, plugins/feedback/package.json
[RHIDP-3549](https://issues.redhat.com//browse/RHIDP-3549): Add deprecation note to feedback and feedback-backend plugins
=> chore: add deprecation note to feedback and feedback-backend plugins

plugins/bulk-import/app-config.janus-idp.yaml, plugins/bulk-import/package.json, plugins/bulk-import/src/components/BulkImportSidebarItem.tsx, plugins/bulk-import/src/index.ts
**Resolves:**
https://issues.redhat.com/browse/RHIDP-2738
=> fix(bulk-import): update bulk import exports

plugins/orchestrator-form-react/src/components/OrchestratorForm.tsx
[FLPATH-1507](https://issues.redhat.com//browse/FLPATH-1507)
See screenshots bellow - the background color is unified, the view is more condense (no padding), the top-level border line is removed.
=> fix(orchestrator): improve styles of generated field array in the dark theme

plugins/orchestrator/src/components/WorkflowInstancePage.tsx
[FLPATH-1600](https://issues.redhat.com//browse/FLPATH-1600)
backport of #2098
=> fix(orchestrator): make "Retrigger" to the user

plugins/bulk-import-backend/dist-dynamic/package.json, plugins/bulk-import-backend/package.json, plugins/bulk-import-common/package.json
Fixes https://issues.redhat.com/browse/RHIDP-3818
/cc @nickboldt
=> fix(bulk-import): fix inconsistency with the support levels declared by the plugins

plugins/orchestrator-backend/src/OrchestratorPlugin.ts, plugins/orchestrator-backend/src/service/router.ts, plugins/orchestrator-common/package.json, plugins/orchestrator-common/scripts/openapi.sh, plugins/orchestrator-common/src/generated/docs/html/index.html
[FLPATH-1407](https://issues.redhat.com//browse/FLPATH-1407)
https://issues.redhat.com/browse/FLPATH-1407
make open api documentation of backend available via backend plugin
=> feat(orchestrator): add open api documentation

plugins/audit-log-node/package.json
Another attempt at downgrading by MSR. Reverts the change of `audit log node`
=> chore(release): revert downgrade of audit log

plugins/bulk-import-common/package.json
This reverts commit 9e239c5ae768ed6cbe5aebf483f318c42b984c91.
Yet another MSR issue:
https://github.com/janus-idp/backstage-plugins/actions/runs/10819711893/job/30018196326
/cc @PatAKnight @AndrienkoAleksandr
=> chore(release): revert downgrade of bulk-import-common

plugins/bulk-import-backend/CHANGELOG.md, plugins/bulk-import-backend/dist-dynamic/package.json, plugins/bulk-import-backend/package.json
MSR attempted another downgrade of the bulk import backend plugin. This PR aims to fix it.
[Downgrade attempt](https://github.com/janus-idp/backstage-plugins/commit/03a5839370fef285f9657a189f66c36c94d62d86)
=> chore(release): revert downgrade of bulk import backend

plugins/orchestrator-form-api/package.json
This reverts commit 0c149bbcf7881efa83ef55ae42ce9276ce96cab9.
MSR issue:
https://github.com/janus-idp/backstage-plugins/actions/runs/10838902789/job/30078138859
/cc @PatAKnight @AndrienkoAleksandr @dzemanov
=> chore(release): revert downgrade of 'orchestrator-form-api' package

plugins/bulk-import/package.json, plugins/bulk-import/src/components/AddRepositories/AddRepositoriesFormFooter.tsx, plugins/bulk-import/src/components/PreviewFile/PreviewFileSidebarDrawerContent.tsx, yarn.lock
This is for [RHIDP-3799](https://issues.redhat.com/browse/RHIDP-3799). [PR in redhat-developer-hub-theme](https://github.com/redhat-developer/red-hat-developer-hub-theme/pull/37) is also requested for the fix to close the story.
https://github.com/user-attachments/assets/a43dd981-75d7-4f81-9228-02ef6f003f7c
Tested on showcase
https://github.com/user-attachments/assets/8ae7c7eb-e496-47fd-83ee-4971b73ae58c
=> fix(ui): fixed bulk import footer background color in dark theme

plugins/topology/README.md
Bug : https://issues.redhat.com/projects/RHIDP/issues/RHIDP-4020
=> fix(topology): adding vmi in readme

plugins/bulk-import/dev/index.tsx, plugins/bulk-import/src/api/BulkImportBackendClient.test.ts, plugins/bulk-import/src/api/BulkImportBackendClient.ts, plugins/bulk-import/src/components/AddRepositories/AddRepositoriesDrawer.tsx, plugins/bulk-import/src/components/AddRepositories/AddRepositoriesTable.test.tsx, plugins/bulk-import/src/components/AddRepositories/AddRepositoriesTableToolbar.tsx, plugins/bulk-import/src/components/AddRepositories/RepositoriesTable.tsx, plugins/bulk-import/src/components/AddRepositories/RepositoryTableRow.tsx, plugins/bulk-import/src/components/BulkImportPage.test.tsx, plugins/bulk-import/src/components/PreviewFile/PreviewFileSidebar.tsx, plugins/bulk-import/src/components/Repositories/EditCatalogInfo.tsx, plugins/bulk-import/src/components/Repositories/RepositoriesList.test.tsx, plugins/bulk-import/src/components/Repositories/RepositoriesList.tsx, plugins/bulk-import/src/components/Repositories/RepositoriesListToolbar.tsx, plugins/bulk-import/src/hooks/useAddedRepositories.test.ts, plugins/bulk-import/src/hooks/useAddedRepositories.ts, plugins/bulk-import/src/hooks/useRepositories.test.ts, plugins/bulk-import/src/hooks/useRepositories.ts, plugins/bulk-import/src/mocks/mockData.ts, plugins/bulk-import/src/types/types.ts, plugins/bulk-import/src/utils/repository-utils.test.tsx, plugins/bulk-import/src/utils/repository-utils.tsx, plugins/bulk-import/tests/bulkImport.spec.ts
**Resolves:**
https://issues.redhat.com/browse/RHIDP-3859
**GIF:**
https://github.com/user-attachments/assets/5e151608-c37f-4ef6-b5a9-50ee56b8108e
=> fix(bulk-import): pass search string as query params in the bulk imort apis

plugins/catalog-backend-module-scaffolder-relation-processor/package.json
chore(deps): make plugins/catalog-backend-module-scaffolder-relation-processor/package.json private:true to avoid version bumps and releases
N/A
https://issues.redhat.com/browse/RHIDP-4031
N/A
=> chore(deps): make plugins/catalog-backend-module-scaffolder-relation-processor/package.json private:true to avoid version bumps and releases

plugins/audit-log-node/package.json
This reverts commit e87ab4612a4ba9db90b8a2936253a51a5a470ef0.
Looks like another MSR issue - logs in [1].
[1] https://github.com/janus-idp/backstage-plugins/actions/runs/10890013976/job/30217827773
=> chore(release): revert unexpected downgrade of `backstage-plugin-audit-log-node`

OWNERS
Add @JessicaJHee and @04kash as approvers and remove @Zaperex
=> chore(owners): update approvers

plugins/keycloak-backend/package.json
Update to match version in main which corresponds to 1.3
=> chore: [1.3.x] update keycloak version

plugins/orchestrator-backend/src/service/router.ts
[FLPATH-1703](https://issues.redhat.com//browse/FLPATH-1703)
https://issues.redhat.com/browse/FLPATH-1703
=> fix(orchestrator): v2 inputSchema API gets stuck for specific workflow

plugins/3scale-backend/dist-dynamic/package.json, plugins/lightspeed-backend/dist-dynamic/package.json, plugins/rbac-backend-module-test/dist-dynamic/package.json, plugins/rbac-backend-module-test/dist-dynamic/yarn.lock
Update the checked in yarn.lock to accomadate dependency updates.  This change also updates a couple other committed package.json files.
=> chore(build): regenerate plugin yarn.lock

plugins/orchestrator-common/src/constants.ts
Former image on quay is 5 months old.
=> chore: update incubator-kie-sonataflow-devmode image to latest

plugins/bulk-import-common/package.json
MSR downgrade of the bulk import common plugin
Causing failing release 
Blocking some plugins from releasing
Problem [commit](https://github.com/janus-idp/backstage-plugins/commit/40dd140f8bd2590c9386a624f86139bdf7fcc15c)
=> chore(release): revert msr downgrade of bulk import common

plugins/bulk-import/src/components/PreviewFile/PreviewPullRequests.tsx
For [RHIDP-3430](https://issues.redhat.com/browse/RHIDP-3430)
Screenshots:
=> fix(ui): updated tabs indicator color

packages/app/package.json, plugins/acr/package.json, plugins/analytics-module-matomo/package.json, plugins/analytics-provider-segment/package.json, plugins/argocd/package.json, plugins/dynamic-plugins-info/package.json, plugins/jfrog-artifactory/package.json, plugins/kiali/package.json, plugins/matomo/package.json, plugins/nexus-repository-manager/package.json, plugins/ocm/package.json, plugins/openshift-image-registry/package.json, plugins/orchestrator/package.json, plugins/quay/package.json, plugins/rbac/package.json, plugins/tekton/package.json, plugins/topology/package.json, plugins/web-terminal/package.json, yarn.lock
Upgrade theme package version for plugins.
=> chore: update theme package version for plugins

plugins/sonarqube-actions/README.md, plugins/sonarqube-actions/dist-dynamic/package.json, plugins/sonarqube-actions/dist-dynamic/yarn.lock, plugins/sonarqube-actions/examples/templates/01-sonar-template.yaml, plugins/sonarqube-actions/package.json, plugins/sonarqube-actions/src/alpha.ts, plugins/sonarqube-actions/src/dynamic/index.ts, plugins/sonarqube-actions/src/index.ts
- Migrate to the new Backend System and remove deprecations
- Fix examples template
Fixes: https://issues.redhat.com/browse/RHIDP-4060
1. Install SonarQube with docker:
```bash
docker run -d --name sonarqube -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true -p 9000:9000 sonarqube:latest
```
2. Go to login page: http://localhost:9000, login with user `admin` and password `admin`. SonarQube will ask you to provide new password.
3. Generate user token: 
Click big letter `A` in the top right corner. Select `Account` in the dropdown. Select `Security` tab. Fill inputs: token name, select token type `User Token`. Click `Generate` button. Copy token.
4. Change root package.json command:
```
...
"start:backstage": "turbo run start --filter=...app --filter=...backend",
...
```
to:
```
... …
```
=> feat(sonarqube-actions)!: migrate to the new Backend System and remove deprecations

plugins/quay-actions/README.md, plugins/quay-actions/dist-dynamic/package.json, plugins/quay-actions/dist-dynamic/yarn.lock, plugins/quay-actions/package.json, plugins/quay-actions/src/alpha.ts, plugins/quay-actions/src/dynamic/index.ts, plugins/quay-actions/src/index.ts
- removes legacy backend system
- removes deprecations
[RHIDP-4057](https://issues.redhat.com/browse/RHIDP-4057)
=> feat(quay-actions)!: migrate to the new backend and remove deprecations #1254

package.json, yarn.lock
https://issues.redhat.com/browse/RHIDP-3925
=> chore(deps): bump to dset@^3.1.4

plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.test.ts, plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.ts
[FLPATH-1675](https://issues.redhat.com//browse/FLPATH-1675)
https://issues.redhat.com/browse/FLPATH-1675
=> fix(orchestrator): fix ProcessInstanceDTO mapping

plugins/rbac-backend/docs/group-hierarchy.md
=> fix(rbac): update group hierarchy doc

package.json, yarn.lock
https://issues.redhat.com/browse/RHIDP-4118
https://issues.redhat.com/browse/RHIDP-4119
=> chore(deps): [release-1.3] bump @backstage/plugin-catalog-backend to 1.26.1

plugins/servicenow-actions/README.md, plugins/servicenow-actions/dist-dynamic/package.json, plugins/servicenow-actions/package.json, plugins/servicenow-actions/src/alpha.ts, plugins/servicenow-actions/src/dynamic/index.ts, plugins/servicenow-actions/src/index.ts
Migrates to the new backend system and removes some of the deprecations from the recent updates in Backstage versions.
- Fixes: [RHIDP-4059](https://issues.redhat.com/browse/RHIDP-4059)
=> feat(servicenow-actions)!: migrate to new backend system and remove deprecations

plugins/orchestrator/src/components/WorkflowDescriptionModal.tsx, plugins/orchestrator/src/components/WorkflowResult.tsx
Fixes: [FLPATH-1748](https://issues.redhat.com//browse/FLPATH-1748)
Handles the case when a workflow instance result references next nonexisting workflow ID.
=> fix(orchestrator): improve error handling for incorrect nextWorkflow IDs

plugins/audit-log-node/package.json, plugins/audit-log-node/src/DefaultAuditLogger.test.ts, plugins/audit-log-node/src/DefaultAuditLogger.ts, plugins/audit-log-node/src/types.ts, yarn.lock
Optimise for the new backend and remove deprecations
https://issues.redhat.com/browse/RHIDP-4226
=> fix(audit-log-node): optimise for the new backend and remove deprecations

.github/workflows/pr-playwright.yaml, .github/workflows/push.yaml, .github/workflows/yarn-lock.yaml, package.json
chore(msr): enable MSR on release-1.3 branch
N/A
https://issues.redhat.com/browse/RHIDP-4120
https://issues.redhat.com/browse/RHIDP-4031
N/A
=> chore(msr): enable MSR on release-1.3 branch (RHIDP-4120)

.github/workflows/pr-playwright.yaml
Signed-off-by: Nick Boldt...
chore: lint
N/A
N/A
=> chore: lint

plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
A temporary solution till we have proper Input Parameters card (tracked in [FLPATH-1736](https://issues.redhat.com//browse/FLPATH-1736))
Fixes: [FLPATH-1737](https://issues.redhat.com//browse/FLPATH-1737)
=> feat(orchestrator): add Variables card

plugins/orchestrator-backend/CHANGELOG.md, plugins/orchestrator-form-react/CHANGELOG.md, plugins/orchestrator-form-react/package.json, plugins/orchestrator/CHANGELOG.md
revert MSR downversioning; add changelog entries to see if that will trick MSR into doing the right thing
N/A
N/A
=> fix(orchestrator): revert MSR downversioning; add changelogs

packages/app/package.json, plugins/analytics-module-matomo/package.json, plugins/analytics-provider-segment/package.json, plugins/bulk-import/package.json, plugins/jfrog-artifactory/package.json, plugins/kiali/package.json, plugins/matomo/package.json, plugins/nexus-repository-manager/package.json, plugins/ocm/package.json, plugins/openshift-image-registry/package.json, plugins/orchestrator/package.json, plugins/quay/package.json, plugins/rbac/package.json, plugins/tekton/package.json, plugins/topology/package.json, plugins/web-terminal/package.json, yarn.lock
Update rhdh-theme to include this PRs:
* https://github.com/redhat-developer/red-hat-developer-hub-theme/pull/43
* https://github.com/redhat-developer/red-hat-developer-hub-theme/pull/44
* https://github.com/redhat-developer/red-hat-developer-hub-theme/pull/45
* https://github.com/redhat-developer/red-hat-developer-hub-theme/pull/46
* [RHIDP-3938](https://issues.redhat.com/browse/RHIDP-3938) Custom theme can causes runtime JavaScript errors
* [RHIDP-3139](https://issues.redhat.com/browse/RHIDP-3139) Theme enhancements to the menu's selected item theme
* [RHIDP-3430](https://issues.redhat.com/browse/RHIDP-3430) Change checkbox and tab color to match PatternFly (RHDH Theme)
/cc @ciiay
=> chore(deps): update rhdh-theme to 0.4.0

yarn.lock
Signed-off-by: Nick Boldt...
yarn lock regen
N/A
N/A
=> yarn lock regen

plugins/keycloak-backend/__fixtures__/data.ts, plugins/keycloak-backend/__fixtures__/helpers.ts, plugins/keycloak-backend/src/lib/read.ts
https://issues.redhat.com/browse/RHIDP-4391
=> fix(keycloak): retrieve all group members using pagination

plugins/tekton/src/components/Tekton/TektonCIComponent.tsx, plugins/tekton/src/plugin.ts
For [RHIDP-4266](https://issues.redhat.com/browse/RHIDP-4266)
Screen recording
https://github.com/user-attachments/assets/a8b6e5ef-be14-436b-bea4-313d1b46be62
=> fix(tekton): resolved css collision issue from tekton

plugins/topology/src/components/Topology/TopologyComponent.tsx, plugins/topology/src/plugin.ts
For [RHIDP-2388](https://issues.redhat.com/browse/RHIDP-2388)
Tested with [RHIDP-4237](https://issues.redhat.com/browse/RHIDP-4237) test data and verified that CSS collision doesn't happen with this solution.
Screen recording
https://github.com/user-attachments/assets/4b3663e8-65fd-4a3c-ac60-fbed29af0aca
=> fix(topology): avoid css collision on plugins

plugins/orchestrator-backend/dist-dynamic/package.json, plugins/orchestrator-backend/dist-dynamic/yarn.lock, plugins/orchestrator-backend/package.json, plugins/orchestrator-backend/src/OrchestratorPlugin.ts, plugins/orchestrator-backend/src/service/router.ts
remove docs feature that breaks dynamic plugin build, and revert PR that attempted to fix that issue but broke multi-semantic-release
=> fix(orchestrator): remove docs feature

plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
variables card scrollbar was removed following results feature
=> fix(orchestrator): add scrollbar to variables card

plugins/feedback-backend/dist-dynamic/yarn.lock, plugins/kiali-backend/dist-dynamic/yarn.lock, plugins/matomo-backend/dist-dynamic/yarn.lock, plugins/ocm-backend/dist-dynamic/yarn.lock, plugins/orchestrator-backend/dist-dynamic/yarn.lock, yarn.lock
Fixes:
https://issues.redhat.com/browse/RHIDP-3946
https://issues.redhat.com/browse/RHIDP-3916
https://issues.redhat.com/browse/RHIDP-3932
https://issues.redhat.com/browse/RHIDP-3897
CVE-2024-45296
CVE-2024-43799
CVE-2024-45590
CVE-2024-47764
CVE-2024-43800
=> chore(deps): update express to fix multiple CVEs

plugins/aap-backend/dist-dynamic/package.json, plugins/bulk-import-backend/dist-dynamic/package.json, plugins/bulk-import-backend/dist-dynamic/yarn.lock, plugins/keycloak-backend/dist-dynamic/package.json, plugins/kiali-backend/dist-dynamic/package.json, plugins/kiali-backend/dist-dynamic/yarn.lock, plugins/kubernetes-actions/dist-dynamic/package.json, plugins/kubernetes-actions/dist-dynamic/yarn.lock, plugins/lightspeed-backend/dist-dynamic/package.json, plugins/lightspeed-backend/dist-dynamic/yarn.lock, plugins/matomo-backend/dist-dynamic/package.json, plugins/ocm-backend/dist-dynamic/package.json, plugins/ocm-backend/dist-dynamic/yarn.lock, plugins/orchestrator-backend/dist-dynamic/package.json, plugins/orchestrator-backend/dist-dynamic/yarn.lock, plugins/quay-actions/dist-dynamic/package.json, plugins/rbac-backend-module-test/dist-dynamic/package.json, plugins/rbac-backend-module-test/dist-dynamic/yarn.lock, plugins/regex-actions/dist-dynamic/package.json, plugins/scaffolder-annotator-action/dist-dynamic/package.json, plugins/servicenow-actions/dist-dynamic/package.json, plugins/servicenow-actions/dist-dynamic/yarn.lock, plugins/sonarqube-actions/dist-dynamic/package.json
Rerun `export-dynamic` to fix the `release` github action.
=> fix(release): rerun export-dynamic

plugins/feedback-backend/CHANGELOG.md, plugins/feedback-backend/dist-dynamic/package.json, plugins/feedback-backend/package.json, plugins/kiali-backend/CHANGELOG.md, plugins/kiali-backend/dist-dynamic/package.json, plugins/kiali-backend/package.json, plugins/kubernetes-actions/CHANGELOG.md, plugins/kubernetes-actions/dist-dynamic/package.json, plugins/kubernetes-actions/package.json, plugins/matomo-backend/CHANGELOG.md, plugins/matomo-backend/dist-dynamic/package.json, plugins/matomo-backend/package.json, plugins/ocm-backend/CHANGELOG.md, plugins/ocm-backend/dist-dynamic/package.json, plugins/ocm-backend/package.json, plugins/orchestrator-backend/CHANGELOG.md, plugins/orchestrator-backend/dist-dynamic/package.json, plugins/orchestrator-backend/package.json
bump up plugin versions and changelogs
=> chore(deps): update versions and changelogs

plugins/keycloak-backend/dist-dynamic/package.json
I tried to update backstage-plugins with newer keycloak-backend plugin, but failed with error:
https://github.com/janus-idp/backstage-showcase/pull/1770#issuecomment-2412531097
=> fix(keycloak): include 'embedded' folder to keycloak-backend release files

OWNERS
/cc @invincibleJai @debsmita1 @divyanshiGupta @ciiay @its-mitesh-kumar 
/assign @invincibleJai
=> chore: update my github username

.github/workflows/pr.yaml
Signed-off-by: Paul Schultz <pschultz@pobox.com>
=> chore(gh): fix fetch depth on ui-tests

.changeset/two-waves-film.md, plugins/orchestrator-common/package.json, yarn.lock
Signed-off-by: Paul Schultz <pschultz@pobox.com>
=> fix(orchestrator): fix typo in package resolution

.changeset/odd-dryers-draw.md, plugins/orchestrator/src/components/WorkflowResult.tsx
Part of [FLPATH-1797](https://issues.redhat.com//browse/FLPATH-1797)
=> fix(orchestrator): make WorkflowResult rebust on malformed input

CONTRIBUTING.md
CONTRIBUTING.md: add notes about maintenance branches and spiff up links #2492
=> chore: doc - CONTRIBUTING.md: add notes about maintenance branches and spiff up links

.changeset/lemon-points-applaud.md, plugins/orchestrator-form-react/src/components/OrchestratorFormStepper.tsx
Fixes: [FLPATH-1825](https://issues.redhat.com//browse/FLPATH-1825)
=> fix: use background button color from theme

.changeset/gentle-fishes-swim.md, plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx, plugins/orchestrator/src/components/WorkflowResult.tsx
Fixes: [FLPATH-1833](https://issues.redhat.com//browse/FLPATH-1833)
=> fix: make long workflow result message fully visible

plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx, plugins/orchestrator/src/components/WorkflowResult.tsx
=> fix: make long workflow result message fully visible (backport 1.3)

plugins/bulk-import/README.md
=> fix(bulk-import): minor typo fix

plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx, plugins/orchestrator/src/components/WorkflowInstanceStatusIndicator.tsx, plugins/orchestrator/src/components/WorkflowRunDetails.tsx
=> fix(orchestrator): remove completedWith status (1.3)

package.json
=> chore: tagRelease.sh: bump to 3.3.2 in release-1.3 branch

.changeset/sweet-pens-drive.md, plugins/orchestrator-common/package.json
add orchestrator common to changeset to resolve release action failing for PR https://github.com/janus-idp/backstage-plugins/pull/2514
=> chore(orchestrator): fix changeset for PR 2514

.changeset/pretty-avocados-talk.md, plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx
Fixes: [FLPATH-1851](https://issues.redhat.com//browse/FLPATH-1851)
=> fix(orchestrator): filter workflow runs by status

yarn.lock
Signed-off-by: Nick...
chore: yarn lock regen
N/A
N/A
=> chore: yarn lock regen

.changeset/hot-otters-shave.md, plugins/argocd/package.json, plugins/kubernetes-actions/dist-dynamic/package.json, plugins/kubernetes-actions/dist-dynamic/yarn.lock, plugins/kubernetes-actions/package.json, plugins/ocm-backend/dist-dynamic/package.json, plugins/ocm-backend/dist-dynamic/yarn.lock, plugins/ocm-backend/package.json, plugins/ocm-backend/src/constants.ts, plugins/ocm-backend/src/providers/ManagedClusterProvider.ts, plugins/shared-react/package.json, plugins/tekton/package.json, plugins/topology/package.json, yarn.lock
backport of https://github.com/janus-idp/backstage-plugins/pull/2356 to fix CVE-2024-21534
=> chore: 1.2.x fix CVE-2024-21534

.changeset/witty-penguins-live.md, plugins/kubernetes-actions/dist-dynamic/yarn.lock, plugins/ocm-backend/dist-dynamic/yarn.lock, yarn.lock
Fix : https://issues.redhat.com/browse/RHIDP-4440
*  jsonpath-plus  v10.2.0 bump
=> chore(deps): 1.3 bump jsonpath-plus - CVE-2024-21534

.changeset/old-trees-tease.md
This updates the changeset file from #2547 to have the correct text.
=> chore(cli): fix changeset text

.changeset/spicy-mayflies-arrive.md, plugins/audit-log-node/package.json, yarn.lock
Replaces [renovate PR](https://github.com/janus-idp/backstage-plugins/pull/2595)
=> chore(deps): update express in audit-log-node

package.json
=> chore: tagRelease.sh: bump to 3.4.1 in release-1.4 branch

package.json
=> chore: tagRelease.sh: bump to 3.3.4 in release-1.3 branch

.changeset/silent-hounds-live.md, plugins/shared-react/package.json, yarn.lock
Update @kubernetes/client-node for shared/react
https://issues.redhat.com/browse/RHIDP-4744
=> fix(shared-react): update @kubernetes/client-node for shared/react
