.github/actions/build/action.yaml

`tsc` step was missing from the build step. See logs at:
https://github.com/janus-idp/backstage-plugins/actions/runs/3623692907/jobs/6109842475

chore(ci): Add tsc before build step

---

plugins/keycloak-backend/src/lib/constants.ts

I missed that when reviewing #1 .
I think you've meant to use `keycloak.org` everywhere when changing it from `backstage.io`

fix: typo in keycloak annotations

---

.github/workflows/push.yaml

As per https://github.com/dhoulb/multi-semantic-release#npm-v85-npm-err-notarget-no-matching-version-found-for and https://github.com/dhoulb/multi-semantic-release/issues/129
I think this might be it. This is my last attempt to fix the `semantic-release` if this doesn't work I'll experiment with some other releasers like [intuit/auto](https://intuit.github.io/auto/)...

chore(ci): Fix release pipeline [attempt 2]

---

plugins/keycloak-backend/package.json
yarn.lock

Keycloak client decided to drop support for CommonJS by v19. Backstage doesn't properly support ESM yet, therefore ESM only dependencies don't build properly via `backstage-cli package build`. This is a temporary workaround until Backstage works out proper ESM support. Locking to `<19` version of Keycloak client. 
Related to: #47

fix(keycloak): Downgrade to keycloak client v18

---

.github/ISSUE_TEMPLATE/epic.md

[Test check](https://github.com/janus-idp/backstage-plugins/actions/runs/3839061037/jobs/6536319318) fails since there is an extra space in the `epic.md` issue template. This PR should fix it.

fix: Formating in issue template

---

plugins/ocm-backend/README.md
plugins/ocm-common/README.md
plugins/ocm/README.md

Full documentation (without screenshots for now, since I expect the UI to change substantially soon).
Adds an installation and configuration guide for OCM plugins.

docs(ocm): Documentation for OCM plugins

---

plugins/ocm-backend/package.json
plugins/ocm-backend/src/helpers/kubernetes.test.ts
plugins/ocm-backend/src/helpers/kubernetes.ts
plugins/ocm-backend/src/helpers/parser.test.ts
plugins/ocm-backend/src/helpers/parser.ts
plugins/ocm-backend/src/service/router.ts
plugins/ocm-common/src/index.ts
plugins/ocm/README.md

Serve as the backend for https://github.com/operate-first/service-catalog/issues/179
Add additional API call to gather information about cluster updates and provide it in the `/status` API endpoint. Also  create tests for newly created functions.
I couldn't find an endpoint that only provides a single cluster, so I have to use the endpoint (`internal.open-cluster-management.io/v1beta1/managedclusterinfos`) even in the `/status/:clusterName` API endpoint.
Example of the new API response on `/status/smaug` (see the `update` section at the end):
```json
{
"name": "smaug",
"status": {
"available": true,
"reason": "Managed cluster is available"
},
"consoleUrl": "https://console-openshift-console.apps.smaug.na.operate-first.cloud",
"kubernetesVersion": "v1.22.3+fdba464",
"oauthUrl": …
```

feat(ocm): Add update information to the `/status` API endpoint

---

plugins/ocm-backend/README.md
plugins/ocm-backend/schema.d.ts
plugins/ocm-backend/src/helpers/config.test.ts
plugins/ocm-backend/src/helpers/config.ts
plugins/ocm-backend/src/helpers/kubernetes.test.ts
plugins/ocm-backend/src/helpers/kubernetes.ts
plugins/ocm/README.md

Resolves #48 
Change the `ocm-backend` config schema to allow for an explicit configuration of the ocm plugin without a requirement for the Kubernetes plugin configuration.
Add `serviceAccountToken` field to the hub configuration scheme since we don't have any other way to access the hub. We can then remove this in the future when we have proper RBAC.
Update/create tests for additional functions that are created in order to parse the configuration file.
Options like `skipMetricsLookup` and `caFile` are omitted since we don't even support these options in the code.
Update: Update documentation for standalone OCM configuration

feat(ocm): Add an option to decouple ocm config from k8s plugin

---

plugins/ocm/src/components/ClusterInfoCard/ClusterInfoCard.tsx
plugins/ocm/src/components/TableCardFromData/TableCardFromData.tsx

Resolves https://github.com/operate-first/service-catalog/issues/179
Add an indicator for displaying whether an upgrade is available. Additionally add a mouse over tooltip showing which version is available linking to the Red Hat Product Erreta.
Since we want to make this look like the ACM indicator (see the comparison bellow) an external icon would have to be used (ACM uses patternfly for icons). This would require us to import an external `svg` which I don't think is very clean.
The closest match I found in the material ui icons is this.

feat(ocm): Add a frontend indicator for cluster upgrades

---

plugins/ocm-backend/src/service/router.test.ts

Part of https://github.com/operate-first/service-catalog/issues/176
Add tests for the `router.ts` file which contains endpoint definition for the `ocm-backend` plugin.
Kubernetes API is mocked by [nock](https://www.npmjs.com/package/nock).

test(ocm): Add router tests

---

plugins/ocm-backend/src/providers/ManagedClusterProvider.ts

Adds annotation `kubernetes.io/api-server` to a Cluster resource
Related to: https://github.com/operate-first/service-catalog/pull/210
Part of: https://github.com/janus-idp/backstage-plugins/issues/81

feat: Add API server annotation

---

plugins/quay/src/components/QuayRepository/QuayRepository.tsx
plugins/quay/src/components/utils.tsx

#100
Format date, size and Manifest information to be same as on the quay UI

fix(quay): Format date, size and Manifest information to be same as on the quay UI

---

plugins/topology/src/components/Graph/BaseNode.tsx

Fixes: https://github.com/janus-idp/backstage-plugins/issues/156
Pod label in case of rolling/recreate overlaps with pod ring
**Before:**
**After:**

fix(topology): fixes pods label overlap with rolling recreate

---

plugins/3scale-backend/package.json
plugins/keycloak-backend/package.json
plugins/ocm-backend/package.json
plugins/ocm-common/package.json
plugins/ocm/package.json
plugins/quay/package.json
plugins/topology/package.json

fix(metadata): adding default metadata to current plugins
missing metadata we need (#155a): -repository : github:janus-idp/backstage-plugins, -keywords : backstage, plugin,-homepage : janus-idp.io, -bugs : janus-idp/backstage-plugins/issues
PR closes https://github.com/janus-idp/backstage-plugins/issues/155

fixes 155a adding default metadata

---

plugins/ocm/src/components/ClusterStatusPage/ClusterStatusPage.tsx

Part of https://github.com/janus-idp/backstage-showcase/issues/63
Add a `header` instead of a `typography` field to the `ocm` cluster status page.
Result:

feat(ocm): Add header to the ocm cluster status page

---

packages/app/package.json
plugins/ocm/package.json
plugins/quay/package.json

Related to: https://github.com/janus-idp/backstage-plugins/pull/138 https://github.com/janus-idp/backstage-plugins/issues/41
Unifies the `@testing-library/react` versions (Topology plugin is already [on this exact version](https://github.com/janus-idp/backstage-plugins/blob/6f1e02ff7c55d32bab4d99afab832dd89d9fa9cf/plugins/topology/package.json#L59)).
This is necessary until we can support React v18. The v13 of `@testing-library/react` [drops](https://github.com/testing-library/react-testing-library/releases/tag/v13.0.0) support for v17.

chore(deps): downgrade dependency @testing-library/react to v12

---

plugins/topology/package.json
plugins/topology/src/components/Graph/EdgeConnect.tsx
yarn.lock

**Fixes:** https://github.com/janus-idp/backstage-plugins/issues/187
`mobx` and `mobx-react` is a transitive dependency from @patternfly/react-topology and there could be a scenario when we update the dependency version here but pf may still needs an update and use the old one this creates the issue with multiple instances of mobx. Best would to use the one from pf an avoid this.
https://github.com/patternfly/patternfly-react/blob/main/packages/react-topology/package.json#L42-L43
https://www.npmjs.com/package/@patternfly/react-topology

fix(topology): removed mobx and mobx-react from direct dependency and use one from @patternfly/react-topology

---

plugins/ocm-backend/src/helpers/config.ts
plugins/ocm-backend/src/helpers/kubernetes.ts

This PR is related to [this slack thread](https://janus-idp.slack.com/archives/C04EDTPJRK5/p1679181248576309) and might help troubleshoot this and similar issues.
Add an `url` validator before the k8s config is created and add a fallback for the error handler if the response doesn't contain a header (which is the case in the slack thread issue).

fix(ocm-backend): Improve error reporting and check for url

---

plugins/quay/src/components/QuayRepository/QuayRepository.tsx

Sonarcloud is complaining about this as a potential security hotspot.

fix(quay): change http link to https

---

plugins/sonarqube-actions/package.json

Enable [release automation](@janus-idp/backstage-scaffolder-backend-module-sonarqube) for the `@janus-idp/backstage-scaffolder-backend-module-sonarqube` package and set the initial version to 1.0.0
Fixes #219

fix(sonarqube): Enable release automation

---

plugins/ocm-backend/src/helpers/config.test.ts
plugins/ocm-backend/src/helpers/config.ts

A previous PR added `url` validation however it doesn't work when the k8s ref config is used since it was trying to use the wrong config to get the `url`. This PR should fix this bug.
Also add tests for verify that the `url` validation works correctly now.

fix(ocm-backend): Reference the correct config during url validation and add tests

---

plugins/ocm-backend/config.d.ts
plugins/ocm-backend/src/helpers/config.test.ts
plugins/ocm-backend/src/helpers/config.ts
plugins/ocm-backend/src/providers/ManagedClusterProvider.ts
plugins/ocm-backend/src/types.ts
plugins/ocm/README.md

Fixes #140 
Add a configuration option for adding a default owner to the created entities from the cluster discovery. It works by using mimicking the backstage owner references described here: https://backstage.io/docs/features/software-catalog/references/.

feat(ocm): Add a default owner configuration field

---

plugins/topology/src/components/Topology/TopologyViewWorkloadComponent.tsx

Fixes: https://github.com/janus-idp/backstage-plugins/issues/257
During resource fetch, loaded is set to false till the time the call completes so during that time selected node was not getting set as loaded remained false. I have removed loaded from the check as it is not needed since we just want to have the data-model in place and the selected-node should be set when its available.
https://user-images.githubusercontent.com/20724543/232550733-accff3f4-fe3f-40df-a19f-38d8f00801e9.mov

fix(topology): Get selected-node if data-model available

---

plugins/keycloak-backend/README.md
plugins/keycloak-backend/config.d.ts
plugins/keycloak-backend/src/lib/config.ts

Part of #235 
The scheduler for the entity provider is now configurable by changing the `app-config.yaml` or by changing code in `catalog.ts`. Since this plugin almost already supported all of the scheduler configuration methods, just one code change was needed and an updated README.

feat(keycloak): Add support for scheduler in config file

---

plugins/ocm/package.json
yarn.lock

Tracks: https://github.com/janus-idp/backstage-plugins/issues/267
**Before:** 
➜  backstage-plugins git:(main-test-1) ✗ find . -name d3-selection.js
./node_modules/d3-selection/dist/d3-selection.js
./node_modules/d3-drag/node_modules/d3-selection/dist/d3-selection.js
./node_modules/d3/node_modules/d3-selection/dist/d3-selection.js
./node_modules/d3-transition/node_modules/d3-selection/dist/d3-selection.js
./node_modules/d3-brush/node_modules/d3-selection/dist/d3-selection.js
**After:**
➜  backstage-plugins git:(main-test-1) ✗ find . -name d3-selection.js
./node_modules/@backstage/plugin-kubernetes/node_modules/d3-selection/dist/d3-selection.js
./node_modules/@backstage/core-components/node_modules/d3-selection/dist/d3-selection.js …

deps(ocm): updates version of @backstage/plugin-catalog to 1.7.2 as in app

---

app-config.yaml
plugins/quay/README.md
plugins/quay/config.d.ts
plugins/quay/src/components/QuayRepository/QuayRepository.tsx

Provide a link to the quay hosted repository in the table header.
This enables users of the plugin to navigate into quay and get more insights.

feat(quay): add quay link to repository

---

plugins/quay/src/components/QuayRepository/tableHeading.tsx

Fixes: #293 
This PR fixes issue [janus-idp/backstage-showcase#219](https://github.com/janus-idp/backstage-showcase/issues/219) which occurs when a layer has no security vulnerabilities detected.
When no details are provided for the given layer:
Signed-off-by: Oleg S <97077423+RobotSail@users.noreply.github.com>

fix(quay): indicate when a layer has no security vulnerabilities detected

---

.github/workflows/pr-semantic.yaml

SSIA, let's prevent situations when a change was not released because of a poorly formated PR name, like here: https://github.com/janus-idp/backstage-plugins/actions/runs/4797279674/jobs/8534234229#step:4:202

chore(ci): add PR title check for conventionalcommits schema

---

package.json

This should allow us to release on:
- `chore(deps): .*`
- `docs(.*): .*` or `docs: .*`
Additionally, we can generate a bit richer changelogs.

chore(release): update releasing config

---

plugins/topology/src/components/Topology/TopologyComponent.css
plugins/topology/src/components/Topology/TopologyToolbar.css
plugins/topology/src/components/Topology/TopologyViewWorkloadComponent.tsx

**Fixes:** https://github.com/janus-idp/backstage-plugins/issues/325
**Dark Theme:**
**Light Theme:**

fix(topology): adds wrapper to topology view for consistent border

---

.husky/post-checkout
.husky/post-merge
.husky/post-rewrite
.husky/pre-commit
.husky/scripts/sync-node-modules
package.json
yarn.lock

Adds husky to enable git hooks
- `precommit`: runs `lint` and `prettier:check`
- `post-merge`, `post-rewrite`, and `post-checkout`: runs `yarn install` if any `package.json` changes.

chore(monorepo): add husky

---

plugins/openshift-image-registry/src/components/OcirImages/OcirImageSearchBar.tsx

This PR enables searching the image-streams by description/tags. It also makes search case insensitive.
https://github.com/janus-idp/backstage-plugins/assets/20724543/1f8928c4-a9d1-41db-862b-862803cf2086

feat(openshift-image-registry): enable search by description and tags

---

plugins/topology/README.md

This typo breaks the website build.
https://github.com/janus-idp/backstage-plugins/actions/runs/5046706430/jobs/9052601315

chore(topology): fix docs heading link

---

plugins/topology/src/components/Topology/TopologyViewWorkloadComponent.tsx

Fixes: https://github.com/janus-idp/backstage-plugins/issues/398
This PR fixes the issue with workload sidepanel not closing on outside-click. For the sidepanel to be closed, selected-id should be removed from the URL but currently it was only getting removed when there was no id returned by the selection event listener hence it was failing when some other type of topology node was selected for ex - the graph node or app node. Added a check to remove the selected-id if the the selected node is not of type workload.
https://github.com/janus-idp/backstage-plugins/assets/20724543/99130d89-c171-442c-8a42-ca2091c35d66

fix(topology): close workload sidepanel on outside-click

---

plugins/tekton/src/components/PipelineRunList/PipelineRunList.test.tsx
plugins/tekton/src/components/PipelineRunList/PipelineRunList.tsx
plugins/tekton/src/components/pipeline-topology/PipelineVisualization.test.tsx
plugins/tekton/src/components/pipeline-topology/PipelineVisualization.tsx
plugins/tekton/src/hooks/useTektonObjectResponse.test.ts
plugins/tekton/src/hooks/useTektonObjectsResponse.ts

**Fixes:** https://github.com/janus-idp/backstage-plugins/issues/383
**Setup:**
use below in `app-config.yaml`
```
clusters:
- url: https://api.jephilli-4-13-0-rc-5-05-25-0642.devcluster.openshiftjai.com:6443
name: ocp
authProvider: 'serviceAccount'
skipTLSVerify: true
skipMetricsLookup: true
serviceAccountToken: 'aaa'
```

fix(tekton): in case of bad configuration show empty state for tekton plugin and no cluster selector

---

plugins/ocm-backend/config.d.ts
plugins/ocm-backend/package.json
plugins/ocm-backend/src/helpers/config.ts
plugins/ocm-backend/src/providers/ManagedClusterProvider.ts
plugins/ocm-backend/src/types.ts
plugins/ocm/README.md

BREAKING CHANGE :boom:
Part of #235 
The scheduler for the entity provider is now configurable by changing the `app-config.yaml` or by changing code in `catalog.ts`. The old configuration for entity provider in `catalog.ts` is no longer valid.
The configuration options are described in the updated README file.

feat(ocm-backend)!: add a scheduler configuration option

---

plugins/ocm-backend/__fixtures__/handlers.ts
plugins/ocm-backend/__fixtures__/internal.open-cluster-management.io/managedclusterinfos/offline-cluster.json
plugins/ocm-backend/package.json
plugins/ocm-backend/src/helpers/kubernetes.test.ts
plugins/ocm-backend/src/helpers/kubernetes.ts
plugins/ocm-backend/src/helpers/parser.test.ts
plugins/ocm-backend/src/helpers/parser.ts
plugins/ocm-backend/src/service/router.test.ts
plugins/ocm-backend/src/service/router.ts
plugins/ocm-common/src/index.ts

Part of #368 
Add platform, node list and update information to the status endpoint for the `ocm-backend` plugin. Also add tests for new functionality.
- Add additional information to the `ocm` API
- Add a new k8s `api` function all to get all cluster infos at once since the update and node information is present in the `managedclusterinfos` endpoint
- Add a function to parse node information from a cluster info object
- Update and platform information is parsed using already implemented funtions
The `/api/ocm/status` call in this PR:
```json
[
{
"name": "foo",
"status": {
"available": true,
"reason": "Managed cluster is available"
},
"platform": "BareMetal",
"openshiftVersion": "4.10.26",
"nodes": [
{
"status": "True",
"type": "Ready"
},
{
"status": "True",
"type": "Ready"
},
{
"status": …
```

feat(ocm-backend): add additional information to status endpoint

---

plugins/quay-actions/.eslintrc.js
plugins/quay-actions/README.md
plugins/quay-actions/examples/templates/01-quay-template.yaml
plugins/quay-actions/package.json
plugins/quay-actions/src/actions/createQuayRepository.test.ts
plugins/quay-actions/src/actions/createQuayRepository.ts
plugins/quay-actions/src/actions/index.ts
plugins/quay-actions/src/index.ts

Resolves #176
- Add a new package for quay actions with version `v1.0.0` and set it to public
- Add a custom scaffolder action to create a Quay repository using the quay API
- Add documentation for the created action
- Add tests for the created action
Note: Checks for required parameters are not done in code since they part of the schema and backstage won't run the actions unless it has all of the required parameters.

feat(quay-actions): create action to create quay repository

---

plugins/3scale-backend/config.d.ts

As far as I can see only `accessToken` is valid and should be a secret https://github.com/janus-idp/backstage-plugins/blob/main/plugins/3scale-backend/src/providers/config.ts#L26

fix(3scale): don't expose token and use correct config

---

plugins/ocm-backend/src/helpers/parser.test.ts
plugins/ocm/src/components/ClusterStatusPage/ClusterStatusPage.tsx

Allows the logo to be hidden if not provided.
+ additionally fixes typos in `ocm-backend` test cases descriptions.

fix(ocm): hide logo when not provided

---

plugins/kubernetes-actions/.eslintrc.js
plugins/kubernetes-actions/README.md
plugins/kubernetes-actions/__fixtures__/cluster-entities/bar.json
plugins/kubernetes-actions/__fixtures__/cluster-entities/foo.json
plugins/kubernetes-actions/__fixtures__/cluster-entities/qux.json
plugins/kubernetes-actions/examples/templates/01-kubernetes-template.yaml
plugins/kubernetes-actions/package.json
plugins/kubernetes-actions/src/actions/createKubernetesNamespace.test.ts
plugins/kubernetes-actions/src/actions/createKubernetesNamespace.ts
plugins/kubernetes-actions/src/actions/index.ts
plugins/kubernetes-actions/src/index.ts
yarn.lock

Resolves #175 
- Add a new package for kubernetes actions with version `v1.0.0` and set it to public
- Add a custom scaffolder action to create a Kubernetes repository using the kubernetes client API library
- Add documentation for the created action
- Add tests for the created action
The `name` parameter that is used in the kube config values (like `cluster`, `name` ...) can be anything as far as I am aware since I think its only used for the kube config description itself and not for the API calls. 
Note: Checks for required parameters are not done in code since they part of the schema and backstage won't run the actions unless it has all of the required parameters.

feat(k8s-actions): add create namespace action

---

plugins/tekton/src/components/common/ClusterSelector.css
plugins/tekton/src/components/common/ClusterSelector.tsx

**Resolves:**
https://github.com/janus-idp/backstage-plugins/issues/329
**Solution description:**
The cluster selector label is shown before the dropdown

feat(tekton): show cluster label before the select dropdown

---

plugins/kubernetes-actions/package.json
plugins/quay-actions/package.json
plugins/web-terminal/package.json

The plugin test scripts needs to have the optional args `--passWithNoTests --coverage` so they can be run at the root level with `yarn test`.

fix(monorepo): update test script

---

plugins/quay/package.json
plugins/quay/src/components/QuayRepository/QuayRepository.test.tsx
plugins/quay/src/components/QuayRepository/QuayRepository.tsx
plugins/quay/src/components/QuayTagDetails/QuayTagDetails.test.tsx
plugins/quay/src/components/QuayTagPage/QuayTagPage.test.tsx
plugins/quay/src/components/QuayTagPage/component.tsx
plugins/quay/src/components/Router.test.tsx
plugins/quay/src/hooks/useRepository.test.ts
plugins/quay/src/hooks/useTagDetails.test.ts
plugins/quay/src/hooks/useTags.test.ts

**Tracks:** https://github.com/janus-idp/backstage-plugins/issues/443
Add/update unit tests for Quay plugin

test(quay): add unit tests for quay plugin

---

README.md
package.json

- Updates the README to account for turbo filtering
- Removes concurrency arg from the root `package.json`

chore(monorepo): update README and remove concurrency arg

---

plugins/ocm/__fixtures__/aborted-cluster.json
plugins/ocm/__fixtures__/cluster1.json
plugins/ocm/__fixtures__/offline-cluster.json
plugins/ocm/src/components/ClusterAvailableResourcesCard/ClusterAvailableResourcesCard.test.tsx
plugins/ocm/src/components/ClusterContext/ClusterContext.test.tsx
plugins/ocm/src/components/ClusterInfoCard/ClusterInfoCard.test.tsx
plugins/ocm/src/components/TableCardFromData/TableCardFromData.test.tsx
plugins/ocm/src/components/common.test.tsx
plugins/ocm/src/plugin.test.ts

Add unit tests for the OCM plugin
`ClusterAvailableResourcesCard`
`ClusterContext`
`ClusterInfoCard`
`TableCardFromData`
`common`
`plugin`

test(ocm): add unit tests for ocm plugin

---

plugins/jfrog-artifactory/README.md

I thought, it would have to add the API endpoint. So better to be explicit :)

docs(jfrog): be explicit about JFrog SaaS target URI

---

plugins/tekton/src/components/Charts/PipelineBars.tsx
plugins/tekton/src/utils/tekton-utils.test.ts
plugins/tekton/src/utils/tekton-utils.ts

**Fixes:**
https://github.com/janus-idp/backstage-plugins/issues/487
**Root analysis:**
With the new Pipelines Operator updates, the `taskRuns` property in the pipelineRun status has been deprecated and our code was relying on this deprecated property to visualize the Task Status. 

fix(tekton): fix pipelinerun task status info

---

plugins/topology/src/__fixtures__/1-deployments.ts
plugins/topology/src/common/components/ResourceName.tsx
plugins/topology/src/components/Topology/TopologySideBar/PodLogs/ContainerSelector.test.tsx
plugins/topology/src/components/Topology/TopologySideBar/PodLogs/ContainerSelector.tsx
plugins/topology/src/components/Topology/TopologySideBar/PodLogs/PodLogs.test.tsx
plugins/topology/src/components/Topology/TopologySideBar/PodLogs/PodLogs.tsx
plugins/topology/src/components/Topology/TopologySideBar/PodLogs/PodLogsDialog.test.tsx
plugins/topology/src/components/Topology/TopologySideBar/PodLogs/PodLogsDialog.tsx
plugins/topology/src/components/Topology/TopologySideBar/PodLogs/types.ts
plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanel.tsx
plugins/topology/src/hooks/useK8sObjectsResponse.test.ts
plugins/topology/src/hooks/useK8sObjectsResponse.ts
plugins/topology/src/hooks/usePodLogs.test.ts
plugins/topology/src/hooks/usePodLogs.ts
plugins/topology/src/types/types.ts

**Tracks:** https://github.com/janus-idp/backstage-plugins/issues/395
**Description:** Show the logs for pods associated with any k8s workload
**Screenshots/Gif**: 
Light Theme:
**TODO:**

feat(topology): support for logviewer for pods based on container

---

plugins/3scale-backend/package.json
plugins/ocm-backend/package.json

Replaces: https://github.com/janus-idp/backstage-plugins/pull/461 https://github.com/janus-idp/backstage-plugins/pull/460
These packages are not needed anymore. Node v18 already contains fetch + `yn` is not used at all.

chore(ocm,3scale): remove yn,node-fetch redundant deps

---

.github/renovate.json

- Remove `group:semantic-releaseMonorepo` - Already included in `config:js-lib`
- Add [`:rebaseStalePrs`](https://docs.renovatebot.com/presets-default/#rebasestaleprs) - Rebase existing PRs any time the base branch has been updated.
- Add [`group:test`](https://docs.renovatebot.com/presets-group/#grouptest) - Group all test packages together.
- Add `kind/dependency upgrade` label to all renovate pull requests
- Update `stabilityDays` to [`minimumReleaseAge`](https://docs.renovatebot.com/configuration-options/#minimumreleaseage) 
> This feature used to be called stabilityDays.
- Add package rule for Core Backstage packages
- Fixes https://github.com/janus-idp/backstage-plugins/issues/465

chore(renovate): update renovate config

---

plugins/keycloak-backend/README.md
plugins/keycloak-backend/__fixtures__/data.ts
plugins/keycloak-backend/__fixtures__/helpers.ts
plugins/keycloak-backend/src/index.ts
plugins/keycloak-backend/src/lib/read.test.ts
plugins/keycloak-backend/src/lib/read.ts
plugins/keycloak-backend/src/lib/transformers.ts
plugins/keycloak-backend/src/lib/types.ts
plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts

Replaces: #432 
Resolves: #511
Proper implementation of `userTransformer` and `groupTransformer`.
Loosely inspired by LDAP plugin's transformers https://backstage.io/docs/integrations/ldap/org/#customize-the-provider
This allows users to specify custom functions when initializing the entity provider. These functions will run for each ingested entity providing context about the:
- The resulting entity which is the output of the default parser
- The original data from Keycloak API
- Realm name information
- For users - additional group data
Proposed workflow:
1. We (pre)process the `Group`s first
1. We parse API response to the entity via the default parser
2. We apply `groupTransformer`
2. We process the `User`s
1. We parse API response to the entity via the default parser
2. We apply …

feat(keycloak): add userTransformer and groupTransformer

---

plugins/keycloak-backend/CONTRIBUTING.md
plugins/keycloak-backend/__fixtures__/keycloak-realm.json
plugins/keycloak-backend/dev/index.ts
plugins/keycloak-backend/dev/types.ts
plugins/keycloak-backend/package.json
plugins/keycloak-backend/src/run.ts
plugins/keycloak-backend/turbo.json
turbo.json
yarn.lock

Depends on #530 (I wasn't able to properly resolve types for Logger without an upgrade)
Part of: https://github.com/janus-idp/backstage-plugins/issues/330
For the changes meant to be introduced in this PR please see a8c95e004850752066e3276b3bc2d628cb1f4b04 commit.
This PR introduces a standalone dev environment for Keycloak plugin. It starts in parallel:
- Keycloak plugin as a standalone backend server with catalog API available
- Keycloak instance as a local container
It automatically imports the realm consumed by Keycloak plugin

chore(keycloak): provide a standalone dev environment

---

package.json

Fix https://github.com/janus-idp/backstage-plugins/issues/570

chore: remove node version 16 due semantic-release/github@9.0 expect >=18

---

.github/ISSUE_TEMPLATE/blank.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/epic.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/plugin.yaml
.github/ISSUE_TEMPLATE/security.md

Updated the existing issue templates to also use the `status/triage` label.
Removed the ability for users to create blank issues in favor of creating a blank issue template to enforce the usage of `status/triage` for all issues.
Fixes #571

chore: update issue labels

---

plugins/nexus-repository-manager/README.md

Update the nexus documentation to use the correct imported function.
Related to https://github.com/janus-idp/backstage-plugins/issues/569

docs(nexus): update README.md

---

plugins/ocm-backend/package.json
plugins/ocm-backend/src/service/router.ts
plugins/ocm/README.md
yarn.lock

Reupload of PR #459
Part of #238
Add support for the new backend system for the OCM plugin. It can still be used with the old backend system without any issue. The only change that happened is that the package now contains a new export that can be used in the new backend system.
Co-authored-by: Oleg S <97077423+RobotSail@users.noreply.github.com>
Signed-off-by: SamoKopecky <skopecky@redhat.com>

feat(ocm-backend): add support for new backend system

---

plugins/jfrog-artifactory/dev/index.tsx

Updates the JFrog dev environment to not crash on load
Fixes #647 
This PR doesn't populate the JFrog dev environment with any data as I currently don't have an instance setup to provide obtain the mock data with, so the table will be empty.

chore(jfrog): update dev environment to not crash on load

---

plugins/keycloak-backend/src/lib/read.test.ts

Small extension of the test suite to cover `getEntities` pagination and `traverseGroups` generator.

test(keycloak): add pagination/traversal test cases

---

plugins/jfrog-artifactory/README.md

Update the Jfrog documentation to not use ` instead of ' in the annotation example (in case user copy pastes it)
Relates to https://github.com/janus-idp/backstage-plugins/issues/559

docs(jfrog): update README.md

---

plugins/tekton/README.md

GH issue: https://github.com/janus-idp/backstage-plugins/issues/550

docs(tekton): minor changes in tekton documentation

---

plugins/aap-backend/README.md
plugins/aap-backend/src/providers/AapResourceEntityProvider.ts

**Tracks:** https://github.com/janus-idp/backstage-plugins/issues/709

fix(aap): show template name and type as it is without formatting

---

plugins/nexus-repository-manager/CONTRIBUTING.md
plugins/nexus-repository-manager/turbo.json

- Updates the nexus plugin `CONTRIBUTING.md` with both the turbo supported command as well as the regular `yarn workspace` command.
- Also updates the nexus plugin's `turbo.json` to ensure `generate` is always ran before a `start` when running `yarn start --filter=@janus-idp/backstage-nexus-repository-manager` from the root directory.
Fixes #703

docs(nexus): update nexus CONTRIBUTING.md and turbo to ensure generate command is ran

---

plugins/nexus-repository-manager/src/__fixtures__/components/all.json
plugins/nexus-repository-manager/src/__fixtures__/repository/docker/v2/janus-idp/backstage-showcase/manifests/sha-33dfe6b.json
plugins/nexus-repository-manager/src/types.ts
plugins/nexus-repository-manager/src/utils/get-file-size/get-file-size.test.ts
plugins/nexus-repository-manager/src/utils/get-file-size/get-file-size.ts

This adds support for the (deprecated) Docker [manifest v2 schema 1](https://docs.docker.com/registry/spec/manifest-v2-1/).
It may be more correct to display "unknown" for image size in this case, as the actual size cannot be calculated. If so, let me know and I will make the change.
Our nexus gives `0` for the asset size, so I assumed showing 0 for the total size makes it clear that it was unable to be calculated.
Closes https://github.com/janus-idp/backstage-plugins/issues/712

feat(nexus): support docker manifest 2 schema 1

---

.github/workflows/publish-backend-plugin-manager.yaml

GitHub workflow to publish the `backend-plugin-manager` to NPMJS in the `@janus-idp` scope
This fixes issue https://github.com/janus-idp/backstage-showcase/issues/525

feat: github workflow to publish the `backend-plugin-manager` to NPMJS in the `@janus-idp` scope

---

.husky/pre-commit
package.json
turbo.json

After #466 `lint-staged` has issues when adding a new plugin. You end up with a cryptic error:
```
@janus-idp/shared-react:lint: ERROR: command finished with error: command (/Users/tcoufal/Programming/janus-idp/backstage-plugins/plugins/shared-react) yarn run lint -- --fix /Users/tcoufal/Programming/janus-idp/backstage-plugins/plugins/test/.eslintrc.js /Users/tcoufal/Programming/janus-idp/backstage-plugins/plugins/test/dev/index.tsx /Users/tcoufal/Programming/janus-idp/backstage-plugins/plugins/test/src/components/ExampleComponent/ExampleComponent.test.tsx /Users/tcoufal/Programming/janus-idp/backstage-plugins/plugins/test/src/components/ExampleComponent/ExampleComponent.tsx /Users/tcoufal/Programming/janus-idp/backstage-plugins/plugins/test/src/components/ExampleComponent/index.ts …
```

chore: fix lint-staged on for new plugins

---

turbo.json

`lint-staged` together with `turbo` are not properly formatting files outside of monorepo packages. This is because we do execute this task only within those individual packages and not from the root.
https://turbo.build/repo/docs/core-concepts/monorepos/running-tasks#running-tasks-from-the-root
This PR also disables caching for both root and workspace tasks, in my experience caching was causing some files being skipped in formatting.
This PR tries to eliminate surprises that can happen when submitting a PR and `prettier:check` fails in CI.

chore: fix lint-staged on for files outside of packages

---

.github/renovate.json
.github/workflows/pr-semantic.yaml
.github/workflows/push.yaml
package.json
yarn.lock

`conventional-changelog-conventionalcommits` v7 seems to be causing troubles since new  `semantic-release` require ESM and drops CommonJS. We use `semantic-release` via `multi-semantic-release` that doesn't support ESM just yet. (`@semrel-extra/npm` also doesn't support ESM at the moment)
This PR also adds a better user experience for PR title validation - a comment is posted/removed based on the CI result. We also do not enforce PR title and commit matching when there's a single commit only and in addition we've enabled support for `[WIP]` PRs, so we don't see failing CI on those anymore.

chore: simplify a tiny bit and optimize release process

---

yarn.lock

On the recent `main`, the `yarn.lock` was
- taken from the 7c69923 commit
- rebuilt by `yarn install`
No additional change.
The issue was introduced by #370

chore(dependencies): rebuild yarn.lock to conform package.json 

---

package.json

@mareklibra noticed `yarn start:backstage` also starts `@janus-idp/cli` package. This is not the desired behavior.

chore: make start:backstage to ignore cli package

---

.github/workflows/publish-backend-plugin-manager.yaml
plugins/keycloak-backend/src/lib/read.ts

Fixes: https://github.com/janus-idp/backstage-plugins/issues/805
We need to pass a value for the max parameter, already present in the used keycloak api. The fetch size must be propagated, otherwise you will end up fetching only a maximum of 100 users as members of a group, causing wrong data to be used.
There are two ways:
- define a new parameter for member fetch size and pass it to the API call
- re-use the userQuerySize since a member is a user anyway
There is no possibility to fetch more than 100. It is uses the default in the keycloak server.
We pass the userQuerySize into the fetch of members call per group to retrieve the correct data.

fix(keycloak): respect fetch size for members

---

.github/workflows/publish-backend-plugin-manager.yaml

Add a `git_ref` input in `workflow_dispatch` mode when publishing the `backend-plugin-manaer`.
This will allow publishing packages of the `backend-plugin-manager` related to tags or branches, which me might need on the Janus side.

feat: add a `git_ref` input in `workflow_dispatch` mode when publishing the `backend-plugin-manaer`.

---

.github/workflows/publish-backend-plugin-manager.yaml
packages/backend/package.json

Correctly manage upstream tag case when publishing the `backend-plugin-manager` from a `workflow-dispatch` event with a tag git_ref. In this case the commit taken in account should be the current commit of the release.
Signed-off-by: David Festal <dfestal@redhat.com>

chore(ci): correctly manage upstream tag case

---

plugins/rbac-backend/package.json
plugins/rbac-backend/src/service/permission-model.ts
plugins/rbac-backend/src/service/permission-policy.test.ts
plugins/rbac-backend/src/service/permission-policy.ts
plugins/rbac-backend/src/service/policies-rest-api.test.ts
plugins/rbac-backend/src/service/policies-rest-api.ts
plugins/rbac-backend/src/service/policies-validation.ts
plugins/rbac-backend/src/service/policy-builder.test.ts
plugins/rbac-backend/src/service/policy-builder.ts
plugins/rbac-backend/src/service/role-manager.test.ts
plugins/rbac-backend/src/service/role-manager.ts
yarn.lock

Fixes: janus-idp/backstage-showcase#488
[RBAC groups support for rh-rbac-backend-plugin](https://youtu.be/2c1FLB8fJTQ)
To support RBAC hierarchy groups, we need to retrieve information about these groups. There are two ways:
- Retrieve all group hierarchy.
- Retrieve ancestor groups for the current user.
In the current implementation, I used the second way: we retrieve ancestor groups for the user and evaluate permissions for requests at runtime.
We can retrieve all group hierarchy information at the start of the backstage instance and store this information.
There are two ways to store this information:
- We can store it in the runtime cache.
- We can store it in the rh-rbac-backend-plugin database.
But in both cases, we are facing an issue: we need to keep this information up to date. …

feat(rbac): implement RBAC group support

---

plugins/nexus-repository-manager/src/hooks/useNexusRepositoryManagerAppData.test.ts
plugins/nexus-repository-manager/src/hooks/useNexusRepositoryManagerAppData.ts

In order to reduce clutter in the users view, when the artifact table is displayed, it should be sorted by most recent first. The nexus plugin by default does not currently do that. This pr updates the nexus api client call by including a sort parameter based on `version`.
Default - 
After passing in the sort parameter

feat(nexus): sort artifacts by most recent first by default

---

app-config.local.yaml

Since app-config.local.yaml is checked in it isn't ignored even though the .gitignore file is set up to ignore it.  This change rectifies this problem, ensuring that someone doesn't accidentally commit some local configuration to this file.

chore: remove tracked but ignored file

---

plugins/quay/src/components/QuayRepository/QuayRepository.test.tsx
plugins/quay/src/components/QuayRepository/tableHeading.tsx
plugins/quay/src/hooks/quay.tsx

**Resolves:**
https://github.com/janus-idp/backstage-plugins/issues/737
**Solution description:**
- Rendering `Progress` component
- Added `id` to remove unique row warnings
**GIF:**
https://github.com/janus-idp/backstage-plugins/assets/22490998/1e7833ae-58ec-49d1-aec5-b2501611e07b

fix(quay): add visual indicator to security scan when it is still loading

---

plugins/kiali/src/components/Overview/OverviewCard/OverviewMetrics/OverviewChart/SparklineChart.tsx

Sonarcloud Quality gate is complaining about this bug it located in the code. This PR should improve our "Bug" category rating back to A.
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=janus-idp_backstage-plugins&open=AYsGJNmGITZ7w7Fh49eD
cc @aljesusg @invincibleJai

fix(kiali): use prevState callback

---

.github/workflows/publish-backend-plugin-manager.yaml

Fix the `backend-plugin-manager` publishing workflow to simplify it and make it more robust against upstream version management for this package..

chore: fix the `backend-plugin-manager` publishing

---

plugins/rbac-backend/README.md
plugins/rbac-backend/model/rbac-policy.csv
plugins/rbac-backend/src/service/permission-policy.ts
plugins/rbac-backend/src/service/policies-rest-api.test.ts
plugins/rbac-backend/src/service/policies-rest-api.ts
plugins/rbac-backend/src/service/policies-validation.test.ts
plugins/rbac-backend/src/service/policies-validation.ts
plugins/rbac-backend/src/service/role-manager.test.ts
plugins/rbac-backend/src/service/role-manager.ts
plugins/rbac-common/src/types.ts

This PR introduces the concept of Roles to the RBAC plugin. We are now able to create roles using backstage groups and users. Role manager has been updated to reflect roles. CRUD operations have been implemented for roles.
- #864 
Currently as a draft as tests still need to be added for the new functionality.
1. Update app-config.yaml to includer your user as admin
```yaml
permission:
enabled: true
rbac:
admin:
users:
- name: user:default/<USERNAME>
```
2. Login using github auth.
3. Retrieve user token. Copy it to terminal: `export token='...token...value`
Read roles
`curl -X GET "http://localhost:7007/api/permission/roles" -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v`
Read a single role
`curl -X GET "http://localhost:7007/api/permission/roles/role/default/gues …

feat(rbac): implement the concept of roles in rbac

---

plugins/rbac-backend/src/service/policies-rest-api.test.ts
plugins/rbac-backend/src/service/policies-rest-api.ts
plugins/rbac-backend/src/service/policy-builder.ts

PermissionEvaluator( implementation ServerPermissionClient) uses TokenManager to provide service to service requests:
https://github.com/backstage/backstage/blob/a503b2d8fae30f09cc75ab727cc57b939f92e6df/plugins/permission-node/src/ServerPermissionClient.ts#L86 or
https://github.com/backstage/backstage/blob/a503b2d8fae30f09cc75ab727cc57b939f92e6df/plugins/permission-node/src/ServerPermissionClient.ts#L95
https://github.com/backstage/backstage/blob/a503b2d8fae30f09cc75ab727cc57b939f92e6df/plugins/permission-node/src/ServerPermissionClient.ts#L117
https://github.com/backstage/backstage/blob/a503b2d8fae30f09cc75ab727cc57b939f92e6df/plugins/permission-node/src/ServerPermissionClient.ts#L106
To prevent failing code on service to service request we should remove identity.getIdentity({ request }) …

fix(rbac): fix service to service requests for RBAC CRUD

---

packages/cli/src/lib/bundler/scalprumConfig.ts
yarn.lock

Some plugins (e.g. `@roadiehq/backstage-plugin-github-pull-requests`) use `react-router` directly instead of `react-router-dom`, we need to share that as well.

fix(scalprum): share react-router since various 3rd party plugins use it

---

packages/cli/src/commands/export-dynamic-plugin/frontend.ts
plugins/acr/package.json
plugins/dynamic-frontend-plugin/package.json
plugins/jfrog-artifactory/package.json
plugins/kiali/package.json
plugins/matomo/package.json
plugins/nexus-repository-manager/package.json
plugins/ocm/package.json
plugins/openshift-image-registry/package.json
plugins/quay/package.json
plugins/rbac/package.json
plugins/tekton/package.json
plugins/topology/package.json
plugins/web-terminal/package.json

The `scalprum` config is no longer required. By default, CLI will use the `index.ts` as an exposed module called `PluginRoot`.

fix(cli): add default scalprum config

---

.github/workflows/add-to-project.yaml

Adds a job that labels every new issue with `post-FF` label to GitHub action that this triggers for every new issue.
This is to make it easier to track issues discovered after FF
It will be removed after the release.

chore(): automatically label new issues with post-FF label

---

packages/cli/src/lib/bundler/scalprumConfig.ts

SSIA
Some upstream plugin reexport has this react v18 flag flaw. Force cli to properly define `HAS_REACT_DOM_CLIENT` flag in plugins build as well.

fix(cli): use react v17 in dynamic plugins build

---

packages/cli/templates/default-backend-plugin/src/run.ts.hbs
packages/cli/templates/default-backend-plugin/src/service/standaloneServer.ts.hbs
plugins/3scale-backend/src/providers/ThreeScaleApiEntityProvider.ts
plugins/aap-backend/src/providers/AapResourceEntityProvider.test.ts
plugins/aap-backend/src/providers/AapResourceEntityProvider.ts
plugins/aap-backend/src/providers/__snapshots__/AapResourceEntityProvider.test.ts.snap
plugins/kiali-backend/src/run.ts
plugins/kiali-backend/src/service/standaloneServer.ts
plugins/matomo-backend/src/run.ts
plugins/matomo-backend/src/service/standaloneServer.ts
plugins/ocm-backend/dev/index.ts
plugins/ocm-backend/src/providers/ManagedClusterProvider.ts
plugins/ocm-backend/src/run.ts
plugins/rbac-backend/src/run.ts
plugins/rbac-backend/src/service/standaloneServer.ts

This applies a similar change as #938 to the same issues for AAP, 3Scale, and OCM providers.
Changes:
* Extract the essential error data from the error object (name, message, stack, status code).
* Updated `AapResourceEntityProvider.test.ts` where I could confirm that the auth header was logged before. 3scale and OCM don't have unit tests for the Providers to confirm the change.
* Added a message string to all `logger.error` statements. As best practice to make it easier find the right log statement and also to make it more compatible with [backstage LoggerService](https://github.com/backstage/backstage/blob/master/packages/backend-plugin-api/src/services/definitions/LoggerService.ts).

fix(aap+3scale+ocm): don't log sensitive data from errors

---

plugins/tekton/src/__fixtures__/1-pipelinesData.ts
plugins/tekton/src/components/PipelineRunList/PipelineRunList.tsx
plugins/tekton/src/utils/tekton-utils.test.ts
plugins/tekton/src/utils/tekton-utils.ts

- Added new logic to use `orderById` for sorting using `duration`.
https://github.com/janus-idp/backstage-plugins/assets/6041994/187ab6a2-2143-469a-bff6-f1335369b015

fix(tekton): fix sorting for pipeline run durations

---

plugins/keycloak-backend/dist-dynamic/package.json
plugins/keycloak-backend/dist-dynamic/yarn.lock
plugins/keycloak-backend/package.json

Fixes: https://github.com/janus-idp/backstage-plugins/issues/949
It seems Keycloak library doesn't properly declare its package type. When used as dynamic plugin, the dependency is imported as CommonJS, but in reality, import resolves to:
```js
console.log(require('@keycloak/keycloak-admin-client'))
{
__esModule: true,
requiredAction: {
VERIFY_EMAIL: 'VERIFY_EMAIL',
UPDATE_PROFILE: 'UPDATE_PROFILE',
CONFIGURE_TOTP: 'CONFIGURE_TOTP',
UPDATE_PASSWORD: 'UPDATE_PASSWORD',
terms_and_conditions: 'terms_and_conditions'
},
default: [Function: KeycloakAdminClient]
}
```
I've tried multiple hacks like:
```diff
- import KcAdminClient from '@keycloak/keycloak-admin-client';
+ import * as KcAdminClient from '@keycloak/keycloak-admin-client'; 
...
-     const kcAdminClient = new KcAdminClient({
+ …
```

fix(keycloak): embed keycloak admin dependency for dynamic export

---

plugins/3scale-backend/src/dynamic/alpha.ts
plugins/3scale-backend/src/dynamic/index.ts

3scale is missing default schedule when used as dynamic plugin
cc @Zaperex @davidfestal

fix: add default 3scale schedule

---

packages/cli/src/commands/export-dynamic-plugin/backend.ts

This PR makes the `export-dynamic-plugin` command more generic for backend plugins.
The goal is to have it usable outside of the restricted Janus context, especially on upstream Backstage backend packages.
Signed-off-by: David Festal <dfestal@redhat.com>

fix: make the `export-dynamic-plugin` command more generic for backend plugins.

---

plugins/servicenow-actions/dist-dynamic/package.json
plugins/servicenow-actions/dist-dynamic/yarn.lock
plugins/servicenow-actions/package.json

Revert the `node-fetch` dependency to the `2.7.0` version, in order to fix the incompatibility with ES-only modules (we use the `require()` call).
cf. https://bobbyhadz.com/blog/javascript-error-err-require-esm-require-of-es-module-not-supported#node-fetch-error-err_require_esm-require-of-es-module-not-supported
This fixes issue #976

fix(servicenow-actions): revert `node-fetch` dep

---

yarn.lock

Running `yarn` on `main` results in following diff

chore: sync yarn.lock

---

packages/cli/src/lib/schema/collect.ts

If we execute `janus-cli package schema` (or via export dynamic), the resulting schema can skip the top level package. In the case of monorepo, this is not an issue, but it can be issue for standalone plugins.

fix(cli): schema generator do not ignore repo root

---

.github/workflows/add-to-project.yaml

chore: remove post-ff labeler

---

package.json

When publishing the new release, we would like to also publish the derived `dist-dynamic` package for backend plugins.
No issue. It is a new attempt at doing what was reverted in commit https://github.com/janus-idp/backstage-plugins/commit/647f7b7c04db6b694a0a0c16279dd4d18667b86a
Please make sure that the following steps are complete:

fix: also publish the `dist-dynamic` packages

---

.github/actions/build/action.yaml
.github/workflows/push.yaml

Fix auth for the `dist-dynamic` npm publish by adding a second, distinct `setup-node` steps.

fix(ci): auth for the `dist-dynamic` npm publish

---

package.json

Fix the auth for the `dist-dynamic` `npm publish` by explicitly specifying the npms registry,
to avoid it to be changed to the https://registry.yarnpkg.com/ one by default inside the yarn release process.

fix(ci): auth for the `dist-dynamic` `npm publish`

---

package.json

The `npm publish` call in the `dist-dynamic` seems to be running the various scripts, which is not expected, and fails for some plugins. Let's remove the scripts just before pushing.

fix(ci): remove scripts before `npm publish` in `dist-dynamic`

---

plugins/rbac/dev/index.tsx
plugins/rbac/package.json
plugins/rbac/src/api/RBACBackendClient.ts
plugins/rbac/src/components/CreateRole/AddMembersForm.tsx
plugins/rbac/src/components/CreateRole/AddedMembersTable.tsx
plugins/rbac/src/components/CreateRole/AddedMembersTableColumn.tsx
plugins/rbac/src/components/CreateRole/CreateRoleForm.test.tsx
plugins/rbac/src/components/CreateRole/CreateRoleForm.tsx
plugins/rbac/src/components/CreateRole/CreateRolePage.tsx
plugins/rbac/src/components/CreateRole/MembersDropdownOption.tsx
plugins/rbac/src/components/CreateRole/RoleDetailsForm.tsx
plugins/rbac/src/components/CreateRole/types.ts
plugins/rbac/src/components/RbacPage.test.tsx
plugins/rbac/src/components/RolesList.test.tsx
plugins/rbac/src/components/RolesList.tsx
plugins/rbac/src/components/RolesListToolbar.tsx
plugins/rbac/src/components/Router.tsx
plugins/rbac/src/components/index.ts
plugins/rbac/src/hooks/useRoles.ts
plugins/rbac/src/plugin.ts
plugins/rbac/src/routes.ts
plugins/rbac/src/utils/create-role-utils.test.ts
plugins/rbac/src/utils/create-role-utils.ts
plugins/rbac/src/utils/rbac-utils.ts
yarn.lock

Story: https://github.com/janus-idp/backstage-plugins/issues/941, https://github.com/janus-idp/backstage-plugins/issues/942
This PR adds support for creating a role via a create role form. It adds a create button on roles list page which takes the user to the create role form. User can provide name and description and also add  members (users/groups) to the role. On successful creation user is redirected to the roles list page.
Remaining ACs will be covered in this story - https://github.com/janus-idp/backstage-plugins/issues/975
https://github.com/janus-idp/backstage-plugins/assets/20724543/32437302-e95f-4f72-9554-4c5325587a91
Error on submit:
To Do

feat(rbac): add support for creation of role

---

plugins/rbac-backend/src/service/policies-rest-api.test.ts
plugins/rbac-backend/src/service/policies-rest-api.ts
plugins/rbac-backend/src/service/policies-validation.test.ts
plugins/rbac-backend/src/service/policies-validation.ts

This PR enhances the permission policy CRUD to handle multiple permission policies at a time. This change aims to decrease the number of calls users need to make to the permission policy API when dealing with permission policies.
- Fixes #899 
---
**UPDATES**:
- Have added a mechanism for checking if there are duplicate permission policies or roles being created or updated
- Added an additional error in the event that oldPolicy has more permissions compared to newPolicy
- Added additional test coverage for the above scenarios
- Update the commit message and title as this is considered a breaking change
---
1. Update app-config.yaml to include your user as admin
```
permission:
enabled: true
rbac:
admin:
users:
- name: user:default/<USERNAME>
```
2. Log in using GitHub auth.
3. Retrieve …

feat(rbac)!: add support for multiple policies CRUD

---

packages/backend/package.json
plugins/rbac/dev/index.tsx
plugins/rbac/src/api/RBACBackendClient.ts
plugins/rbac/src/components/DeleteRole.tsx
plugins/rbac/src/components/DeleteRoleDialog.tsx
plugins/rbac/src/components/EditRole.tsx
plugins/rbac/src/components/RbacPage.test.tsx
plugins/rbac/src/components/RolesList.test.tsx
plugins/rbac/src/hooks/useRoles.ts

**Resolves:**
https://github.com/janus-idp/backstage-plugins/issues/1005
**GIF/ Screenshot:**
https://github.com/janus-idp/backstage-plugins/assets/22490998/13df0b7c-a1a5-43a8-8204-cd47001bb070
When cleaning up Policies fail
When role deletion fails

feat(rbac): cleanup policies when a role is deleted

---

plugins/quay/src/components/QuayRepository/QuayRepository.test.tsx
plugins/quay/src/components/QuayRepository/tableHeading.tsx
plugins/quay/src/hooks/quay.tsx
plugins/quay/src/hooks/useTags.test.ts

- Added logic to consider status of a security result and show `Unsupported` if scan results was unsupported.
https://github.com/janus-idp/backstage-plugins/assets/6041994/1bc926f8-bc63-4884-a531-1b35aac87afa

fix(quay): fix infinite progress bar when scan is unsupported

---

plugins/quay/src/components/QuayRepository/tableHeading.tsx
plugins/quay/src/components/QuayTagDetails/component.tsx
plugins/quay/src/lib/utils.data.ts
plugins/quay/src/lib/utils.test.ts
plugins/quay/src/lib/utils.ts
plugins/quay/src/types.ts

- Fixed the ordering of vulnerabilities in tags list page based on severity.
- Fixed the sorting of vulnerabilities in vulnerabilities list page based on severity.
https://github.com/janus-idp/backstage-plugins/assets/6041994/c77dd566-5691-4101-92c5-3ba5f02dca24
https://github.com/janus-idp/backstage-plugins/assets/6041994/1b6f4be1-1234-4665-b580-0532d76e3269
https://github.com/janus-idp/backstage-plugins/assets/6041994/d58a7911-585a-4b73-a792-62d300344bce

fix(quay): fix sorting and ordering of vulneribilities based on severity

---

plugins/openshift-image-registry/README.md
plugins/openshift-image-registry/dev/index.tsx
plugins/openshift-image-registry/dev/namespaces.json
plugins/openshift-image-registry/dev/openshift-imagestreams.json
plugins/openshift-image-registry/dev/openshift-imagestreamtags.json
plugins/openshift-image-registry/src/api/index.ts
plugins/openshift-image-registry/src/components/OcirImages/OcirImageSidebar.tsx
plugins/openshift-image-registry/src/components/OcirImages/OcirImagesCard.tsx
plugins/openshift-image-registry/src/components/OcirImages/OcirImagesCards.tsx

Fix #596: Cleanup [3 small code smells](https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fopenshift-image-registry) reported by sonarcloud:
* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fopenshift-image-registry%2Fsrc%2Fcomponents%2FOcirImages%2FOcirImagesCard.tsx
* Used the tag as key since duplicates should happen because each tag refers to a resource name
* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fopenshift-image-registry%2Fsrc%2Fcomponents%2FOcirImages%2FOcirImagesCards.tsx
* Cleanuped the usage of `toggleDrawer` by using more explicit props to close the drawer.
* …

fix(openshift-image-registry): fix #596: Add mock data for test page and cleanup some small code smells

---

plugins/keycloak-backend/src/lib/config.ts
plugins/keycloak-backend/src/lib/read.test.ts
plugins/keycloak-backend/src/lib/read.ts
plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts

Part of #583, this PR fix #591: Cleanup 4 code smells reported by sonarcloud:
* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fkeycloak-backend%2Fsrc%2Flib%2Fconfig.ts
* `readProviderConfigs` was to complex. Extracted the code that reads each config entry into `readProviderConfig`
* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fkeycloak-backend%2Fsrc%2Flib%2Fread.test.ts
* used `entity?.` instead of `entity!.` to solve the sonar issue. Added a "is defined" condition.
* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fkeycloak-backend%2Fsrc%2Fproviders
* replace the enforcing of the the clientId (with !), added an …

fix(keycloak): fix #591: Cleanup some small code smells in Keycloak plugin

---

plugins/web-terminal/src/components/NamespacePickerDialog/NamespacePickerDialog.tsx
plugins/web-terminal/src/components/TerminalComponent/TerminalComponent.test.tsx
plugins/web-terminal/src/components/TerminalComponent/TerminalComponent.tsx
plugins/web-terminal/src/components/TerminalComponent/static/xterm.css

Fix #598: Cleanup 7 code smells reported by sonarcloud:
* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fweb-terminal%2Fsrc%2Fcomponents%2FTerminalComponent%2FTerminalComponent.tsx
* Checked options in conditions instead of enforcing them with `!`
* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fweb-terminal%2Fsrc%2Fcomponents%2FTerminalComponent%2FTerminalComponent.test.tsx
* switched (hihi) from a switch statement to an if statement because it has just one case
* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fweb-terminal%2Fsrc%2Fcomponents%2FTerminalComponent%2Fstatic%2Fxterm.css
* removed commented code

fix(web-terminal): fix #598: Cleanup some small code smells in the web-terminal plugin

---

OWNERS

Initial OWNERS file for Prow integrations.
This matches the list of the people with write access to this repo.

chore: add initial OWNERS file

---

plugins/rbac-backend/src/service/permission-policy.ts
plugins/rbac-backend/src/service/policies-rest-api.test.ts
plugins/rbac-backend/src/service/policies-rest-api.ts
plugins/rbac-backend/src/service/policies-validation.ts
yarn.lock

This PR fixes the issue of missing validation on the role name in the POST and PUT methods for roles. This also adds a couple of additional unit tests to get `policies-rest-api.ts` to 100% test coverage.
- Fixes #943 
1. Update app-config to include your user as admin
```yaml
permission:
enabled: true
rbac:
admin:
users:
- name: user:default/<USERNAME>
```
2. Log in using GitHub auth
3. Get token and export it in the terminal with `export token=...token...`
4. Use curl commands to test validation
wrong kind
`curl -X POST "http://localhost:7007/api/permission/roles" -d '{ "memberReferences": [ "user:default/test", "user:default/test2" ], "name": "x:default/test" }' -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v`
Missing name
`curl -X POST …

fix(rbac): fix role validation

---

plugins/regex-actions/README.md
plugins/regex-actions/src/actions/regex/replace.test.ts
plugins/regex-actions/src/actions/regex/replace.ts

Fix #594: Cleanup [3 small code smells](https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fregex-actions) reported by sonarcloud:
* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fregex-actions%2Fsrc%2Factions%2Fregex%2Freplace.ts
* removed the FIXME: comments since the common input format is YAML which doesn't support Sets. So imho it might be incorrect to expect a Set here.
* Updated the README with the right Type definition.
* fixed another warning that recommended to prefer startsWith and endsWith.
* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fregex-actions%2Fsrc%2Factions%2Fregex%2Freplace.test.ts
* fixed …

fix(regex-actions): fix #594: Cleanup some small code smells

---

plugins/rbac/src/components/RoleOverview/MembersCard.tsx
plugins/rbac/src/hooks/useRoles.ts

**Resolves:**
https://github.com/janus-idp/backstage-plugins/issues/1048
**Solution:**
Also checking for catalog entity read permission
**GIF:**
With no catalog-entity read permission
https://github.com/janus-idp/backstage-plugins/assets/22490998/7346598b-7ea0-475a-875d-875a05b018f2
With catalog-entity read permission
https://github.com/janus-idp/backstage-plugins/assets/22490998/4b943d00-d558-4105-b0ca-2c74f07d5f0f

fix(rbac): disable edit when the user is unauthorized to read the catalog-entity

---

plugins/quay/src/components/QuayRepository/QuayRepository.tsx
plugins/quay/src/components/QuayRepository/tableHeading.tsx
plugins/quay/src/components/QuayTagDetails/component.tsx
plugins/quay/src/hooks/quay.tsx
plugins/quay/src/types.ts

Allows sorting for all columns in the quay table (with the exception of `SECURITY_SCAN`)
Fixes sorting for vulnerability `SEVERITY` column in the tag details page
Fixes #1034
Fixes #1043

feat(quay): fix sorting in quay table and tag details

---

plugins/servicenow-actions/package.json

Tests for servicenow-actions were failing due to `Error: command --input not found`.
This was due to the wrong open API generator being executed. Instead of https://github.com/ferdikoomen/openapi-typescript-codegen the https://github.com/openapistack/openapicmd was started.

fix(servicenow): make sure that the correct openapi generator is executed

---

.github/workflows/push.yaml

Updates Push Workflow to use token owned by our Janus-IDP GitHub app 
We have Branch protection enabled that doesn't allow merging anything that doesn't have passing tests, this unfortunately means that this job is failing on the following error
```
[multi-semantic-release]: Error: Command failed with exit code 1: git push --tags https://github.com/janus-idp/backstage-plugins HEAD:main
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: 3 of 3 required status checks are expected.     
```
I've added an exception to allow the Janus-idp app to push without checks.

chore: use janus-idp GH App in push workflow

---

app-config.yaml

The `app-config.yaml` file was found to be invalid.
To address this issue and ensure consistency with [backstage-showcase](https://github.com/janus-idp/backstage-showcase/blob/main/app-config.yaml#L139), the `scaffolder` property has been set to an empty object.

fix(app-config): invalid app-config.yaml

---

plugins/rbac/README.md

Resolves:
https://issues.redhat.com/browse/RHIDP-1011
Vanilla backstage users would need to set up Auth to be able to view the Administration menu in the UI

fix(rbac): update the rbac ui readme

---

.github/workflows/push.yaml

This should finally make possible for semantic-release to push tags even with branch protection enabled

chore(cd): fix semantic-release permission issues

---

plugins/notifications-backend/README.md
plugins/notifications-backend/config.d.ts
plugins/notifications-backend/package.json
plugins/notifications-backend/src/dynamic/alpha.ts
plugins/notifications-backend/src/dynamic/index.ts
plugins/notifications-backend/src/index.ts
plugins/notifications-backend/src/service/auth.ts
plugins/notifications-backend/src/service/router.ts
plugins/notifications-backend/src/service/types.ts
plugins/notifications/README.md
plugins/notifications/app-config.janus-idp.yaml
plugins/notifications/package.json
plugins/notifications/src/index.ts

Fixes [FLPATH-877](https://issues.redhat.com//browse/FLPATH-877)

feat(notifications): turn plugins into dynamic ones

---

plugins/orchestrator/README.md

Addresses:
- https://issues.redhat.com/browse/FLPATH-827

docs(orchestrator): adds a section about deploying as a dynamic plugins

---

plugins/rbac/src/components/CreateRole/PermissionPoliciesForm.tsx
plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx

Fixes: https://github.com/janus-idp/backstage-plugins/issues/1068
New implementation:
Based on UX input this PR now disables selected permissions.
https://github.com/janus-idp/backstage-plugins/assets/20724543/0b958264-9d70-437d-8e37-035cd97244a0
Old implementation:
This PR adds validations to show field level error for permission fields that are not unique for the same plugin.
https://github.com/janus-idp/backstage-plugins/assets/20724543/a00538a8-a3a6-468b-9ad5-a9f8d7d9d9c3

feat(rbac): disable selected permissions

---

plugins/orchestrator/src/components/WorkflowInstancePage.tsx
plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx
plugins/orchestrator/src/hooks/usePolling.test.ts
plugins/orchestrator/src/hooks/usePolling.ts

[clicking on ASSESSED BY link in Workflow instance page doesn't refresh the page
](https://issues.redhat.com/browse/FLPATH-945
)

fix(orchestrator): resolve bug in workflow instance page assessed by link

---

plugins/tekton/src/components/PipelineRunList/PipelineRunRow.tsx
plugins/tekton/src/components/pipeline-topology/PipelineLayout.tsx
plugins/tekton/src/components/pipeline-topology/PipelineVisualizationView.tsx

This tekton plugin update fixes #962 and probably #922 by using the full width for the pipeline visualization, as defined in the [figma design here](https://www.figma.com/file/ydwdsmUS1PzdvMwe975u0G/Component-CI-tab-improvements?type=design&node-id=150%3A110&mode=design&t=KGzSpg5Kq5F5NOgt-1).
Before:
https://github.com/janus-idp/backstage-plugins/assets/139310/97e24dd6-f495-4448-827a-ee409a2d0a0e
After:
https://github.com/janus-idp/backstage-plugins/assets/139310/e9eca171-fd13-4f91-8623-545ff0f243a4

fix(tekton): fix #922 and #962 by using full width for pipeline visualization

---

plugins/dynamic-plugins-info/.eslintrc.js
plugins/dynamic-plugins-info/CONTRIBUTING.md
plugins/dynamic-plugins-info/README.md
plugins/dynamic-plugins-info/app-config.janus-idp.yaml
plugins/dynamic-plugins-info/dev/index.tsx
plugins/dynamic-plugins-info/package.json
plugins/dynamic-plugins-info/src/api/DynamicPluginsInfoClient.ts
plugins/dynamic-plugins-info/src/api/types.ts
plugins/dynamic-plugins-info/src/components/DynamicPluginsInfoContent/DynamicPluginsInfoContent.tsx
plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.tsx
plugins/dynamic-plugins-info/src/index.ts
plugins/dynamic-plugins-info/src/plugin.test.ts
plugins/dynamic-plugins-info/src/plugin.ts
plugins/dynamic-plugins-info/src/routes.ts
plugins/dynamic-plugins-info/src/setupTests.ts
plugins/dynamic-plugins-info/tsconfig.json
plugins/dynamic-plugins-info/turbo.json
yarn.lock

This change adds a dynamic-plugins-info plugin which is a frontend for the [dynamic-plugins-info-backend](https://github.com/janus-idp/backstage-showcase/tree/main/plugins/dynamic-plugins-info-backend) plugin that is part of the Janus IDP [backstage-showcase](https://github.com/janus-idp/backstage-showcase) instance.  The plugin implements a table view of the plugin data and includes client-side filtering, sorting and pagination. A dev mode is available with some test data to populate the table. This initial implementation only covers installing the plugin dynamically.
Part pf [RHIDP-980](https://issues.redhat.com/browse/RHIDP-980)
Here's an example of the plugin running in dev mode:
And here's an example of the plugin running in backstage-showcase with [this PR in …

feat(plugins): ui for dynamic-plugins-info-backend

---

plugins/shared-react/src/types/pipeline/computedStatus.ts
plugins/shared-react/src/utils/pipeline/pipeline.test.ts
plugins/tekton/src/components/PipelineRunList/PipelineRunList.test.tsx
plugins/tekton/src/components/PipelineRunList/PipelineRunList.tsx
plugins/tekton/src/components/PipelineRunList/PipelineRunListSearchBar.test.tsx
plugins/tekton/src/components/PipelineRunList/PipelineRunListSearchBar.tsx
plugins/tekton/src/components/common/ClusterSelector.tsx
plugins/tekton/src/components/common/StatusSelector.tsx
plugins/tekton/src/components/pipeline-topology/PipelineVisualizationView.test.tsx
plugins/tekton/src/hooks/TektonResourcesContext.ts
plugins/tekton/src/hooks/useTektonObjectsResponse.ts
plugins/tekton/src/types/types.ts
plugins/tekton/src/utils/pipeline-step-utils.test.ts

Update the tekton plugin to fix #947 aka [](https://issues.redhat.com/browse/RHIDP-977):
1. Reset page to page 0 when the cluster, state filter or text-field changed
2. Calculate and set `filteredPipelineRuns` in a useMemo when some of the user states change, instead of having two states that are set when the search field changes.
3. Removed the `native` prop from the dropdowns so that the dropdowns are rendered with Material UI.
Before:
https://github.com/janus-idp/backstage-plugins/assets/139310/d1d717dd-7b52-49ee-8e2d-3439c8c97ba1
After:
https://github.com/janus-idp/backstage-plugins/assets/139310/31a6900e-5a0c-41a1-98ea-320d3e971308

fix(tekton): fix #947: Reset pagination when changing any filter

---

plugins/dynamic-plugins-info/package.json

This commit ensures the plugin configuration is also exported when the package is released.
@invincibleJai FYI missed this bit in the initial spike of this component.

chore(dynamic-plugins-info): export config

---

plugins/tekton/src/__fixtures__/1-pipelinesData.ts
plugins/tekton/src/__fixtures__/taskRunData.ts
plugins/tekton/src/components/PipelineRunList/PipelineRunRowActions.tsx
plugins/tekton/src/components/PipelineRunList/__tests__/PipelineRunRowActions.test.tsx
plugins/tekton/src/hooks/useAllWatchResources.test.ts
plugins/tekton/src/utils/taskRun-utils.test.ts

**Fixes:**
https://github.com/janus-idp/backstage-plugins/issues/1151
This PR contains the following changes:
1. Logs modal will be opened only for internal sbom task.
2. Add unit tests to cover pipelinerun  actions component.
On clicking on View SBOM action, the users is properly redirected to external-link when the task contains external-link annotation, but the internal sbom logs dialog is also opened at the same time. Logs modal should be opened only when this external-link annotation is not set.
**Before:**
https://github.com/janus-idp/backstage-plugins/assets/9964343/1cc83a4f-8a10-4f3f-aabb-7f059197f728
**After:**
https://github.com/janus-idp/backstage-plugins/assets/9964343/8f9df0b7-bada-4125-bc54-0da7eb210b74
1. After checking out this PR, run …

fix(tekton): external sbom view action should not open logs modal

---

plugins/3scale-backend/app-config.janus-idp.yaml

JIRA: https://issues.redhat.com/browse/RHIDP-1030
Upstream issue: https://github.com/janus-idp/backstage-showcase/issues/849
In fact environment variables starting with digits are not recommended in POSIX:
> Environment variable names used by the utilities in the Shell and Utilities volume of POSIX.1-2017 consist solely of uppercase letters, digits, and the <underscore> ( '_' ) from the characters defined in [Portable Character Set](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap06.html#tagtcjh_3) and **do not begin with a digit**
Hence I am adding an underscore ("_") as initial character. 
Notice I didn't find it documented, hence I am not changing documentation. Let me know if I should document this.
Thanks!
[1] …

fix(3scale): modify 3scale environment variables

---

plugins/ocm-backend/src/alpha.ts
plugins/orchestrator-backend/src/alpha.ts

When embedding alpha modules, the embedded module dependencies were not hoisted to the embedding module.
This PR fixes this issue.

fix: add missing alpha  dynamic plugin entry points

---

packages/cli/src/commands/export-dynamic-plugin/backend.ts
packages/cli/src/lib/builder/embedPlugin.ts

When embedding alpha modules, the embedded module dependencies were not hoisted to the embedding module.
This PR fixes this issue.

fix(cli): embedded alpha module dependencies not hoisted.

---

plugins/rbac-backend/package.json
plugins/rbac-backend/src/index.ts
plugins/rbac-backend/src/plugin.ts
plugins/rbac-backend/src/service/plugin-endpoints.ts
plugins/rbac-backend/src/service/policies-rest-api.ts
plugins/rbac-backend/src/service/policy-builder.ts
plugins/rbac-node/.eslintrc.js
plugins/rbac-node/README.md
plugins/rbac-node/package.json
plugins/rbac-node/src/extensions.ts
plugins/rbac-node/src/index.ts
plugins/rbac-node/src/setupTests.ts
plugins/rbac-node/src/types/index.ts
plugins/rbac-node/src/types/types.ts
plugins/rbac-node/tsconfig.json
plugins/rbac-node/turbo.json

Add support for the new backend system to the rbac backend plugin.
This fixes issue #1063

feat: add support for the new backend system to the `rbac-backend` plugin

---

plugins/rbac/src/components/CreateRole/CreateRolePage.tsx
plugins/rbac/src/components/CreateRole/EditRolePage.tsx
plugins/rbac/src/components/CreateRole/RoleForm.tsx
plugins/rbac/src/components/EditRole.tsx
plugins/rbac/src/components/RbacPage.tsx
plugins/rbac/src/components/RoleOverview/MembersCard.tsx
plugins/rbac/src/components/RoleOverview/PermissionsCard.tsx
plugins/rbac/src/components/RoleOverview/RoleOverviewPage.tsx
plugins/rbac/src/components/Router.tsx

This change updates the links between components from absolute links to relative links to better support being run from a different route root. This commit also adds a property to help better integrate this plugin into the backstage-showcase Administration page while still retaining it's existing functionality.  Some examples:
This fixes #1165 
Also note that this needs https://github.com/janus-idp/backstage-showcase/pull/955 to fully test this locally.

feat(rbac): use relative links

---

plugins/kiali/src/pages/Kiali/Header/NamespaceSelector.tsx

When you remove a namespace in selector, this option is removed from items. The behaviour should be keep the namespace unselected.
[before_fix.webm](https://github.com/janus-idp/backstage-plugins/assets/3019213/f4d70167-f99b-43fb-8b30-2e768ff89cac)
[after_fix.webm](https://github.com/janus-idp/backstage-plugins/assets/3019213/7fad824e-6393-4709-a3c4-b9aae4c51a86)

fix(kiali): namespaceSelector is removing options

---

plugins/orchestrator/src/dataFormatters/WorkflowOverviewFormatter.test.ts
plugins/orchestrator/src/dataFormatters/WorkflowOverviewFormatter.ts

[FLPATH-968](https://issues.redhat.com/browse/FLPATH-968)
fixed average duration field in workflows table to be the same as duration field in workflow runs

fix(orchestrator): resolve inconsistency with workflow run average duration format 

---

plugins/topology/src/components/Topology/TopologyViewWorkloadComponent.test.tsx
plugins/topology/src/components/Topology/TopologyViewWorkloadComponent.tsx
plugins/topology/src/components/Topology/TopologyWorkloadView.test.tsx
yarn.lock

Initial loading of the topology view can, in instances, fail to layout the nodes centered on the view (in particular, in the [Janus Showcase application](https://github.com/janus-idp/backstage-showcase.git ).
The fix is to wait until the graph surface area has been initialized and sized so that the graph component has dimensions. This allows the layout of the nodes to be set based on the current graph size and centered on the graph surface.
/cc @invincibleJai

fix(topology): fix to layout nodes correctly on first load

---

plugins/rbac-backend/README.md
plugins/rbac-backend/config.d.ts
plugins/rbac-backend/src/__fixtures__/data/invalid-csv/duplicate-policies-actions.csv
plugins/rbac-backend/src/__fixtures__/data/invalid-csv/duplicate-policy.csv
plugins/rbac-backend/src/__fixtures__/data/invalid-csv/entityref-policy.csv
plugins/rbac-backend/src/__fixtures__/data/invalid-csv/permission-policy.csv
plugins/rbac-backend/src/__fixtures__/data/invalid-csv/role-entityref-policy.csv
plugins/rbac-backend/src/__fixtures__/data/valid-csv/rbac-policy.csv
plugins/rbac-backend/src/__fixtures__/data/valid-csv/updated-rbac-policy.csv
plugins/rbac-backend/src/file-permissions/csv.test.ts
plugins/rbac-backend/src/file-permissions/csv.ts
plugins/rbac-backend/src/helper.ts
plugins/rbac-backend/src/service/permission-policy.test.ts
plugins/rbac-backend/src/service/permission-policy.ts
plugins/rbac-backend/src/service/policies-rest-api.test.ts
plugins/rbac-backend/src/service/policies-validation.ts
plugins/rbac-backend/src/service/policy-builder.ts
plugins/rbac-backend/src/service/test/data/rbac-policy.csv

This PR introduces new functionality to facilitate the reloading of permission policies sourced from the CSV file. The issue at hand was the necessity of restarting the server every time there was an update to the permission policies in the CSV, which was quite inconvenient. The added feature enables the dynamic reloading of permission policies and roles directly from the CSV.
It leverages information provided by the permission framework (entity reference, permission, policy). This approach allows us to focus solely on roles associated with the entity reference in the CSV, subsequently retrieving permissions linked to that role, matching the given permission and policy. The aim is to enhance efficiency by selectively reloading relevant portions of the file, rather than the entire dataset. …

fix(rbac): csv updates no longer require server restarts

---

plugins/orchestrator-backend/src/service/router.ts

Closes https://github.com/janus-idp/backstage-plugins/issues/1167

fix(orchestrator): filter out `null` values from action input

---

plugins/rbac-backend/src/service/plugin-endpoint.test.ts
plugins/rbac-backend/src/service/plugin-endpoints.ts

- display resource typed permissions by name too. 
- add more tests to improve coverage for plugin-endpoints.ts
https://issues.redhat.com/browse/RHIDP-1290

fix(rbac): display resource typed permissions by name too

---

plugins/rbac-backend/README.md
plugins/rbac-backend/config.d.ts
plugins/rbac-backend/src/service/permission-policy.test.ts
plugins/rbac-backend/src/service/permission-policy.ts

Adds a 'super user' configuration value that grants users allow all access to their backstage instance. In this approach, I settled for creating an additional config value to capture the individuals who would be labeled super users within a backstage instance. This way we still preserve the integrity of the rbac admin role and have the ability to have users that will allow all priveliges.
Also, updated the documentation with the additional config value. Added an additional test for reloading the CSV file that was missed previously. This test checks if a user that originally was granted an allow for a particular permission, looses said allow result when removed from the csv file. 
- Fixes: #999

fix(rbac): allow for super users to have allow all access

---

.github/workflows/pr-playwright.yaml
.gitignore
CONTRIBUTING.md
plugins/quay/dev/index.tsx
plugins/quay/package.json
plugins/quay/playwright.config.ts
plugins/quay/tests/quay.spec.ts
yarn.lock

Adds a playwright based test suite for quay plugin. This is to help with automation for features contributed by RHTAP.
Also adds a github action that runs said automation for any plugin that would have it as PR check.

test(quay): add first playwright tests

---

plugins/dynamic-plugins-info/dev/index.tsx
plugins/dynamic-plugins-info/src/__fixtures__/listLoadedPluginsResult.ts
plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx

This change adds a test for the dynamic plugins info table component to cover the client-side filtering, sorting and pagination that this component implements.  The same data is used for the plugin's dev mode and the tests.
For [RHIDP-1005](https://issues.redhat.com/browse/RHIDP-1005)

chore(dynamic-plugins-info): add test

---

plugins/rbac-backend/src/file-permissions/csv.test.ts
plugins/rbac-backend/src/role-manager/ancestor-search-memo.ts
plugins/rbac-backend/src/role-manager/role-list.ts
plugins/rbac-backend/src/role-manager/role-manager.test.ts
plugins/rbac-backend/src/role-manager/role-manager.ts
plugins/rbac-backend/src/service/permission-policy.test.ts
plugins/rbac-backend/src/service/policy-builder.ts

This PR aims to reduce the number of times we make a call to the catalog while building the group hierarchy graph for a user. In our original approach, we would find that for each call to the authorize endpoint, we would retrieve the number of roles that the RBAC plugin is aware of, multiplied by the hierarchy level of the user. So, in the case of 52 roles and a user nested under four groups, we would end up with 52 * 4 = 208 catalog calls.
In the update, I chose to make a single call to retrieve all of the groups at once and then build the graph based on the retrieved information. This now means that for every authorize endpoint, we only make a call to the catalog the same number of times as the number of roles that the RBAC plugin is aware of.
Another aim of this PR is to separate some …

fix(rbac): reduce the catalog calls when build graph

---

plugins/rbac-backend/migrations/20231212224526_migrations.js
plugins/rbac-backend/migrations/20231221113214_migrations.js
plugins/rbac-backend/migrations/20240201144429_migrations.js
plugins/rbac-backend/src/database/policy-metadata-storage.test.ts
plugins/rbac-backend/src/database/role-metadata.test.ts
plugins/rbac-backend/src/database/role-metadata.ts
plugins/rbac-backend/src/file-permissions/csv.ts
plugins/rbac-backend/src/helper.test.ts
plugins/rbac-backend/src/helper.ts
plugins/rbac-backend/src/service/enforcer-delegate.ts
plugins/rbac-backend/src/service/enforcer.delegate.test.ts
plugins/rbac-backend/src/service/permission-policy.ts
plugins/rbac-backend/src/service/policies-rest-api.test.ts
plugins/rbac-backend/src/service/policies-rest-api.ts
plugins/rbac-common/src/types.ts

https://github.com/janus-idp/backstage-showcase/issues/898

feat(rbac): backend part - store role description to the database 

---

plugins/orchestrator-backend/src/service/router.ts
plugins/orchestrator-common/src/auto-generated/api/definition.ts
plugins/orchestrator-common/src/auto-generated/api/models/schema.ts
plugins/orchestrator-common/src/auto-generated/docs/index.adoc/index.adoc
plugins/orchestrator-common/src/openapi/openapi.yaml

By mistake the PR that added the new openapi v2 endpoints broke the `/workflows/:workflowId` v1 route.
In addition, the v2 endpoint wasn't properly added due to a wrong rebase.

fix(orchestrator): implementation of getWorkflowById (v2)

---

plugins/kubernetes-actions/README.md
plugins/kubernetes-actions/examples/templates/01-kubernetes-template.yaml
plugins/kubernetes-actions/src/actions/createKubernetesNamespace.test.ts
plugins/kubernetes-actions/src/actions/createKubernetesNamespace.ts

- Add support for adding labels while creating namespace resource in kubernetes action.
- Updates the example template to support labels.
https://github.com/janus-idp/backstage-plugins/assets/6041994/614a1459-05ee-4dfa-95fc-446de947676d

fix(kubernetes-actions): support adding labels while creating namespace

---

plugins/rbac/src/components/CreateRole/AddMembersForm.tsx
plugins/rbac/src/components/CreateRole/PermissionPoliciesForm.tsx
plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
plugins/rbac/src/components/CreateRole/PoliciesCheckboxGroup.tsx
plugins/rbac/src/components/CreateRole/ReviewStep.tsx
plugins/rbac/src/components/RolesList/RolesListToolbar.tsx
plugins/rbac/src/components/SnackbarAlert.tsx

**Fixes:** [RHIDP-1249](https://issues.redhat.com//browse/RHIDP-1249)
The RBAC plugin uses Material UI v4 and v5 components together. To solve some issues with the dark theme I aligned/downgraded the code to use v4. I ignored the imports that just import icons.
**Before:**
https://github.com/janus-idp/backstage-plugins/assets/139310/c9860b3a-8661-4879-b108-1dc4e0b105cc
**With this PR:**
https://github.com/janus-idp/backstage-plugins/assets/139310/738e5882-7339-4e1f-87bd-2dee32d36eb0

fix(rbac): fix labels and dropdowns in dark theme by aligning/downgrading components to MUI v4

---

plugins/orchestrator-backend/src/service/DataIndexService.ts
plugins/orchestrator-backend/src/service/Helper.ts
plugins/orchestrator-backend/src/service/SonataFlowService.ts
plugins/orchestrator-backend/src/service/api/v1.ts
plugins/orchestrator-backend/src/service/router.ts

- Some places in the services assume the response array is non-empty or the response object is not undefined, which could not be the case. So I've changed these parts to a more defensive code.
- When executing a workflow, I've added a call to fetch the instance details just to make sure the data is available. 
Please note that none of these improvements is changing the current behavior.

fix(orchestrator): improvements to backend services

---

plugins/orchestrator-backend/dist-dynamic/package.json
plugins/orchestrator-backend/package.json
plugins/orchestrator-backend/src/service/router.ts

During backstage startup there are warnings like:
`unknown format "date-time" ignored in schema at path "#/oneOf/0/properties/ended"`
due to a bug in [OpenAPIBackend issue](https://github.com/openapistack/openapi-backend/issues/280).
Resolves [FLPATH-1045](https://issues.redhat.com/browse/FLPATH-1045)
Based on Yaron Dayagi <ydayagi@redhat.com> [work](https://github.com/janus-idp/backstage-plugins/blob/903c7f37a1cf138ac96ef3f631f951866c2014fa/plugins/notifications-backend/src/service/router.ts#L45-L52) in notification plugin.

fix(orchestrator): warn "unknown format X ignored in schema at path Y"

---

plugins/rbac/src/components/CreateRole/AddMembersForm.tsx

For [RHIDP-1395](https://issues.redhat.com/browse/RHIDP-1395): [RBAC] Unable to clear Autocomplete text field on the add members section in the role form.
https://github.com/janus-idp/backstage-plugins/assets/26255262/5d0322ce-28b9-40e3-ac1d-30372f792ef7

fix(rbac): fixed autocomplete text input behavior on clear

---

plugins/orchestrator-common/src/auto-generated/api/definition.ts
plugins/orchestrator-common/src/auto-generated/api/models/schema.ts
plugins/orchestrator-common/src/auto-generated/docs/index.adoc/index.adoc
plugins/orchestrator-common/src/openapi/openapi.yaml

The values of date-time fields don't refect the RFC format. Use only string.
Fix [FLPATH-1051](https://issues.redhat.com/browse/FLPATH-1051)

fix(orchestrator): remove date-time format from spec

---

plugins/orchestrator-backend/src/service/router.ts

The `workflowId` param isn't parsed properly.
The endpoint always returns 500 error.
Fix [FLPATH-1052](https://issues.redhat.com/browse/FLPATH-1052)

fix(orchestrator): workflowId parameter wrongly parsed in getWorkflowOverviewById (v2)

---

plugins/orchestrator-backend/src/service/DataIndexService.ts
plugins/orchestrator-backend/src/service/SonataFlowService.ts
plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.ts
plugins/orchestrator-common/src/auto-generated/api/models/schema.ts
plugins/orchestrator-common/src/models.ts
plugins/orchestrator/src/components/WorkflowInstancePage.tsx
plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
plugins/orchestrator/src/components/WorkflowInstanceStatusIndicator.tsx
plugins/orchestrator/src/components/WorkflowProgressNode.tsx
plugins/orchestrator/src/components/WorkflowProgressNodeModel.ts
plugins/orchestrator/src/components/WorkflowRunDetail.ts
plugins/orchestrator/src/hooks/useWorkflowInstanceStatusColors.ts

https://issues.redhat.com/browse/FLPATH-1035
- Add debug logs for SonataFlow responses
- Remove unused `SonataFlow#fetchWorkflows` method
- Handle null values for `start` and `state` properties (ProcessInstance)
- Handle `PENDING` state (ProcessInstance)

fix(orchestrator): handle nullable start/state properties of process instance

---

plugins/rbac-backend/src/service/plugin-endpoint.test.ts
plugins/rbac-backend/src/service/plugin-endpoints.ts
plugins/rbac-backend/src/service/policies-rest-api.ts

Log errors when requesting rbac-backend permission metadata instead of propagating them. Ignore errors caused by non-JSON responses during permission metadata retrieval.
Fixes: https://issues.redhat.com/browse/RHIDP-1453
Workaround for: https://issues.redhat.com/browse/RHIDP-1456

fix(rbac): improve error handling in retrieving permission metadata.

---

plugins/rbac-backend/README.md
plugins/rbac-backend/docs/apis.md
plugins/rbac-backend/docs/permissions.md

Updates the documentation for the RBAC plugin. We have had a number of updates to the plugin and this PR should help to get the documentation caught back up to these updates. 
Added the ability to create and update multiple permission policies, added the `metadata.description` parameter, moved some steps around in the README for a better step by step guide, and minor formatting to the permission policies guide.

docs(rbac): update to the rbac documentation

---

plugins/orchestrator-backend/src/service/router.ts
plugins/orchestrator-common/package.json
plugins/orchestrator-common/scripts/openapi.sh
plugins/orchestrator-common/src/auto-generated/api/definition.ts
plugins/orchestrator-common/src/auto-generated/api/models/schema.ts
plugins/orchestrator-common/src/auto-generated/docs/index.adoc/index.adoc
plugins/orchestrator-common/src/openapi/openapi.yaml
plugins/orchestrator-common/src/openapi/types.ts

https://issues.redhat.com/browse/FLPATH-1024
* Apply Prettier to auto-generated OpenAPI files during the generation phase to ensure consistent formatting.
* Refactor all v2 endpoint 500 responses to utilize the `ErrorResponse` object, enhancing readability and maintainability by replacing text/plain responses.

fix(orchestrator): refactor 500 response to use ErrorResponse object

---

plugins/notifications/src/components/NotificationsTable/NotificationsTable.tsx

The filtering used to be done twice - by both the BE and the FE. Since we stopped using a regular table, the FE filtering did not find match and so filtered-out all the messages.
With this fix, just the BE performs the filter.
Fixes: [FLPATH-1067](https://issues.redhat.com//browse/FLPATH-1067)

fix: text filtering in Notifications

---

plugins/orchestrator/src/components/WorkflowInstancePage.tsx

Jira: [https://issues.redhat.com/browse/FLPATH-1060](https://issues.redhat.com/browse/FLPATH-1060)
When run workflow the `state` field of the `instance` object could be `null`, but actually it should not be. We walk around it in this fix.

fix(orchestrator): walk around the state field is empty issue when fetch instance

---

plugins/orchestrator-backend/src/service/Helper.test.ts
plugins/orchestrator-backend/src/service/Helper.ts
plugins/orchestrator-backend/src/service/api/v1.ts

Increasing from `5` to `10` for slow envs.
Also added some tests and renamed a few things.

fix(orchestrator): increase the number of attempts to fetch the instance after execution

---

plugins/rbac-backend/src/file-permissions/csv.test.ts
plugins/rbac-backend/src/service/permission-policy.test.ts
plugins/rbac-backend/src/service/policies-validation.ts

Fixes the duplication warning being thrown unnecessarily whenever there is a policy present in the CSV file and the database. This issue was happening because we were not checking the origin of the duplication warning whenever we were loading in the app-config at the start of an instance. The updates to this PR aims to fix it so that we check the source also before throwing the warning. 
Updated the tests as well to match the duplication fix.

fix(rbac): check source before throwing duplicate warning

---

plugins/orchestrator-backend/src/helpers/queryBuilder.ts
plugins/orchestrator-backend/src/pagination.test.ts
plugins/orchestrator-backend/src/queryBuilder.test.ts
plugins/orchestrator-backend/src/service/DataIndexService.ts
plugins/orchestrator-backend/src/service/SonataFlowService.ts
plugins/orchestrator-backend/src/service/api/v1.ts
plugins/orchestrator-backend/src/service/api/v2.test.ts
plugins/orchestrator-backend/src/service/api/v2.ts
plugins/orchestrator-backend/src/service/constants.ts
plugins/orchestrator-backend/src/service/router.ts
plugins/orchestrator-backend/src/types/pagination.ts
plugins/orchestrator-common/src/auto-generated/api/definition.ts
plugins/orchestrator-common/src/auto-generated/api/models/schema.ts
plugins/orchestrator-common/src/auto-generated/docs/index.adoc/index.adoc
plugins/orchestrator-common/src/openapi/openapi.yaml
plugins/orchestrator-common/src/openapi/types.ts

JIRA: [FLPATH-749](https://issues.redhat.com/browse/FLPATH-749)
Use query parameters in the GET request to identify the following options:
- pageSize
- page
- orderBy
- orderDirection
E.g.: http://localhost:7007/api/orchestrator/v2/workflows/instances?pageSize=10&page=2&orderBy=start&orderDirection=DESC
Response structure for the /v2/workflows/instances & /v2/workflows/overview should be as below:
```
{
items: [],
paginationInfo: {
pageSize: 10,
page: 2,
totalCount: 50
}
}
```

feat(orchestrator): support pagination for /instances and /overview

---

plugins/orchestrator/src/components/WorkflowsTable.tsx
plugins/orchestrator/src/components/ui/OverrideBackstageTable.tsx

root caused to [override of background-color in MuiDisabled](https://github.com/janus-idp/backstage-showcase/blob/main/packages/app/src/themes/componentOverrides.ts#L59)
This override is meant for a disabled tab, but it propogates down to any element under a tab that has the MuiDisabled class
I searched in material UI for a way to localise the disabled override but couldn't find a better solution
The solution in this PR adds a custom class to a div around the table that overrides MuiDisabled class backgroundColor

fix(orchestraotr): resolved grey background appears in actions column in workflows table

---

plugins/ocm-backend/src/helpers/parser.test.ts
plugins/ocm-backend/src/helpers/parser.ts

Error:
When a ManagerCluster API response lacks the `status.clusterClaims` then the error `Cannot read properties of undefined (reading 'find')` is displayed on the UI.
Fix: Just make sure that `clusterClaims` is checked before calling `find` ;

fix(ocm): prevent error when ManagedCluster.status doesn't contain a 'clusterClaims' field

---

README.md

Added brief information about dynamic plugins installation to the README.md, but linking the main Dynamic Plugins docs to avoid information duplication. The README.md instruction is just to let users know about this possibility and direct them to a more complete document.

docs:  Add dynamic plugin setup/installation instruction for the janus-idp plugins

---

plugins/rbac-backend/src/file-permissions/csv.test.ts
plugins/rbac-backend/src/role-manager/ancestor-search-memo.test.ts
plugins/rbac-backend/src/role-manager/ancestor-search-memo.ts
plugins/rbac-backend/src/role-manager/role-list.test.ts
plugins/rbac-backend/src/role-manager/role-manager.test.ts
plugins/rbac-backend/src/role-manager/role-manager.ts
plugins/rbac-backend/src/service/enforcer-delegate.test.ts
plugins/rbac-backend/src/service/permission-policy.test.ts
plugins/rbac-backend/src/service/policy-builder.ts

As part of the work to increase the performance of the RBAC backend plugin, this PR further reduces the number of catalog api calls to zero by instead attempting to query the catalog database table 'relations'. This relations table contains all of the relations between two entities within the catalog. We can query this table to retrieve relations of 'memberOf' for a specified user and 'childOf' for groups that have parents. We can then begin to build the graph using this minimum amount of information.
Went in and fixed the broken tests to now work. Also, fixed an issue with the logger mock within the `role-manager.test.ts` not being reset after each test. Now, the correct log statements will show up ensuring that we have accurate tests. Also, renamed `enforcer.delegate.test.ts` to …

feat(rbac): query the catalog database when building graph

---

plugins/rbac-backend/src/helper.test.ts
plugins/rbac-backend/src/helper.ts
plugins/rbac-backend/src/service/enforcer-delegate.ts
plugins/rbac-backend/src/service/permission-policy.test.ts
plugins/rbac-backend/src/service/permission-policy.ts
plugins/rbac-backend/src/service/policies-rest-api.test.ts

1) remove admin metadata, when all admins removed from config
2) remove role metadata, when it really unused
3) change log message, when admin or super-admin list is absent
https://issues.redhat.com/browse/RHIDP-1506

fix(rbac): remove admin metadata, when all admins removed from config

---

plugins/analytics-module-matomo/src/api/Matomo.ts

Fixes #1294
The analytics events are not triggered on page load, using `window._paq` fixes the issue.

fix(matomo-analytics): event trigger on load

---

plugins/rbac-backend/src/service/plugin-endpoint.test.ts
plugins/rbac-backend/src/service/plugin-endpoints.ts
plugins/rbac-backend/src/service/policies-rest-api.ts

Passes a token to `readUrl` whenever we are looking up the permissions for a particular plugin using the `well-known` endpoint. Passing this token is important because if a user decides to implement the custom auth middleware mentioned within this documentation, then the `readUrl` will return with a 401 error leading to a 500 for the endpoints `/plugins/policies` and `/plugins/condition-rules`
- Fixes #1248

fix(rbac): pass token to readUrl for well-known permission endpoint

---

plugins/tekton/src/components/PipelineRunList/PipelineRunVulnerabilities.tsx

**Fixes:**
https://github.com/janus-idp/backstage-plugins/issues/1346
Hovering on low vulnerability count should open a tooltip that reads "Low"
Before:
https://github.com/janus-idp/backstage-plugins/assets/9964343/a58e4ffb-b075-4e37-a6a6-e17028a54270
After:
https://github.com/janus-idp/backstage-plugins/assets/9964343/53723995-dfed-462a-9424-8ef3a426b175
**steps to test this bug**
- Start the tekton plugin in dev mode
- Hover on the last count in the vulnerabilities column

fix(tekton): fix low vulnerability tooltip text

---

plugins/orchestrator-common/scripts/openapi.sh

Improve the openapi generation [script](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/orchestrator-common/scripts/openapi.sh#L5-L7) 
* use the `--yes` flag
so that the script doesn't need to prompt the user for the installation 
* fix a version to the packages that we are using
Solve [FLPATH-1072](https://issues.redhat.com/browse/FLPATH-1072)

chore(orchestrator): set npx packages version for openapi generation

---

plugins/notifications-backend/src/service/handlers.test.ts
plugins/notifications-backend/src/service/handlers.ts

[FLPATH-1087](https://issues.redhat.com//browse/FLPATH-1087)
https://issues.redhat.com/browse/FLPATH-1087

feat(notifications): require users and groups to be of the form namespace/name

---

.github/dependabot.yml

Create dependabot.yml to work on / of the monorepo and do daily/weekly checks for yarn deps & GH actions

chore(deps): dependabot.yml to work on monorepo root and do daily/weekly checks for yarn deps & GH actions

---

package.json
plugins/rbac/.eslintignore
yarn.lock

For [RHIDP-1709](https://issues.redhat.com/browse/RHIDP-1709): [RBAC] fix yarn lint command in plugins/rbac
Changes:
1. Updated @typescript-eslint/typescript-estree version to support TypeScript version installed
2. Added `.eslintignore` file to avoid `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`
How to verify this change:
Go to plugins/rbac and run `yarn lint`. Observe that command gets executed with no error or warning.
```
➜  rbac git:(your-branch) ✗ yarn lint
yarn run v1.22.21
$ backstage-cli package lint
✨  Done in 3.08s.
```

fix(rbac): yarn lint command

---

plugins/argocd/.eslintrc.js
plugins/argocd/OWNERS
plugins/argocd/README.md
plugins/argocd/app-config.janus-idp.yaml
plugins/argocd/config.d.ts
plugins/argocd/dev/index.tsx
plugins/argocd/package.json
plugins/argocd/src/components/ExampleComponent/ExampleComponent.test.tsx
plugins/argocd/src/components/ExampleComponent/ExampleComponent.tsx
plugins/argocd/src/components/ExampleComponent/index.ts
plugins/argocd/src/components/ExampleFetchComponent/ExampleFetchComponent.test.tsx
plugins/argocd/src/components/ExampleFetchComponent/ExampleFetchComponent.tsx
plugins/argocd/src/components/ExampleFetchComponent/index.ts
plugins/argocd/src/index.ts
plugins/argocd/src/plugin.test.ts
plugins/argocd/src/plugin.ts
plugins/argocd/src/routes.ts
plugins/argocd/src/setupTests.ts
plugins/argocd/tsconfig.json
plugins/argocd/turbo.json

- Adds a new plugin for ArgoCD.
- Adds the dynamic plugin configuration.
- Adds the OWNER file.
- The plugin right now is an empty plugin with example component. We have a follow up story that will add environments view UI to the plugin.
- Tested the plugin on Backstage Showcase by loading it as a dynamic plugin.
https://github.com/janus-idp/backstage-plugins/assets/6041994/f6c83843-1e00-4a31-bf80-528dce366ad4

feat(argocd): create a new plugin for argocd

---

plugins/tekton/package.json
yarn.lock

**Fixes:**
https://github.com/janus-idp/backstage-plugins/issues/1355
Handles the invalid ACS inputs gracefully instead of crashing the UI. 
**Steps to reproduce:**
1. Create Tasks and Pipelinerun from this gist - https://gist.github.com/karthikjeeyar/c3c4bf69df5e035f5dd4115cbccd5bf4
2. Once the Pipelinerun is complete, click on the output action to view the report.
**Before**:
**After**:
cc: @rohitkrai03

fix(tekton): bump aonic-ui/pipelines package to fix acs table crashing issue

---

plugins/topology/src/__fixtures__/1-deployments.ts
plugins/topology/src/utils/resource-utils.ts

**Fixes:** 
https://issues.redhat.com/browse/RHTAPBUGS-1166
https://issues.redhat.com/browse/RHIDP-1693
**Description:** 
Adds check on service and routes to match the same namespace as workloads, if resources are fetched across namespaces
**Test Setup:**
Create two workloads with the same name in two different namespaces.
Before:
After:

fix(topology): adds check on service and routes to match same namespace as workloads

---

packages/backend/package.json
plugins/rbac/src/components/CreateRole/RoleForm.tsx
plugins/rbac/src/components/RoleOverview/RoleOverviewPage.tsx
plugins/rbac/src/components/RolesList/RolesList.tsx
plugins/rbac/src/hooks/useLocationToast.test.ts
plugins/rbac/src/hooks/useLocationToast.ts
plugins/rbac/tests/rbac.spec.ts

For [RHIDP-1362](https://issues.redhat.com/browse/RHIDP-1362)
e2e test updated: https://github.com/janus-idp/backstage-showcase/pull/1090
screen recording;
https://github.com/janus-idp/backstage-plugins/assets/26255262/d986aa30-ad44-445a-b7eb-07c841ee8f0f

fix(rbac): alert display issue after role creating/updating

---

plugins/quay/src/components/QuayRepository/QuayRepository.test.tsx
plugins/quay/src/components/QuayRepository/tableHeading.tsx

**Fixes:**
https://issues.redhat.com/browse/RHTAPBUGS-1184
Quay plugin intercepts queued vulnerability image scan as `Passed`. I have added queued status to convey the right status to the users.
**Before:**
**After:**
Push an image to quay.io and you can see it will be queued for scan, meanwhile go back to backstage quay plugin to see the new queued status there as well.

fix(quay): add queued status for tags waiting for scan

---

.github/workflows/push.yaml
package.json

chore: [RHIDP-1720](https://issues.redhat.com//browse/RHIDP-1720) allow semantic release from main and 1.1.x+ branches (but not 1.0.x)
N/A
N/A

chore: allow semantic release (RHIDP-1720) from main and 1.1.x+ branches (but not 1.0.x)

---

plugins/3scale-backend/README.md

What does this PR do?
Similar to PR #1407, we are making a change to the readme in an attempt to get the new dependencies in the yarn lock file to be released. PR 1407 failed to release because of the prettier check. This change, hopefully, will allow us to get a good build.

fix(3scale): revert readme change to pull plugin deps

---

plugins/rbac-backend/src/__fixtures__/data/valid-csv/basic-and-resource-policies.csv
plugins/rbac-backend/src/__fixtures__/data/valid-csv/policy-checks.csv
plugins/rbac-backend/src/service/enforcer-delegate.ts
plugins/rbac-backend/src/service/permission-policy.test.ts

This PR aims to utilize Casbin's subset policy loading. This approach allows us to reduce the number of permission policies and roles checked during enforcement, consequently decreasing the time it takes to evaluate the enforced permissions.
I've refactored the permission policy tests as they were failing. I've created functions for the adapter, enforcer, enforcer delegate, and RBAC permission policies to enable their reuse throughout the tests. Additionally, I've updated all adapters from `FileAdapter` to `CasbinDBAdapterFactory` to leverage the `TypeORMAdapter`. This change was necessary because the `FileAdapter` cannot handle filtered policies, unlike the `TypeORMAdapter`.

feat(rbac): load filtered policies before enforcing

---

packages/cli/package.json
packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-code.ts
packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts
packages/cli/src/commands/export-dynamic-plugin/backend-utils.ts
packages/cli/src/commands/export-dynamic-plugin/command.ts
packages/cli/src/commands/export-dynamic-plugin/dev.ts
packages/cli/src/commands/export-dynamic-plugin/frontend.ts
packages/cli/src/commands/index.ts
yarn.lock

This PR :
- adds an experimental `embed-as-dependencies` option in the `export-dynamic-plugin`  command for the backend plugins that provides an alternate way of exporting backend plugins as dynamic. In some time it should become the default way. To summarize, it includes *embedded* packages as private dependencies (ending in the plugin private `node_modules`) instead of embedding them in the generated code. This is much more robust, enable a better validation of the plugin.
- adds a `--dynamic-plugins-root` option, which can used when using the `--dev` argument to add the dynamic plugin folder into the dynmaic plugins root of a local `backstage-showcase` instance. This now works the same for frontend and backend plugins.

refactor: experimental `embed-as-dependencies` option for the backend

---

plugins/feedback-backend/src/mocks/config.ts
plugins/feedback-backend/src/service/router.ts

Closes to #1431
- Fixed feedback url in mail and jira body, when feedback is created using api
- added conditions to check `entityRef` and `feedbackType` fields in post body

fix(feedback-backend): fix the feedback url for mail and jira

---

plugins/rbac/dev/index.tsx
plugins/rbac/src/__fixtures__/mockConditionRules.ts
plugins/rbac/src/api/RBACBackendClient.ts
plugins/rbac/src/components/ConditionalAccess/ConditionalAccessSidebar.tsx
plugins/rbac/src/components/ConditionalAccess/types.ts
plugins/rbac/src/components/CreateRole/PermissionPoliciesForm.tsx
plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.test.tsx
plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
plugins/rbac/src/hooks/useConditionRules.test.ts
plugins/rbac/src/hooks/useConditionRules.ts

Story: https://issues.redhat.com/browse/RHIDP-1639
This PR adds plugins conditional access button which when clicked opens the sidebar with the list of applicable rules.
https://github.com/janus-idp/backstage-plugins/assets/20724543/20c156f1-88b7-450d-a5a6-a8e1ddf167ec

feat(rbac): add conditional access button and sidebar

---

plugins/kiali/src/components/BreadcrumbView/BreadcrumbView.tsx
plugins/kiali/src/components/Charts/SparklineChart.tsx
plugins/kiali/src/components/Overview/TLSInfo.tsx
plugins/kiali/src/components/VirtualList/Config.tsx
plugins/kiali/src/components/VirtualList/Renderers.tsx
plugins/kiali/src/components/VirtualList/VirtualItem.tsx
plugins/kiali/src/pages/AppDetails/AppDescription.tsx
plugins/kiali/src/pages/Overview/OverviewCard/CanaryUpgradeProgress.tsx
plugins/kiali/src/pages/Overview/OverviewCard/ControlPlaneNamespaceStatus.tsx
plugins/kiali/src/pages/Overview/OverviewCard/NamespaceLabels.tsx
plugins/kiali/src/pages/Overview/OverviewCard/OverviewCardControlPlaneNamespace.tsx
plugins/kiali/src/pages/Overview/OverviewPage.tsx
plugins/kiali/src/pages/WorkloadDetails/WorkloadInfo.tsx
plugins/kiali/src/styles/StyleUtils.ts

feat(kiali): update dark theme

---

plugins/rbac-backend/docs/apis.md
plugins/rbac-backend/migrations/20240308134410_migrations.js
plugins/rbac-backend/migrations/20240308134941_migrations.js
plugins/rbac-backend/src/database/conditional-storage.ts
plugins/rbac-backend/src/database/conditional.storage.test.ts
plugins/rbac-backend/src/helper.test.ts
plugins/rbac-backend/src/helper.ts
plugins/rbac-backend/src/service/condition-validation.ts
plugins/rbac-backend/src/service/condition.validation.test.ts
plugins/rbac-backend/src/service/enforcer-delegate.ts
plugins/rbac-backend/src/service/permission-policy.test.ts
plugins/rbac-backend/src/service/permission-policy.ts
plugins/rbac-backend/src/service/plugin-endpoint.test.ts
plugins/rbac-backend/src/service/plugin-endpoints.ts
plugins/rbac-backend/src/service/policies-rest-api.test.ts
plugins/rbac-backend/src/service/policies-rest-api.ts
plugins/rbac-common/src/types.ts

Rework condition policies to bound them to RBAC roles
https://issues.redhat.com/browse/RHIDP-1526
https://issues.redhat.com/browse/RHIDP-1616
You need to have two users: admin and test user.  "user:default/logarifm" is my test user and member of group:defalt/team-a. Token should be retrieved for admin user.
`
curl -X POST "http://localhost:7007/api/permission/roles" -d '{ "memberReferences":  [ "user:default/logarifm" ], "name": "role:default/test" }' -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v
`
`
curl -X POST "http://localhost:7007/api/permission/roles/conditions" -d '{"result":"CONDITIONAL","roleEntityRef": "role:default/test","pluginId":"catalog","resourceType":"catalog-entity", "permissionMapping": ["read"], …

fix(rbac): rework condition policies to bound them to RBAC roles

---

plugins/orchestrator-backend/src/service/DataInputSchemaService.test.ts
plugins/orchestrator-backend/src/service/DataInputSchemaService.ts

https://issues.redhat.com/browse/FLPATH-1179
https://github.com/janus-idp/backstage-plugins/assets/638737/3b307951-4e33-4939-8cfc-a972c75e322a

fix(orchestrator): only inputs inherited from the assessment workflow should be disabled

---

packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts
packages/cli/src/commands/export-dynamic-plugin/backend-utils.ts

This PR fixes 2 problems with the new `embed-as-dependencies` option of the `export-dynamic-plugin` CLI command for backend plugins:
- running the command with `npx` failed at validating that the required entrypoints are there
- resolved peer dependencies were added without respecting the original `workspace:` range specifier.

fix(cli): fix entrypoint validation when running with `npx`

---

plugins/feedback/src/components/CreateFeedbackModal/CreateFeedbackModal.tsx
plugins/feedback/src/components/EntityFeedbackPage/EntityFeedbackPage.tsx
plugins/feedback/src/components/FeedbackDetailsModal/FeedbackDetailsModal.tsx
plugins/feedback/src/components/FeedbackTable/FeedbackTable.tsx
plugins/feedback/src/components/OpcFeedbackComponent/OpcFeedbackComponent.tsx

Added capture events for feedback plugin
The events captured are:
- Searching
- Button clicks
- Feedback details modal
- Pagination events
closes #1437

feat(feedback): add capture events in feedback plugin

---

plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionDetailsCard.tsx
plugins/orchestrator/src/components/WorkflowInstanceStatusIndicator.tsx
plugins/orchestrator/src/components/WorkflowsTable.tsx
plugins/orchestrator/src/dataFormatters/WorkflowOverviewFormatter.ts

Jira: [https://issues.redhat.com/browse/FLPATH-1208](https://issues.redhat.com/browse/FLPATH-1208)
In the workflow table, make the last-run-status filed as a link to the workflow last-run details page.

feat(orchestrator): make workflow last run status as link to the workflow last run details page

---

packages/cli/.versionhistory.md
plugins/3scale-backend/.versionhistory.md
plugins/aap-backend/.versionhistory.md
plugins/acr/.versionhistory.md
plugins/analytics-provider-segment/.versionhistory.md
plugins/dynamic-frontend-plugin/.versionhistory.md
plugins/dynamic-plugins-info/.versionhistory.md
plugins/feedback-backend/.versionhistory.md
plugins/jfrog-artifactory/.versionhistory.md
plugins/keycloak-backend/.versionhistory.md
plugins/kubernetes-actions/.versionhistory.md
plugins/matomo-backend/.versionhistory.md
plugins/matomo/.versionhistory.md
plugins/nexus-repository-manager/.versionhistory.md
plugins/notifications/.versionhistory.md
plugins/ocm-backend/.versionhistory.md
plugins/ocm-common/.versionhistory.md
plugins/ocm/.versionhistory.md
plugins/openshift-image-registry/.versionhistory.md
plugins/quay-actions/.versionhistory.md
plugins/quay/.versionhistory.md
plugins/rbac-node/.versionhistory.md
plugins/regex-actions/.versionhistory.md
plugins/servicenow-actions/.versionhistory.md
plugins/shared-react/.versionhistory.md
plugins/sonarqube-actions/.versionhistory.md
plugins/tekton/.versionhistory.md
plugins/topology/.versionhistory.md
plugins/web-terminal/.versionhistory.md

- **feat: checkPluginVersion.sh bump plugins/3scale-backend to 1.5.0 in main**
- **feat: checkPluginVersion.sh bump plugins/aap-backend to 1.6.0 in main**
- **feat: checkPluginVersion.sh bump plugins/acr to 1.3.0 in main**
- **feat: checkPluginVersion.sh bump plugins/analytics-provider-segment to 1.3.0 in main**
- **feat: checkPluginVersion.sh bump plugins/dynamic-frontend-plugin to 0.1.0 in main**
- **feat: checkPluginVersion.sh bump plugins/dynamic-plugins-info to 1.1.0 in main**
- **feat: checkPluginVersion.sh bump …

feat: checkPluginVersion.sh bump plugins for 1.2.0 release

---

plugins/rbac-backend/docs/apis.md
plugins/rbac-backend/src/service/plugin-endpoint.test.ts
plugins/rbac-backend/src/service/plugin-endpoints.ts
plugins/rbac-common/src/types.ts

reduce the number of permissions returned, add isResourced flag. 
Notice: this pr reduces permission set in combination with current UI implementation.
Before:
After:
https://issues.redhat.com/browse/RHIDP-1926
https://issues.redhat.com/browse/RHIDP-1467

fix(rbac): reduce the number of permissions returned, add isResourced flag

---

plugins/orchestrator/README.md
plugins/orchestrator/docs/quickstart.md

fixed quick start image urls and link from README to refer to janus-idp instead of private repo, and added raw=true parameter to image urls

docs(orchestrator): fix quick start urls to private repo and make image urls raw

---

plugins/rbac-backend/README.md
plugins/rbac-backend/config.d.ts
plugins/rbac-backend/src/file-permissions/csv.test.ts
plugins/rbac-backend/src/role-manager/ancestor-search-memo.test.ts
plugins/rbac-backend/src/role-manager/ancestor-search-memo.ts
plugins/rbac-backend/src/role-manager/role-manager.test.ts
plugins/rbac-backend/src/role-manager/role-manager.ts
plugins/rbac-backend/src/service/enforcer-delegate.test.ts
plugins/rbac-backend/src/service/permission-policy.test.ts
plugins/rbac-backend/src/service/policy-builder.ts

Introduces the optional configuration value `maxDepth` that will limit the depth that hierarchy group graphs are built. This should help reduce the amount of time building complex graphs and will help with performance.
- Fixes https://issues.redhat.com/browse/RHIDP-1376
I did the bare minimum for updating the tests because I have updates to tests in this [PR](https://github.com/janus-idp/backstage-plugins/pull/1446). I will rebase and fix the tests in this PR in the event the other is merged.

feat(rbac): add the optional maxDepth feature

---

plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.test.ts
plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.ts
plugins/orchestrator-backend/src/service/api/test-utils.ts
plugins/orchestrator-backend/src/service/api/v2.ts
plugins/orchestrator-common/src/models.ts
plugins/orchestrator/src/__fixtures__/fakeLongProcessInstanceList.ts
plugins/orchestrator/src/__fixtures__/fakeProcessInstance.ts

cherry-pick from: 88b49df35cf10e231ba69c239e873cb10e7cc25b
* fix(orchestrator): fixes v2/instances endpoint
The `start` and `end` fields are annotated as `strings` instead of `Date`. The format of the string is provided as a hint for the developer as a comment (date-time)  due to limitations in the OpenAPI code generator.
* chore(orchestrator): removes format: date-time

fix(orchestrator): fixes v2/instances endpoint (#1414)

---

plugins/kiali/src/components/VirtualList/VirtualList.tsx
plugins/kiali/src/pages/AppList/AppListPage.tsx
plugins/kiali/src/pages/IstioConfigList/IstioConfigListPage.tsx
plugins/kiali/src/pages/Overview/ListView/ListViewPage.tsx
plugins/kiali/src/pages/Overview/OverviewPage.tsx
plugins/kiali/src/pages/ServiceList/ServiceListPage.tsx
plugins/kiali/src/pages/WorkloadList/WorkloadListPage.tsx

Sometimes the graph data is not loaded until you click a second time, and it looks like it has no data.
It looks like the view is not being refreshing after the request finished loading.
- Added loading message instead of "No resources found" for lists

fix(kiali): update load for overview page

---

.github/renovate.json

- Seeing warnings.  Looks like we are using the wrong field.  
WARN: Use matchDepPatterns instead of matchPackagePatterns
WARN: Error updating branch: update failure
- Disabled backstage core updates

chore(renovate): fix warnings, use matchDepPatterns instead

---

packages/cli/src/lib/bundler/bundlePlugin.ts
packages/cli/src/lib/bundler/scalprumConfig.ts
packages/cli/src/lib/bundler/types.ts

This PR removes the requirement of having a nearly-empty `app-config.yaml` file when exporting fronted plugins to dynamic.
In fact this requirement has been borrowed from the webpack configuration for the frontend application. But it makes no sense for dynamic plugins.

fix(cli): remove the requirement for `app-config` when exporting fronted plugins to dynamic.

---

packages/cli/src/commands/export-dynamic-plugin/command.ts

The `export-dynamic-plugin` command of the `@janus-idp/cli` package, when applied to frontend plugins, doesn't support packages with the `frontend-plugin-module`.
This should be allowed so that `APIFactories` can be added, for example to support additional analytics providers.
This PR drops this unnecessary limitation.

fix(cli): allow exporting dynamic plugins from `frontend-plugin-module` packages.

---

plugins/servicenow-actions/README.md

Fix a typo in the `servicenow` custom action documentation for the new backend setup
Fixes: #1585

docs(servicenow): fix typo in the service now documentation

---

packages/cli/src/commands/export-dynamic-plugin/frontend.ts
packages/cli/src/commands/index.ts

This PR adds the avalability, in the `export-dynamic-plugin` command of the `janus-idp/cli` package, to take the frontend plugin scalprum-specific configuration from an external JSON file instead of expecting the config to be specified in a `scalprum` field of the source plugin `package.json`.
It should be possible to run the `export-dynamic-plugin` CLI command directly on normal & typical backstage static frontend plugin without having to change its source.
With the current behavior, before this PR, when additional scalprum configuration is needed, there is still the requirement to update the source `package.json` in order to add the `scalprum` field with additional configuration.

fix(cli): allow retrieving scalprum config from an external file in `export-dynamic-plugin`.

---

packages/cli/src/commands/export-dynamic-plugin/frontend.ts
packages/cli/src/lib/builder/buildScalprumPlugin.ts

This PR completely removes the requirement of having a nearly-empty app-config.yaml file when exporting fronted plugins to dynamic.
This is a followup of previous [PR #1592](https://github.com/janus-idp/backstage-plugins/pull/1592) which was incomplete.

fix(cli): completely removing the requirement for `app-config` when exporting fronted plugins to dynamic.

---

plugins/orchestrator-backend/src/service/DevModeService.ts

1.This makes sure selinux context is passed when mounting
src/main/resources when starting the container using `yarn
start:backstage`
This is mainly for those developers working with podman and not docker
There's no need to hack the permissions of /tmp/orchestrator
2. Set a name for the container so it is easily identified
Signed-off-by: Roy Golan <rgolan@redhat.com>

feat(orchestrator): make the internal sonata podman compatible

---

plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx
plugins/orchestrator/src/components/ui/OverrideBackstageTable.tsx

[FLPATH-1191](https://issues.redhat.com/browse/FLPATH-1191)
The default behavior of material UI is confusing, clicking on the sort button the third time disables the sort, and it's not clear what the stage of the table should be making it feel like a bug.
There's a [discussion](https://github.com/mbrn/material-table/issues/985) about it both in Material UI and a [bug](https://github.com/backstage/backstage/issues/23969) open in backstage upstream.
Following the discussion in the upstream bug, it was agreed that each plugin should disable this feature on their own.
Since there's already a component OverrideBackstageTable for the orchestrator, used because of a theme issue, I added this fix there as well, this way the fix applies to both the instance and workflows tables.

fix(orchestrator): disabled MUI table thirdSortClick

---

plugins/kiali/dev/index.tsx
plugins/kiali/src/components/DetailDescription/DetailDescription.tsx
plugins/kiali/src/components/Drawers/AppDetailsDrawer.tsx
plugins/kiali/src/components/Drawers/ServiceDetailsDrawer.tsx
plugins/kiali/src/components/Drawers/WorkloadDetailsDrawer.tsx
plugins/kiali/src/components/VirtualList/Renderers.tsx
plugins/kiali/src/components/VirtualList/VirtualList.tsx
plugins/kiali/src/dynamic/EntityKialiResourcesCard.tsx
plugins/kiali/src/dynamic/KialiContext.tsx
plugins/kiali/src/helpers/namespaces.ts
plugins/kiali/src/index.ts
plugins/kiali/src/pages/AppDetails/AppDescription.tsx
plugins/kiali/src/pages/AppDetails/AppInfo.tsx
plugins/kiali/src/pages/AppList/AppListPage.tsx
plugins/kiali/src/pages/ServiceDetails/ServiceDescription.tsx
plugins/kiali/src/pages/ServiceDetails/ServiceInfo.tsx
plugins/kiali/src/pages/ServiceList/ServiceListPage.tsx
plugins/kiali/src/pages/WorkloadDetails/WorkloadInfo.tsx
plugins/kiali/src/pages/WorkloadDetails/WorkloadsDescription.tsx
plugins/kiali/src/pages/WorkloadList/WorkloadListPage.tsx
plugins/kiali/src/plugin.ts
plugins/kiali/src/types/ErrorRate/ErrorRate.ts
plugins/kiali/src/types/Health.ts
plugins/kiali/src/types/types.ts
plugins/kiali/tests/entityResources.spec.ts
plugins/kiali/tests/kiali.spec.ts

How to include a card: 
```
// packages/app/src/components/catalog/EntityPage.tsx
const overviewContent = (
<Grid container spacing={3} alignItems="stretch">
...
<Grid item md={8} xs={12}>
<EntityKialiResourcesCard />
</Grid>
```

feat(kiali): add card for resources 

---

plugins/argocd/config.d.ts

Change visibility of the argocd appLocatorMethods configuration and explicitly mask the visibility of username and password fields.

fix(argocd): fix argocd configurations visibility

---

packages/backend/src/index.ts
packages/backend/src/types.ts
plugins/orchestrator-backend/dev/index.ts
plugins/orchestrator-backend/src/run.ts

Removing references to the deprecated `ServiceBroker` and importing the new `EventsService`.
Changes were made based on this documentation: https://github.com/backstage/backstage/tree/master/plugins/events-node

chore: use the new Events service in the Showcase

---

plugins/rbac-backend/README.md
plugins/rbac-backend/src/file-permissions/csv.test.ts
plugins/rbac-backend/src/plugin.ts
plugins/rbac-backend/src/role-manager/ancestor-search-memo.test.ts
plugins/rbac-backend/src/role-manager/ancestor-search-memo.ts
plugins/rbac-backend/src/role-manager/role-manager.test.ts
plugins/rbac-backend/src/role-manager/role-manager.ts
plugins/rbac-backend/src/service/enforcer-delegate.test.ts
plugins/rbac-backend/src/service/permission-policy.test.ts
plugins/rbac-backend/src/service/policy-builder.test.ts
plugins/rbac-backend/src/service/policy-builder.ts

While upgrading to the new backend system, I missed one other place that required the new `auth` backend service. This PR fixes that mistake as well as removes the token manager since it is no longer in use.
I tested this with both `admin` and `superUser` with and without the database.

fix(rbac)!: remove token manager for auth service

---

.github/CODEOWNERS
plugins/notifications-backend/OWNERS
plugins/notifications/OWNERS
plugins/orchestrator-backend/OWNERS
plugins/orchestrator-common/OWNERS
plugins/orchestrator-swf-editor-envelope/OWNERS
plugins/orchestrator/OWNERS

- Confirmed with the @janus-idp/orchestrator team that they would prefer to use CODEOWNERS over OWNERS.  Deleting OWNERS to avoid dup assignments
- Update CODEOWNERS to add the missing `/plugins/orchestrator-swf-editor-envelope` plugin

chore(owners): remove OWNERS files from orchestrator plugins

---

.github/CODEOWNERS
plugins/kiali-backend/OWNERS
plugins/kiali/OWNERS

* confirmed with @aljesusg that it's ok to remove the OWNERS file from their plugins
* removed `/plugins/kiali-common` from CODEOWNERS since that no longer exists

chore(owners): remove OWNERS files from kiali, update CODEOWNERS

---

plugins/kiali/tests/kiali.spec.ts

the `afterAll` hook in test file is not needed. It causing troubles when another file is executed after specific file with the ` await browser.close();` method. From the playwright docs
> The [Browser](https://playwright.dev/docs/api/class-browser) object itself is considered to be disposed and cannot be used anymore.
This is simplest fix for now. If test starts to flake again, lets reiterate and create more robust bootstrap and cleanup methods. Tested, working with multiple test files.

fix(kiali): removing unnecessary afterAll hook

---

plugins/argocd/config.d.ts

Since we have a fallback value for refreshInterval config, marking it as optional field.

fix(argocd): make refreshInterval configuration as optional

---

package.json
turbo.json

Turbo supports caching for tasks, including build(ing), lint(ing), and even test(ing).
While investigating why #1480 failed multiple times, I noticed that **different** tests fail our GitHub Actions and on my local machine. But when I tried to run the tests for a single workspace/plugin these tests pass...
I could reproduce this when disable the cache. The currency is 10 by default and many different workspaces fail:
```
yarn turbo test --force # default is --concurrency=10
...
@janus-idp/backstage-plugin-rbac#test: command (/home/christoph/git/janus-idp/backstage-plugins/plugins/rbac) yarn run test exited (1)
Tasks:    12 successful, 47 total
Cached:    0 cached, 47 total
Time:    1m3.393s 
Failed:    @janus-idp/backstage-plugin-rbac#test
ERROR  run failed: command  exited (1)
error …
```

chore(tests): do not run unit tests in parallel

---

plugins/orchestrator/src/api/OrchestratorClient.test.ts
plugins/orchestrator/src/utils/UrlUtils.test.ts

This PR introduces unit tests for the `OrchestratorClient` methods. These tests have been added as part of the work related to the introduction of a new endpoint defined via OpenAPI (v2) and the deprecation of the current endpoint (v1).
[FLPATH-1125](https://issues.redhat.com/browse/FLPATH-1125)
*Why These Changes Are Necessary*
With the introduction of the v2 OpenAPI endpoint and the deprecation of the current endpoint (v1), these unit tests serve as a safeguard against regressions and help early detect any issues that may arise due to changes in the endpoints.

test(orchestrator): add  OrchestratorClient unit tests

---

.github/renovate.json

Fixes: https://issues.redhat.com/browse/RHIDP-2190
* Added config to group PRs based on github teams (we will rely on CODEOWNERS to auto-assign based on touched files)
* Auto-merge enabled for minor DevDependencies and Test package updates
* `team/<plugin-team>` labels added for grouped PR except for Vulnerability alerts.   The `additionalBranchPrefix` was creating multiple dup PRs (based on unique branch names).  I had to reset this value to "" in the VulnerabilityAlerts rule in order to fix this, which means we can't label this.  We will rely on CODEOWNERS to assign to the right team in this case.  Since most security vulns affect the root yarn.lock file, they should be correctly assigned to the `maintainers-plugins` team (from CODEOWNERS file)
See test repo for results: …

chore(renovate): update config to create team specific PRs

---

plugins/rbac/dev/index.tsx
plugins/rbac/src/__fixtures__/mockConditions.ts
plugins/rbac/src/__fixtures__/mockFormValues.tsx
plugins/rbac/src/api/RBACBackendClient.ts
plugins/rbac/src/components/ConditionalAccess/ConditionalAccessSidebar.tsx
plugins/rbac/src/components/ConditionalAccess/ConditionsForm.tsx
plugins/rbac/src/components/ConditionalAccess/ConditionsFormRow.tsx
plugins/rbac/src/components/CreateRole/EditRolePage.test.tsx
plugins/rbac/src/components/CreateRole/EditRolePage.tsx
plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
plugins/rbac/src/components/CreateRole/RoleForm.tsx
plugins/rbac/src/components/RoleOverview/PermissionsCard.test.tsx
plugins/rbac/src/components/RoleOverview/PermissionsCard.tsx
plugins/rbac/src/components/RolesList/DeleteRoleDialog.test.tsx
plugins/rbac/src/components/RolesList/DeleteRoleDialog.tsx
plugins/rbac/src/hooks/usePermissionPolicies.ts
plugins/rbac/src/types.ts
plugins/rbac/src/utils/create-role-utils.test.ts
plugins/rbac/src/utils/create-role-utils.ts
plugins/rbac/src/utils/rbac-utils.test.ts
plugins/rbac/src/utils/rbac-utils.ts
plugins/rbac/tests/rbac.spec.ts

Story: https://issues.redhat.com/browse/RHIDP-1878
This PR adds support for updating/deleting existing conditions.
https://github.com/janus-idp/backstage-plugins/assets/20724543/ffbeb886-9656-4b23-a38c-0f23985c291b

feat(rbac): support for updating/deleting conditional permissions

---

plugins/orchestrator-backend/app-config.janus-idp.yaml
plugins/orchestrator-common/config.d.ts
plugins/orchestrator-swf-editor-envelope/README.md
plugins/orchestrator/README.md

Removes deprecated documentation related to the editor settings

docs(orchestrator): removes instructions related to the editor

---

package.json
plugins/orchestrator/package.json
yarn.lock

Accessing the Workflow Editor in the Orchestrator plugin throws an error after the [Backstage upgrade to 1.26](https://github.com/janus-idp/backstage-plugins/pull/1536) and this PR fixes it.

fix(orchestrator): remove the need of react dev dependencies

---

plugins/orchestrator-backend/package.json
plugins/orchestrator/package.json

The `common` package version was bumped by the bot but its references have not been updated.

fix(orchestrator): fix the common package reference version

---

plugins/feedback-backend/dist-dynamic/package.json
plugins/feedback-backend/dist-dynamic/yarn.lock
plugins/feedback-backend/package.json
plugins/feedback-backend/src/dynamic/inedx.ts
plugins/feedback/package.json
plugins/feedback/src/components/CreateFeedbackModal/CreateFeedbackModal.tsx
plugins/feedback/src/components/EntityFeedbackPage/CustomEmptyState/CustomEmptyState.tsx
plugins/feedback/src/components/EntityFeedbackPage/EntityFeedbackPage.test.tsx
plugins/feedback/src/components/EntityFeedbackPage/EntityFeedbackPage.tsx
plugins/feedback/src/components/FeedbackDetailsModal/FeedbackDetailsModal.tsx
plugins/feedback/src/components/FeedbackTable/FeedbackTable.tsx
plugins/feedback/src/components/GlobalFeedbackPage/GlobalFeedbackPage.tsx
plugins/feedback/src/components/OpcFeedbackComponent/OpcFeedbackComponent.tsx
plugins/feedback/src/index.ts
plugins/matomo-backend/README.md
plugins/matomo-backend/app-config.janus-idp.yaml
plugins/matomo-backend/config.d.ts
plugins/matomo-backend/src/plugin.ts
plugins/matomo-backend/src/service/router.ts
plugins/matomo-backend/src/service/standaloneServer.ts
plugins/matomo/README.md
plugins/matomo/package.json
plugins/matomo/src/api/index.ts
plugins/matomo/src/components/MatomoPage/MatomoPage.tsx
plugins/matomo/src/components/MatomoPage/StatsCard.tsx
plugins/matomo/src/plugin.ts
yarn.lock

feat(feedback): upgrade to mui v5
- switch to backstage `AlertApi` instead of MUI Snackbars
- use mui 5 styled components
- add `themeId` prop to GlobalFeedback component
Signed-off-by: Yash Oswal <yashoswal18@gmail.com>
feat(matomo): upgrade to mui v5
- added `secure` flag to matomo-backend plugin
- use backstage fetchApi for new backend system
Signed-off-by: Yash Oswal <yashoswal18@gmail.com>

fix(deps): upgrade devex plugins to mui v5

---

plugins/rbac-common/package.json
plugins/rbac-common/src/types.ts

A convenience authorization error instead of continuously creating
NotAllowedError('Unauthorized')
Fixes: https://issues.redhat.com/browse/RHIDP-2411
Signed-off-by: Roy Golan <rgolan@redhat.com>

chore(rbac-common): add Unauthorized error

---

plugins/orchestrator-backend/src/OrchestratorPlugin.ts

[FLPATH-1331](https://issues.redhat.com/browse/FLPATH-1331)
Issue:
Following upgrade to backstage 1.26, authentication is required by default. This causes the API for retrieving the workflow editor envelope files to fail with "401 unauthorised"
Solution:
Follow [upstream documentation](https://backstage.io/docs/tutorials/auth-service-migration/#adding-auth-policies) for adding an exception for this policy for the workflow editor files API.
Includes also exception of the /health API

fix(orchestrator): fixed broken workflow viewer

---

plugins/topology-common/package.json

Update the topology common `package.json` to be public
Fixes https://github.com/janus-idp/backstage-plugins/issues/1716

chore(topology-common): change package to public

---

plugins/orchestrator-swf-editor-envelope/package.json
plugins/orchestrator-swf-editor-envelope/scripts/build

Issue: 
The build of the the orchestrator-swf-editor-envelope breaks the [release pipeline](https://github.com/janus-idp/backstage-plugins/actions/runs/9255511136/job/25459744222#step:4:4465) 
It'll take time to investigate.
Resolution:
Since we have the [build results](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/orchestrator-backend/static/generated/envelope) in orchestrator-backend and since the code there rarely changes if at all, we don't need this build job to be enabled

fix(orchestrator): temporarily disable plugins/orchestrator-swf-editor-envelope build

---

plugins/orchestrator-backend/turbo.json

Fix build/test error due to missing dependency.
```
@janus-idp/backstage-plugin-orchestrator-backend:export-dynamic
cache bypass, force executing 35e60e6553d858b4
$ janus-cli package export-dynamic-plugin
Embedding module @janus-idp/backstage-plugin-orchestrator-common
Error: Error: Could not resolve './generated/client' from ../orchestrator-common/src/index.ts
```

chore(orchestrator): add dependency to orchestrator-common in turbo

---

plugins/rbac/src/__fixtures__/mockConditionRules.ts
plugins/rbac/src/components/ConditionalAccess/ConditionsFormRowFields.tsx
plugins/rbac/src/components/ConditionalAccess/CustomArrayField.tsx

[RHIDP-2345](https://issues.redhat.com/browse/RHIDP-2345)
Screen recording
https://github.com/janus-idp/backstage-plugins/assets/26255262/2d1416d7-7b04-4a37-b0f3-e7a22b504fcc

fix(rbac): conditional access form validation

---

plugins/orchestrator/turbo.json

Add dependency to orchestrator-common `openapi:generate` even for `orchestrator` module turborun pipeline.

chore(orchestrator): add dependency to common in orchestrator turbo

---

plugins/rbac-backend/docs/apis.md
plugins/rbac-backend/docs/conditions.md
plugins/rbac-backend/src/file-permissions/csv-file-watcher.ts
plugins/rbac-backend/src/service/permission-policy.ts
plugins/rbac-backend/src/service/policies-rest-api.test.ts
plugins/rbac-backend/src/service/policies-rest-api.ts
plugins/rbac-backend/src/validation/condition-validation.test.ts
plugins/rbac-backend/src/validation/condition-validation.ts
plugins/rbac-backend/src/validation/policies-validation.test.ts
plugins/rbac-backend/src/validation/policies-validation.ts

Adds some more validation to conditional policies. This validation ensures that conditional policies do not have criteria defined in parallel. Example can be found below. Also includes a new test for nested conditions. Updates documentation about nested conditions with a not about the lack of support for parallel condition criteria.
- Fixes: [RHIDP-2157](https://issues.redhat.com/browse/RHIDP-2157)
Example of a condition in parallel:
```
{
"anyOf": [
{
"rule": "IS_ENTITY_OWNER",
"resourceType": "catalog-entity",
"params": {
"claims": ["group:default/team-a"]
}
},
{
"rule": "IS_ENTITY_KIND",
"resourceType": "catalog-entity",
"params": {
"kinds": ["Group"]
}
}
],
"not": {
"rule": "IS_ENTITY_KIND",
"resourceType": "catalog-entity",
"params": { "kinds": ["Api"] }
}
}
```
Example of a nested …

feat(rbac): improve conditional policy validation

---

app-config.yaml

Current Issue:
When running yarn start:backstage, the application encounters a critical problem where all backend calls fail with a "401 Unauthorized" error. The issue stems from missing credentials, as indicated by the stack trace's "AuthenticationError: Missing credentials" message.
Proposed Solution:
This pull request addresses the issue by including the guest authentication provider by default, effectively resolving the authentication problem.
Note: 
Running "npx @backstage/create-app@latest" to bootstrap a new backstage app, includes this config.

fix(config): enable guest provider by default

---

packages/cli/package.json
plugins/acr/package.json
plugins/argocd/package.json
plugins/audit-log-node/package.json
plugins/catalog-backend-module-scaffolder-relation-processor/dist-dynamic/package.json
plugins/catalog-backend-module-scaffolder-relation-processor/package.json
plugins/jfrog-artifactory/package.json
plugins/orchestrator-swf-editor-envelope/package.json
plugins/topology-common/package.json

- Changes `@janus-idp/backstage-plugin-catalog-backend-module-scaffolder-relation-processor` to private temporarily
- Changes `@janus-idp/audit-log-node` to private temporarily
- Uniformly updates `repository` location
- Reverts `@janus-idp/shared-react` issue

fix(release): change problematic plugins to private

---

packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts

Starting with backstage release 1.24.0, the use of `ts-node` to manage the typescript compilation has been replaced by the use of the `@backstage/cli/config/nodeTransform.cjs` script based on `pirates` and `@swc/core`  (see commit https://github.com/backstage/backstage/commit/2c2f705fe169f72fdac4da84c154d7118598d06f).
We should adapt to this in the the validation of the entrypoints part of the Janus CLI `expot-dynamic-plugin` command new implementation for backend plugins.

fix(cli): fix entrypoint validation on backstage 1.24.0 and above.

---

plugins/rbac/README.md
plugins/rbac/src/components/CreateRole/AddMembersForm.tsx
plugins/rbac/src/components/CreateRole/CreateRolePage.test.tsx
plugins/rbac/src/components/CreateRole/CreateRolePage.tsx
plugins/rbac/src/components/CreateRole/EditRolePage.test.tsx
plugins/rbac/src/components/CreateRole/EditRolePage.tsx
plugins/rbac/src/components/RoleOverview/MembersCard.test.tsx
plugins/rbac/src/components/RoleOverview/MembersCard.tsx
plugins/rbac/src/components/RoleOverview/PermissionsCard.test.tsx
plugins/rbac/src/components/RoleOverview/PermissionsCard.tsx
plugins/rbac/src/components/RoleOverview/RoleOverviewPage.tsx
plugins/rbac/src/hooks/useMembers.ts
plugins/rbac/src/hooks/useRoles.ts
plugins/rbac/src/hooks/useSelectedMembers.ts

Fixes: https://issues.redhat.com/browse/RHIDP-1757
Currently `catalog.entity.read` permission auth was incorrect as it expects a complete resource ref for eg  `component:default/test` but `catalog-entity` was used instead and on applying any conditions to the admin role the create button was getting disabled as /api/permission/authorize returns 500 with this error for catalogEntityReadPermission :
"Entity reference \"catalog-entity\" had missing or empty kind (e.g. did not start with \"component:\" or similar)"
To fix this I have remove this permission check. If the user is authorised to read users and groups this /api/catalog/entities?filter=kind=user&filter=kind=group will return a list of users and groups otherwise it returns an empty array. So I have uitilised this to check if the …

fix(rbac): fix to enable create and edit role buttons on having correct permissions

---

plugins/rbac/src/components/ConditionalAccess/ConditionsFormRow.tsx

The criteria toggle button (ButtonGroup or ToggleButtonGroup) sets a custom style for the inactive options with a too low contrast.
When removing the color, these button colors were blue by default because all buttons have a blue color by default.
To remove that, I switched to the semantic, more matching ToggleButtonGroup and ToggleButton here so that it matches almost automatically our design.
Here is the sidebar design change (with the latest theme already):
| Before | After |
|---|---|
| ![backstage-light-before](https://github.com/janus-idp/backstage-plugins/assets/139310/adb9f12d-1887-422d-9ae7-df87545cf386) | ![backstage-light-after](https://github.com/janus-idp/backstage-plugins/assets/139310/c3e02906-60c5-46f5-8523-1ddb5f045d61) |
| …

fix(rbac): improve criteria toggle button readability on dark themes

---

plugins/orchestrator-common/package.json
plugins/orchestrator-common/scripts/openapi.sh

`script.sh` uses libraries that aren't listed in package.json

chore(orchestrator): add missing dev dependencies

---

plugins/rbac/src/components/Router.test.tsx
plugins/rbac/src/components/Router.tsx

For [RHIDP-2344](https://issues.redhat.com/browse/RHIDP-2344): Show empty state when rbac frontend is not available
(Updated on 5/30)
```
<ErrorPage
status="404"
statusMessage="Enable the RBAC backend plugin to use this feature."
additionalInfo="To enable RBAC, set `permission.enabled` to `true` in the app-config file."
/>
```
@ShiranHi @divyanshiGupta Let me know if I need to update the `statusMessage` or the `addtionalInfo` content.
Screenshot(updated on 5/30):

fix(rbac): add proper empty page for RBAC plugin

---

plugins/rbac/src/components/RbacPage.test.tsx
plugins/rbac/src/components/RolesList/RolesList.test.tsx
plugins/rbac/src/components/RolesList/RolesList.tsx
plugins/rbac/src/hooks/useRoles.test.ts
plugins/rbac/src/hooks/useRoles.ts

For [RHIDP-2431](https://issues.redhat.com/browse/RHIDP-2431)
Screen recording
https://github.com/janus-idp/backstage-plugins/assets/26255262/b130e344-ed3a-4edb-be41-95cefdbc556a
Screenshot for error on fetching role conditions

fix(rbac): fix role list view permission policies column value

---

packages/backend/package.json
packages/backend/src/index.ts
packages/backend/src/logger/customLogger.ts
packages/backend/src/logger/index.ts
plugins/rbac-backend/docs/audit-log.md
plugins/rbac-backend/package.json
plugins/rbac-backend/src/audit-log/audit-logger.ts
plugins/rbac-backend/src/audit-log/rest-errors-interceptor.ts
plugins/rbac-backend/src/database/conditional-storage.ts
plugins/rbac-backend/src/database/conditional.storage.test.ts
plugins/rbac-backend/src/database/role-metadata.test.ts
plugins/rbac-backend/src/database/role-metadata.ts
plugins/rbac-backend/src/file-permissions/csv-file-watcher.test.ts
plugins/rbac-backend/src/file-permissions/csv-file-watcher.ts
plugins/rbac-backend/src/helper.test.ts
plugins/rbac-backend/src/helper.ts
plugins/rbac-backend/src/service/enforcer-delegate.test.ts
plugins/rbac-backend/src/service/enforcer-delegate.ts
plugins/rbac-backend/src/service/permission-policy.test.ts
plugins/rbac-backend/src/service/permission-policy.ts
plugins/rbac-backend/src/service/policies-rest-api.test.ts
plugins/rbac-backend/src/service/policies-rest-api.ts
plugins/rbac-backend/src/service/policy-builder.ts
plugins/rbac-backend/src/validation/policies-validation.test.ts
plugins/rbac-common/src/types.ts

Implement audit logging for RBAC backend
https://issues.redhat.com/browse/RHIDP-2004

feat(rbac): add audit log for RBAC backend

---

packages/cli/src/commands/index.ts
yarn.lock

This PR switches the default values of the `--embed-as-dependencies` and `in-place` options:
- `--embed-as-dependencies` becomes `true` by default,
- `--in-place` becomes `false` by default.
These new default values will enable by default the new implementation of the `export-dynamic-plugin` command for both frontend and backend plugins, which brings many usability, validation and robustness enhancements, and has been tested and validated widely while in experimental mode. 
However since the CI builds of the [`backstage-plugins`](https://github.com/janus-idp/backstage-plugins) and [`backstage-showcase`](https://github.com/janus-idp/backstage-showcase) repositories still rely on the old CLI behavior for both frontend and backend plugins, all the calls to the `export-dynamic-plugin` CLI …

feat: switch defaults of the `--embed-as-dependencies` and `in-place` options.

---

plugins/audit-log-node/src/DefaultAuditLogger.ts
plugins/audit-log-node/src/types.ts
plugins/rbac-backend/src/audit-log/audit-logger.ts
plugins/rbac-backend/src/file-permissions/csv-file-watcher.ts
plugins/rbac-backend/src/helper.ts
plugins/rbac-backend/src/service/permission-policy.ts
plugins/rbac-backend/src/service/policies-rest-api.ts

Add type checks for audit log metadata object for type safety.

feat(rbac): add type checks with generics for audit log

---

plugins/kiali/DEVELOPMENT.md

Adapt development documentation to alpha.

docs(kiali): update development doc

---

plugins/argocd/package.json
plugins/bulk-import/package.json
plugins/quay/package.json
plugins/quay/tests/quay.spec.ts
plugins/rbac/package.json
plugins/tekton/package.json
yarn.lock

chore: align up playwright version in plugins and skip failed tests temporarily
Signed-off-by: Yi Cai (yicai@redhat.com)
N/A
e2e tests
For example:
```
Error: Playwright Test did not expect test.describe() to be called here.
Most common reasons include:
- You are calling test.describe() in a configuration file.
- You are calling test.describe() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
when one of the dependencies in your package.json depends on @playwright/test.
at bulkImport.spec.ts:5
3 | import { Common } from './bulkImportHelper';
4 |
> 5 | test.describe('Bulk import plugin', () => {
|      ^
6 |   let page: Page;
7 |   let common: Common;
8 |
at TestTypeImpl._currentSuite …
```

chore: align up playwright version in plugins and skip failed tests temporarily 

---

plugins/topology/package.json
plugins/topology/src/components/Topology/TopologyViewWorkloadComponent.tsx

There is an issue where using a conditional policy that involves the catalog entity read permission will cause an error to be thrown when attempting to access the Topology page. This PR aims to remove the catalog entity read permission check from the Topology page which in turn will fix the error. 
- Fixes: [RHIDP-2594](https://issues.redhat.com/browse/RHIDP-2594)

fix(topology): remove check for catalog entity permission

---

plugins/orchestrator-backend/src/service/OrchestratorService.test.ts
plugins/orchestrator-backend/src/service/OrchestratorService.ts

https://issues.redhat.com/browse/FLPATH-1381
resolved the issue by calling the data index also when the cache is empty, so it'll fail in case data index isn't available

fix(orchestrator): fix error handling in case data index failed to start

---

plugins/feedback-backend/config.d.ts
plugins/feedback-backend/src/service/emails.ts
plugins/feedback-backend/src/service/router.ts

Fixed feedback plugin crashing when integrations are not found
Fixes:
- #1709 
- #1679

fix(feedback): fixed feedback backend plugin crashing

---

packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-code.ts

This PR fixes the erroneous removal of `dist/*.d.ts` files by the `export-dynamic` command, when used on backend plugins with the `no-embed-as-dependencies` option.

fix(cli): fix the removal of type definitions by `export-dynamic`.

---

plugins/feedback-backend/dist-dynamic/package.json
plugins/feedback-backend/package.json
plugins/kiali-backend/dist-dynamic/package.json
plugins/kiali-backend/package.json
plugins/kubernetes-actions/dist-dynamic/package.json
plugins/kubernetes-actions/package.json
plugins/nexus-repository-manager/turbo.json
plugins/scaffolder-annotator-action/dist-dynamic/package.json
plugins/scaffolder-annotator-action/package.json
plugins/servicenow-actions/turbo.json
turbo.json

Fix missing postversion script is several plugins, as well as a missing dependency in the turbo file between the `export-dynamic` task and the `tsc` task.

fix: missing postversion script is several plugins and missing turbo dependency

---

plugins/keycloak-backend/README.md
plugins/keycloak-backend/src/extensions.ts
plugins/keycloak-backend/src/index.ts
plugins/keycloak-backend/src/module/catalogModuleKeycloakEntityProvider.ts

Resolves [RHIDP-2644](https://issues.redhat.com/browse/RHIDP-2644): Expose extension points for the keycloak-backend plugin
To test this change locally, [this](https://github.com/JessicaJHee/backstage-showcase/tree/testing-keycloak-transformers) may be useful - it adds a new module that uses the extension point to append `_foo` and `_bar` to the group and user name respectively.

feat(keycloak): expose keycloak user/group transformer extension point

---

plugins/kiali/src/components/Banners/TechPreviewWarning.tsx
plugins/kiali/src/components/Router.tsx

Included in Kiali tab: 
And Kiali standalone:

feat(kiali): add banner to warn for tech preview windows

---

plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycle.tsx
plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleCard.tsx
plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleDrawer.tsx
plugins/argocd/src/components/DeploymentLifeCycle/__tests__/DeploymentLifecycle.test.tsx
plugins/argocd/src/components/DeploymentLifeCycle/__tests__/DeploymentLifecycleCard.test.tsx
plugins/argocd/src/components/DeploymentLifeCycle/__tests__/DeploymentLifecycleDrawer.test.tsx
plugins/argocd/src/types.ts

Do not show Commit section for non-gitops application (helm based).
**How to test**
1. Create a namespace called `test`
2. Create a application using helm charts
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
name: quarkus-app
labels:
rht-gitops.com/janus-argocd: quarkus-app
spec:
destination:
namespace: test
server: https://kubernetes.default.svc
project: default
source:
helm:
parameters:
- name: build.enabled
value: "false"
- name: deploy.route.enabled
value: "false"
- name: image.name
value: quay.io/redhatworkshops/gitops-helm-quarkus
chart: quarkus
repoURL: https://redhat-developer.github.io/redhat-helm-charts
targetRevision: 0.0.3
syncPolicy:
retry:
backoff:
duration: 5s
factor: 2
maxDuration: 3m0s
limit: 5
automated:
prune: true
selfHeal: true …
```

fix(argocd): hide commit section for helm based applications

---

plugins/kiali-backend/app-config.janus-idp.yaml
plugins/kiali-backend/config.d.ts
plugins/kiali-backend/src/clients/KialiAPIConnector.test.ts
plugins/kiali-backend/src/clients/fetch.test.ts
plugins/kiali-backend/src/service/config.test.ts
plugins/kiali-backend/src/service/config.ts
plugins/kiali-backend/src/service/router.ts
plugins/kiali/src/components/About/AboutUIModal.tsx
plugins/kiali/src/components/DetailDescription/DetailDescription.tsx
plugins/kiali/src/components/Label/Labels.tsx
plugins/kiali/src/pages/WorkloadDetails/WorkloadsDescription.tsx
plugins/kiali/src/types/StatusState.ts
plugins/kiali/tests/entityResources.spec.ts

```
kiali:
url: ${KIALI_BASE_URL}
urlExternal: ''
```
This URL is also displayed in the about window, it can be used to verify: 
- Added some test coverage for resources card.

feat(kiali): include Kiali external URL as a parameter

---

plugins/kubernetes-actions/dist-dynamic/yarn.lock
plugins/ocm-backend/dist-dynamic/yarn.lock
yarn.lock

Update the ws dependencies to `6.2.3`, `7.5.10`, and `8.17.1`
Fixes [**CVE-2024-37890**](https://access.redhat.com/security/cve/CVE-2024-37890) - A flaw was found in the Node.js WebSocket library (`ws`). A request with several headers exceeding the 'server.maxHeadersCount' threshold could be used to crash a `ws` server, leading to a denial of service.

chore(deps): regenerate yarn.lock to update ws

---

plugins/kiali/dev/__fixtures__/general/istioValidations.json
plugins/kiali/dev/__fixtures__/namespaces/travel-agency/health/app.json
plugins/kiali/dev/__fixtures__/namespaces/travel-control/health/app.json
plugins/kiali/src/components/About/AboutUIModal.tsx
plugins/kiali/src/components/MessageCenter/AlertDrawer.tsx
plugins/kiali/src/components/MessageCenter/AlertDrawerGroup.tsx
plugins/kiali/src/components/MessageCenter/AlertDrawerMessage.tsx
plugins/kiali/src/components/MessageCenter/MessageCenter.tsx
plugins/kiali/src/components/Validations/ValidationSummary.tsx
plugins/kiali/src/pages/Kiali/Header/HelpKiali.tsx
plugins/kiali/src/pages/Kiali/Header/KialiHeader.tsx
plugins/kiali/src/pages/Kiali/Header/NamespaceSelector.tsx
plugins/kiali/src/pages/Overview/OverviewCard/NamespaceLabels.tsx
plugins/kiali/src/pages/Overview/OverviewCard/OverviewCard.tsx
plugins/kiali/src/pages/Overview/OverviewStatus.tsx
plugins/kiali/tests/kialiHelper.ts
plugins/kiali/tests/kialiPage.spec.ts

I added some tests for the header and also for the Overview cards. Links to other pages and graphs cannot be tested yet, as they do not work properly.

feat(kiali): add tests for the overview page

---

plugins/orchestrator-backend/src/service/router.ts

This pr fixes the [build](https://github.com/janus-idp/backstage-plugins/actions/runs/9698241417/job/26765971595) failure on main branch from [#1833](https://github.com/janus-idp/backstage-plugins/pull/1833). It only removes the obsolete route and dependencies.

feat(orchestrator): fix build failure from #1833

---

plugins/rbac-backend/src/database/casbin-adapter-factory.test.ts
plugins/rbac-backend/src/database/casbin-adapter-factory.ts

When Backstage uses a single database, the **casbin_rule** table is created in the **public** schema instead of the **permission** schema.
https://backstage.io/docs/tutorials/switching-sqlite-postgres/#using-a-single-database

fix(rbac): casbinDBAdapterFactory supporting postgres schema configuration

---

plugins/feedback/src/components/CreateFeedbackModal/CreateFeedbackModal.tsx

fix: multiple feedback were getting created if user double clicked on submit button, since the button was not disabled after first click

fix(feedback): fixed feedback creation

---

plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx

Following upgrade of material UI packages, styling needed to move from InfoCard to CardContent
resolves [FLPATH-1480](https://issues.redhat.com/browse/FLPATH-1480)

fix(orchestrator): returned scrolling bars to instance page cards

---

plugins/rbac/src/__fixtures__/mockConditions.ts
plugins/rbac/src/components/CreateRole/RoleForm.tsx
plugins/rbac/src/components/RolesList/DeleteRoleDialog.tsx
plugins/rbac/src/types.ts
plugins/rbac/src/utils/create-role-utils.ts
plugins/rbac/src/utils/role-form-utils.test.ts
plugins/rbac/src/utils/role-form-utils.ts

Tech debt - https://issues.redhat.com/browse/RHIDP-2404

refactor(rbac): reduce cognitive stress for create, update and delete role functions

---

plugins/catalog-backend-module-scaffolder-relation-processor/README.md
plugins/catalog-backend-module-scaffolder-relation-processor/package.json

Deprecates the scaffolder relation processor module
Fixes: [RHIDP-3162](https://issues.redhat.com/browse/RHIDP-3162)

chore: deprecate and private the scaffolder relation processor module

---

plugins/orchestrator-backend/dist-dynamic/package.json
plugins/orchestrator-backend/dist-dynamic/yarn.lock
plugins/orchestrator-backend/package.json
plugins/orchestrator-common/package.json

Semantic release for PR #1864 failed to push `orchestrator-common` version bump because of ` [9:50:32 PM] [@janus-idp/backstage-plugin-orchestrator-common] › :information_source:  The local branch main is behind the remote one, therefore a new version won't be published.` (full log [here](https://github.com/janus-idp/backstage-plugins/actions/runs/9895783779/job/27346239425#step:6:554)).
To fix this, a minor change to `orchestrator-common/package.json` has been made.
In addition, to fix the partial upgrade it's necessary to downgrade to `orchestrator-common@1.10.0` dependency into `orchestrator-backend`

feat(orchestrator): fix version

---

plugins/rbac-backend/docs/apis.md
plugins/rbac-backend/src/audit-log/audit-logger.ts
plugins/rbac-backend/src/service/plugin-endpoint.test.ts
plugins/rbac-backend/src/service/plugin-endpoints.ts
plugins/rbac-backend/src/service/policies-rest-api.test.ts
plugins/rbac-common/src/types.ts
plugins/rbac/dev/index.tsx
plugins/rbac/src/__fixtures__/mockPermissionPolicies.ts
plugins/rbac/src/api/RBACBackendClient.ts
plugins/rbac/src/utils/create-role-utils.test.ts
plugins/rbac/src/utils/create-role-utils.ts
plugins/rbac/src/utils/rbac-utils.ts

Cherry-picking this PR: https://github.com/janus-idp/backstage-plugins/pull/1795 into the 1.2.x branch, so then later I can run the https://gitlab.cee.redhat.com/rhidp/rhdh/-/blob/rhdh-1-rhel-9/build/scripts/releasePlugin.sh to release a new version of the plugin.
related JIRA issue: https://issues.redhat.com/browse/RHIDP-2374

fix(rbac): correct plugin ID matching to permission policy (#1795)

---

plugins/kiali/src/components/IstioConfigCard/IstioConfigCard.tsx
plugins/kiali/src/components/VirtualList/Renderers.tsx
plugins/kiali/src/components/VirtualList/VirtualList.tsx
plugins/kiali/src/dynamic/EntityKialiResourcesCard.tsx
plugins/kiali/src/pages/AppDetails/AppDescription.tsx
plugins/kiali/src/pages/AppList/AppListPage.tsx
plugins/kiali/src/pages/Overview/ListView/ListViewPage.tsx
plugins/kiali/src/pages/ServiceDetails/ServiceDescription.tsx
plugins/kiali/src/pages/ServiceDetails/ServiceInfo.tsx
plugins/kiali/src/pages/ServiceDetails/ServiceNetwork.tsx
plugins/kiali/src/pages/ServiceList/ServiceListPage.tsx
plugins/kiali/src/pages/WorkloadDetails/WorkloadPods.tsx
plugins/kiali/src/pages/WorkloadDetails/WorkloadsDescription.tsx
plugins/kiali/src/pages/WorkloadList/WorkloadListPage.tsx
plugins/kiali/src/styles/StyleUtils.ts

Improved styles for tables: 
Before:

feat(kiali): sticky headers for tables

---

plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleCard.tsx
plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleDrawer.tsx

Fixes:
https://issues.redhat.com/browse/RHTAPBUGS-1251
Description:
Ensuring that long commit messages do not spill over within the application. For the Card view, messages are truncated with an added tooltip. For the Drawer (Side panel) view, messages are split onto new lines.
Screenshots:
1. Card View
2. Side Panel View
CC: @karthikjeeyar

fix(argocd): fix argocd commit message visibility

---

plugins/rbac/dev/index.tsx
plugins/rbac/src/components/ConditionalAccess/ConditionalAccessSidebar.tsx
plugins/rbac/src/components/ConditionalAccess/ConditionsForm.test.tsx
plugins/rbac/src/components/ConditionalAccess/ConditionsForm.tsx
plugins/rbac/src/components/ConditionalAccess/ConditionsFormRow.tsx
plugins/rbac/src/components/ConditionalAccess/ConditionsFormRowFields.tsx
plugins/rbac/src/components/ConditionalAccess/CustomArrayField.tsx
plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.test.tsx
plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
plugins/rbac/src/components/CreateRole/RoleForm.tsx

[RHIDP-3038](https://issues.redhat.com/browse/RHIDP-3038): [RBAC] conditional Side bar styles are not changing for dark theme
How to test:
1. Pull this PR to your local plugins repo
2. Go to `plugins/rbac` and run `yarn export-dynamic`
3. At your local showcase directory, go to `dynamic-plugins-root/` and run
```
pkg=../../backstage-plugins/plugins/rbac
archive=$(npm pack $pkg)
tar -xzf "$archive" && rm "$archive"
mv package $(echo $archive | sed -e 's:\.tgz$::')
``` 
4. Go to `packages/backend/package.json` and update rbac backend version to `"@janus-idp/backstage-plugin-rbac-backend": "4.3.2"` as current rbac plugin only works with the latest rbac backend version.
5. Go to showcase root directory and run `yarn install` and `yarn start` to start backstage-showcase
Screen …

fix(rbac): background color of sidebar in dark theme

---

plugins/quay/dev/__data__/labels.ts
plugins/quay/dev/__data__/manifest_digest.ts
plugins/quay/dev/__data__/security_vulnerabilities.ts
plugins/quay/dev/__data__/tags.ts
plugins/quay/dev/index.tsx
plugins/quay/src/types.ts
plugins/quay/tests/quay.spec.ts

**Fixes:**
https://issues.redhat.com/browse/RHIDP-2589
**Description**:
Quay plugin dev-mode expects the users to run the backend to fetch the actual data, this can be tricky with the localsetup as they have to modify the quay endpoint to point to `quay.io` in app.config.yaml. Other plugins use mock data to power this dev mode, similarly this PR adds mock data for quay dev mode.
1. Navigate to `plugins/quay` directory and run `yarn start`
2. run `yarn ui-test`
**To see the test report:** 
run `yarn playwright show-report`
cc: @jrichter1 @ciiay

fix(quay): add mock data to quay dev mode tests

---

plugins/rbac-backend/package.json
plugins/rbac/package.json
yarn.lock

Updates the `rbac-common` plugin dependency for the `rbac` and `rbac-backend` plugins.
Also runs `yarn install` to fix the `After 'yarn install', workspace is dirty! The following files have changed:` error.

chore(deps): update rbac deps

---

yarn.lock

Fixes:
yarn.lock file is out of sync, this PR fixes the dirty yarn.lock file.

chore(deps): fix dirty yarn.lock file

---

plugins/rbac-backend/docs/apis.md
plugins/rbac-backend/docs/conditions.md

Fixes RBAC API url: `api/plugins/condition-rules` -> `api/permission/plugins/condition-rules`.

docs(rbac): fix condition rules api url

---

.github/renovate.json

Fixes: https://issues.redhat.com/browse/RHIDP-2699
* Re-enabled Renovate to create PRs
* Limit PR creation.  Grouping are now based on the following:
*  Test/devdependencies are managed by RHDH for _all_ plugins
*  Additional package rules are used to group monorepo related PRs (material-ui, react, babel, storybook, linters).  These will be managed by RHDH
*  Dependencies are expected to be managed by the respective plugin owner teams
* All major bumps require dashboard approval
* Removed the Notifications rule since those plugins now live upstream
*Note: Major rules are specified in order to organize the dashboard view.  It's not expected that teams will make batch updates to a set of unrelated packages at the same time so it's just informational.   For example, compare the [test repo …

chore(renovate): rework config

---

.github/workflows/pr-playwright.yaml

UI tests don't seem to need the backend process running anymore, and it keeps crashing.
Removing so it doesn't fail the action.

fix: remove crashing process from playwright tests

---

plugins/acr/package.json
plugins/rbac-backend/package.json

Two part PR, first downgrade `shared-react` so that we can try to get a release going. Second, move `"@backstage/backend-test-utils"` to devDependencies in the RBAC backend plugin

fix(deps): move backend-test-utils to devDependencies

---

plugins/rbac-backend/docs/apis.md

Adds example cURL command for nested conditional policies.

docs(rbac): add curl request examples

---

.github/renovate.json

- prevent immortal PRs from re-opening
- only create prs if tests pass

Update renovate to manage the noise

---

plugins/argocd/README.md

Updates the Argocd plugin's installation guide to include the new backend system.
Argocd backend plugin still uses old backend system, so we are using a `legacyPlugin` wrapper to make the backend plugin work at the moment.
cc: @rohitkrai03

docs(argocd): update argocd configuration documentation

---

plugins/quay/README.md

Fixes: 
https://github.com/janus-idp/backstage-plugins/issues/1901
This PR adds more context around the new optional credential settings in the backstage 1.28 to explain different settings available to the users. 
See Backstage 1.28 release notes about the `BREAKING: Proxy backend plugin protected by default` -
https://github.com/backstage/backstage/releases/tag/v1.28.0
> [!Note]
> Quay plugin works without any additional changes in the  `app.config.yaml` for the existing users.
/cc @kim-tsao @rohitkrai03

docs(quay): add documentation for the new credential settings in proxy backend

---

plugins/rbac-backend/docs/permissions.md
plugins/tekton-common/.eslintrc.js
plugins/tekton-common/README.md
plugins/tekton-common/package.json
plugins/tekton-common/src/index.ts
plugins/tekton-common/src/permissions.ts
plugins/tekton-common/tsconfig.json
plugins/tekton-common/turbo.json
plugins/tekton/dev/index.tsx
plugins/tekton/package.json
plugins/tekton/src/components/PipelineRunList/PipelineRunList.test.tsx
plugins/tekton/src/components/PipelineRunList/PipelineRunRowActions.tsx
plugins/tekton/src/components/PipelineRunList/__tests__/PipelineRunRowActions.test.tsx
plugins/tekton/src/components/Tekton/TektonCIComponent.test.tsx
plugins/tekton/src/components/Tekton/TektonCIComponent.tsx
plugins/tekton/src/components/common/PermissionAlert.tsx
plugins/tekton/src/hooks/useTektonViewPermission.ts
yarn.lock

**Fixes:**
https://issues.redhat.com/browse/RHIDP-1793
This PR adds support for RBAC permission in tekton plugin. `tetkon.view.read` Permission allows the user view the tekton plugin component and `kubernetes.proxy` permission allow the user to view the logs. If the `kubernetes.proxy` permission is not available then the `view logs` action is disabled with `Unauthorized to view logs` tooltip.
---
**Without `tekton.view.read`  Permission:**
**With `tekton.view.read`  Permission and without `kubernetes.proxy` permission logs action is disabled with tooltip:**
---
**With  `tekton.view.read` and `kubernetes.proxy`  permission:**
---
1. [Configure the Tekton plugin](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/tekton#configu …

feat(tekton): add permissions support for tekton plugin

---

plugins/argocd-common/.eslintrc.js
plugins/argocd-common/README.md
plugins/argocd-common/package.json
plugins/argocd-common/src/index.ts
plugins/argocd-common/src/permissions.ts
plugins/argocd-common/tsconfig.json
plugins/argocd-common/turbo.json
plugins/argocd/dev/index.tsx
plugins/argocd/package.json
plugins/argocd/src/components/Common/PermissionAlert.tsx
plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycle.tsx
plugins/argocd/src/components/DeploymentLifeCycle/__tests__/DeploymentLifecycle.test.tsx
plugins/argocd/src/components/DeploymentSummary/DeploymentSummary.tsx
plugins/argocd/src/components/DeploymentSummary/__tests__/DeploymentSummary.test.tsx
plugins/argocd/src/hooks/useArgocdViewPermission.ts
plugins/argocd/src/plugin.test.tsx
plugins/rbac-backend/docs/permissions.md

**Fixes:**
https://issues.redhat.com/browse/RHIDP-1796
This PR adds support for RBAC permission in argocd plugin. `argocd.view.read` Permission allows the user view the argocd plugin components in overview and CD tabs.
---
**Without `argocd.view.read`  Permission:**
**With `argocd.view.read`  Permission**
---
1. [Configure the Argocd plugin](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/argocd#configuration) and add Github integration.
2. Create a policy file `rbac.csv` for the permission policies
```
g, user:default/<YOUR_USERNAME>, role:default/argocd-viewer
p, role:default/argocd-viewer, argocd.view.read, read, allow
p, role:default/argocd-viewer, catalog-entity.read, read, allow
p, role:default/argocd-viewer, …
```

feat(argocd): add permission support for argocd

---

plugins/argocd-common/package.json

Remove the private field now that the argocd-common plugin has been released

chore(release): remove private from manually released argocd-common

---

plugins/argocd-common/README.md
plugins/argocd/package.json

Fixes two issues that we are facing with the argocd plugin.
First, the argocd-common plugin has not had a `1.0.0` release, setting the release back to `0.1.0`
Second, the argocd plugin keeps updating to the argocd-common version `1.0.0`, so included is a minor nit fix to get the argocd-common plugin to update

fix(argocd): fix argocd naming

---

plugins/argocd/package.json

The release bot created [commit](https://github.com/janus-idp/backstage-plugins/commit/6405cf54a1ad2a5875964ecb4217dbd45bd5552c) overwrote the "@janus-idp/backstage-plugin-argocd-common" version updated in #1990  and it causes CI check failures.

fix: argocd dependency package version

---

plugins/acr/package.json

Release process failed mid way through causing the acr plugin to get an update to the shared-react dependency but the shared-react plugin did not get released. Downgrades the dependency in an attempt to get it to re-release

fix(deps): downgrade shared-react in acr

---

plugins/rbac-backend/src/service/plugin-endpoint.test.ts
plugins/rbac-backend/src/service/plugin-endpoints.ts

Log whenever a plugin captured by the RBAC Backend plugin does not have permissions.
[RHIDP-2059](https://issues.redhat.com/browse/RHIDP-2059)

fix(rbac): log when plugin has no permissions

---

plugins/rbac-backend/src/service/policies-rest-api.test.ts
plugins/rbac-backend/src/validation/policies-validation.test.ts
plugins/rbac-backend/src/validation/policies-validation.ts
plugins/rbac-common/src/types.ts

Adds validation to the policy section of permission policies. The only allowed terms that can be used are create, read, update, delete, and our RBAC specific keyword use.
Closes #996.

fix(rbac): add additional validation for permission policies

---

plugins/bulk-import/src/components/PreviewFile/KeyValueTextField.tsx
plugins/bulk-import/src/components/PreviewFile/PreviewFile.tsx
plugins/bulk-import/src/components/PreviewFile/PreviewPullRequest.tsx
plugins/bulk-import/src/types.ts
plugins/bulk-import/src/utils/repository-utils.test.tsx
plugins/bulk-import/src/utils/repository-utils.tsx

For [RHIDP-2927](https://issues.redhat.com//browse/RHIDP-2927)
https://github.com/user-attachments/assets/6e7c3357-19aa-4884-b376-b4aea167dfce

feat(bulk-import): add fields for annotations, labels and spec input

---

plugins/rbac/src/__fixtures__/mockConditions.ts
plugins/rbac/src/components/ConditionalAccess/AddNestedConditionButton.tsx
plugins/rbac/src/components/ConditionalAccess/ComplexConditionRow.tsx
plugins/rbac/src/components/ConditionalAccess/ComplexConditionRowButtons.tsx
plugins/rbac/src/components/ConditionalAccess/ConditionRule.tsx
plugins/rbac/src/components/ConditionalAccess/ConditionalAccessSidebar.tsx
plugins/rbac/src/components/ConditionalAccess/ConditionsForm.test.tsx
plugins/rbac/src/components/ConditionalAccess/ConditionsForm.tsx
plugins/rbac/src/components/ConditionalAccess/ConditionsFormRow.tsx
plugins/rbac/src/components/ConditionalAccess/ConditionsFormRowFields.tsx
plugins/rbac/src/components/ConditionalAccess/CriteriaToggleButton.tsx
plugins/rbac/src/components/ConditionalAccess/const.ts
plugins/rbac/src/components/ConditionalAccess/types.ts
plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
plugins/rbac/src/hooks/usePermissionPolicies.test.ts
plugins/rbac/src/utils/conditional-access-utils.test.ts
plugins/rbac/src/utils/conditional-access-utils.ts
plugins/rbac/src/utils/create-role-utils.test.ts
plugins/rbac/src/utils/create-role-utils.ts
plugins/rbac/src/utils/rbac-utils.test.ts
plugins/rbac/src/utils/rbac-utils.ts
plugins/rbac/tests/rbac.spec.ts

For [RHIDP-2553](https://issues.redhat.com/browse/RHIDP-2553): Add support for creating nested conditions
Screen recording(updated on 7/1):
https://github.com/janus-idp/backstage-plugins/assets/26255262/7127740e-e988-43e2-a5da-df621e2d0b1d
Screenshot for multiple level nested condition warning message(updated on 8/5):
<details>
<summary>Demo: (uploaded on 8/2)</summary>
https://github.com/user-attachments/assets/f13211db-59c3-4253-8fd7-8726b7196b0e
</details>

feat(rbac): nested condition

---

plugins/aap-backend/package.json

Reverts the downgrade for the `janus-cli` dependency in the AAP plugin.

fix(aap): revert downgrade of janus-cli

---

packages/cli/package.json

MSR doing MSR things, reverts the "upgrade" from `1.0.0` back to `1.13.0` that MSR attempted.

chore(release): fix downgrade of janus-cli

---

plugins/lightspeed/package.json

Some more of MSR doing big things, reverts another "upgrade" attempt from `1.0.0` to `1.0.1` of the lightspeed plugin.

chore(release): fix downgrade of lightspeed

---

plugins/bulk-import/src/components/PreviewFile/PreviewPullRequest.tsx
plugins/bulk-import/src/utils/repository-utils.tsx

Found this bug when testing #2013 .
Fixes: [RHIDP-3553](https://issues.redhat.com/browse/RHIDP-3533)
Annotations, Labels, and Spec text field will have initial values as shown in Preview entities section.
https://github.com/user-attachments/assets/f09c68dc-06bd-41ba-9db9-e7dae94a62af

fix(bulk-import): set initial value of annotations, labels and specs

---

plugins/acr/README.md
plugins/acr/src/api/index.ts
plugins/acr/src/plugin.ts
plugins/quay/README.md

Fixes: https://issues.redhat.com/browse/RHIDP-3592 
This PR updated the credentials to be passed for the proxy and added more context around the new optional credential settings in the backstage 1.28 to explain different settings available to the users.
See Backstage 1.28 release notes about the BREAKING: Proxy backend plugin protected by default -
https://github.com/backstage/backstage/releases/tag/v1.28.0

fix(acr): new credential settings in proxy backend

---

plugins/argocd/README.md
plugins/argocd/dev/index.tsx
plugins/argocd/src/api/__tests__/index.test.ts
plugins/argocd/src/api/index.ts
plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycle.tsx
plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleCard.tsx
plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleDrawer.tsx
plugins/argocd/src/components/DeploymentLifeCycle/__tests__/DeploymentLifecycle.test.tsx
plugins/argocd/src/components/DeploymentSummary/DeploymentSummary.tsx
plugins/argocd/src/components/DeploymentSummary/__tests__/DeploymentSummary.test.tsx
plugins/argocd/src/hooks/__tests__/useApplications.test.ts
plugins/argocd/src/hooks/useApplications.ts
plugins/argocd/src/utils/__tests__/utils.test.ts
plugins/argocd/src/utils/isArgocdConfigured.ts
plugins/argocd/src/utils/utils.ts

https://issues.redhat.com/browse/RHTAP-2849
Add support  to fetch only the application thats matches the name defined in  `argocd/app-name` annotation.
1. Add a Gitops Application in a namespace
2. Use the following annotation to fetch that single application in Argo CD plugin
```yaml
metadata:
annotations:
....
argocd/app-name: quarkus-app
```
cc: @rohitkrai03

feat(argocd): add support for fetching an application by app name

---

plugins/orchestrator/package.json
plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.tsx
plugins/orchestrator/src/components/ExecuteWorkflowPage/JsonTextAreaForm.tsx
plugins/orchestrator/src/components/ExecuteWorkflowPage/StepperForm.tsx
plugins/orchestrator/src/components/InfoDialog.stories.tsx
plugins/orchestrator/src/components/InfoDialog.tsx
plugins/orchestrator/src/components/OrchestratorIcon.tsx
plugins/orchestrator/src/components/Paragraph.tsx
plugins/orchestrator/src/components/Selector.tsx
plugins/orchestrator/src/components/SubmitButton.tsx
plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionDetailsCard.tsx
plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionViewerPage.tsx
plugins/orchestrator/src/components/WorkflowDescriptionModal.tsx
plugins/orchestrator/src/components/WorkflowDialog.tsx
plugins/orchestrator/src/components/WorkflowInstancePage.tsx
plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
plugins/orchestrator/src/components/WorkflowInstanceStatusIndicator.tsx
plugins/orchestrator/src/components/WorkflowProgressNode.tsx
plugins/orchestrator/src/components/WorkflowRunDetails.stories.tsx
plugins/orchestrator/src/components/WorkflowRunDetails.tsx
plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx
plugins/orchestrator/src/components/WorkflowVariablesViewer.tsx
plugins/orchestrator/src/components/WorkflowsTabContent.tsx
plugins/orchestrator/src/components/WorkflowsTable.tsx
plugins/orchestrator/src/components/ui/OverrideBackstageTable.tsx
plugins/orchestrator/src/hooks/useWorkflowInstanceStatusColors.ts
yarn.lock

Revert https://github.com/janus-idp/backstage-plugins/pull/1727
Upgrade to material 5 proved to be none compatible with the dark theme. 
The only solution was to downgrade back to material 4. 
This also resolves issue of workflow run details not showing spaces correctly between fields
In addition, moved @rjsf and @material dependencies to peerDependencies to avoid conflicting versions.
Made the change only in 1.2.x branch, since main branch will be maintained in community plugins repo and we are still in the process of moving there.
resolves:
[FLPATH-1504](https://issues.redhat.com/browse/FLPATH-1504)
[FLPATH-1505](https://issues.redhat.com/browse/FLPATH-1505)
[FLPATH-1506](https://issues.redhat.com/browse/FLPATH-1506)
[FLPATH-1507](https://issues.redhat.com/browse/FLPATH-1507)

fix(orchestrator): revert upgrade to material 5 to resolve dark theme issues

---

plugins/rbac/src/__fixtures__/mockConditions.ts
plugins/rbac/src/components/ConditionalAccess/ConditionsForm.tsx
plugins/rbac/src/components/ConditionalAccess/ConditionsFormRow.tsx
plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
plugins/rbac/src/utils/conditional-access-utils.ts
plugins/rbac/tests/rbac.spec.ts

For [RHIDP-2554](https://issues.redhat.com/browse/RHIDP-2554)
https://github.com/user-attachments/assets/938034c4-fad5-481c-98c4-4e023a637920

feat(rbac): edit nested conditions

---

packages/cli/src/commands/export-dynamic-plugin/backend-utils.ts

This is as a result of a new [change](https://backstage.io/docs/reference/backend-plugin-api.createbackendmodule) where createBackendModule() now returns `BackendFeatureCompat`, which can have a call signature/ can be a function. This change allows both the old and new behaviour to be recognized as valid backend features. 
Fixes [RHIDP-2529](https://issues.redhat.com/browse/RHIDP-2529)
* More details on the error in the issue
Tested this change locally and can confirm that the `yarn export-dynamic` cli now succeeds with no errors

fix(cli): support BackendFeatureCompat in export-dynamic cli

---

plugins/ocm/src/components/ClusterContext/ClusterContext.test.tsx
plugins/ocm/src/components/ClusterContext/ClusterContext.tsx

This is a temporary fix to not call OCM on `entity.page.overview` mount for entities without `isType: kubernetes-cluster`.
Will need to sync with someone from dynamic plugins about context mounting, as `if` is supported only for `cards`.
https://issues.redhat.com/browse/RHIDP-2438

fix(ocm): call OCM only for kubernetes-cluster entities

---

plugins/bulk-import-backend/api-docs/Models/Organization.md
plugins/bulk-import-backend/src/openapi.d.ts
plugins/bulk-import-backend/src/openapidocument.ts
plugins/bulk-import-backend/src/schema/openapi.yaml
plugins/bulk-import-backend/src/service/githubApiService.ts
plugins/bulk-import-backend/src/service/handlers/organizations.ts
plugins/bulk-import-backend/src/service/router.test.ts
plugins/bulk-import-backend/src/service/router.ts
plugins/bulk-import-backend/src/types.ts

This PR adds a new `totalRepoCount` field in each item in the `GET /organizations` response.
This is needed in the related frontend plugin to show the users how many repos have been already selected from all the repos in that org:
Fixes https://issues.redhat.com/browse/RHIDP-3337
- Add at least one GitHub integration - see https://github.com/janus-idp/backstage-plugins/tree/main/plugins/bulk-import-backend#usage
- Start the bulk import backend:
```
yarn workspace @janus-idp/backstage-plugin-bulk-import-backend run start
```
- Example request and response:
```
$ http GET http://localhost:7007/api/bulk-import-backend/organizations …
```

feat(bulk-import): return the total count of repos per org in the `GET /organizations` backend API [RHIDP-3337]

---

plugins/ocm-backend/CONTRIBUTING.md
plugins/ocm/CONTRIBUTING.md

Fixes outdated instruction to start development environment for OCM backend plugin.

docs(ocm): fix instruction to start dev backend

---

plugins/feedback-backend/dist-dynamic/package.json
plugins/feedback-backend/dist-dynamic/yarn.lock
plugins/feedback-backend/package.json
plugins/feedback/package.json
plugins/kiali-backend/dist-dynamic/package.json
plugins/kiali-backend/dist-dynamic/yarn.lock
plugins/kiali-backend/package.json
plugins/kiali/package.json
plugins/matomo/package.json
plugins/orchestrator-backend/dist-dynamic/package.json
plugins/orchestrator-backend/dist-dynamic/yarn.lock
plugins/orchestrator-common/package.json
plugins/orchestrator-form-react/package.json
plugins/orchestrator/package.json
plugins/orchestrator/src/api/OrchestratorClient.test.ts
plugins/orchestrator/src/api/OrchestratorClient.ts
plugins/servicenow-actions/dist-dynamic/package.json
plugins/servicenow-actions/dist-dynamic/yarn.lock
plugins/servicenow-actions/package.json
yarn.lock

Based on #2051 
Updates axios to 1.7.4 in other plugins as well.
Updates Orchestrator tests to unify use of a single axios instance through-out the jest tests.

fix(deps): update dependency axios to v1.7.4 [security]

---

plugins/bulk-import-backend/src/service/githubApiService.ts
plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
plugins/bulk-import-backend/src/service/router.test.ts

The `POST /imports` endpoint supports a `dryRun` parameter, which currently only checks if the specified entities do exist in the catalog. It won't attempt to create any PRs in the specified repos.
This PR adds additional checks:
- if the repo already has a catalog-info YAML file in its default branch; it adds a new possible error string: `CATALOG_INFO_FILE_EXISTS_IN_REPO`
- if the repo is empty; it adds a new possible error string: `REPO_EMPTY`
- if the repo does not have a `.github/CODEOWNERS` file, it adds a new possible error string: `CODEOWNERS_FILE_NOT_FOUND_IN_REPO`
This is needed to improve the related frontend plugin.
**BREAKING CHANGES**:
- The error when the specified entity already exists in the catalog has been renamed from …

feat(bulk-import): perform more dry-run checks in the `POST /imports` backend endpoint [RHIDP-3339]

---

plugins/bulk-import-backend/CONTRIBUTING.md
plugins/bulk-import-backend/README.md
plugins/bulk-import-backend/api-docs/Apis/ImportApi.md
plugins/bulk-import-backend/api-docs/Apis/ManagementApi.md
plugins/bulk-import-backend/api-docs/Apis/OrganizationApi.md
plugins/bulk-import-backend/api-docs/Apis/RepositoryApi.md
plugins/bulk-import-backend/api-docs/README.md
plugins/bulk-import-backend/dev/index.ts
plugins/bulk-import-backend/package.json
plugins/bulk-import-backend/src/helpers/auth.ts
plugins/bulk-import-backend/src/openapidocument.ts
plugins/bulk-import-backend/src/plugin.test.ts
plugins/bulk-import-backend/src/plugin.ts
plugins/bulk-import-backend/src/schema/openapi.yaml
plugins/bulk-import-backend/src/service/router.test.ts
plugins/bulk-import-backend/src/service/router.ts
plugins/rbac-backend/docs/permissions.md

This PR adds RBAC support to the bulk-import backend plugin API endpoints.
Only admins and users with the `bulk.import` permission have access to the bulk import backend API endpoints.
Fixes https://issues.redhat.com/browse/RHIDP-1208
Note that the [`GET /ping` endpoint](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/bulk-import-backend/api-docs/Apis/ManagementApi.md#ping) is unauthenticated and does not enforce any permission.
All the other endpoints should check for the `bulk.import` permission.
- [Configure](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/bulk-import-backend#bulk-import-backen …

feat(bulk-import): add permissions support to the backend endpoints [RHIDP-1208]

---

plugins/audit-log-node/package.json
plugins/rbac-backend-module-test/dist-dynamic/package.json
plugins/rbac-backend-module-test/dist-dynamic/yarn.lock
plugins/rbac-backend-module-test/package.json
yarn.lock

`yarn tsc` problem due to `@janus-idp/backstage-plugin-rbac-node` not being updated to `1.5.0` in `@janus-idp/backstage-plugin-rbac-backend-module-test`.
MSR upgraded the `@janus-idp/backstage-plugin-audit-log-node` plugin by downgrading it. Can be seen [here](https://github.com/janus-idp/backstage-plugins/commit/8f8ad354aec4fc40d46bb64fc69f2b0a19b663fd).
cc @nickboldt @AndrienkoAleksandr

chore(release): fix some issues caused by msr

---

plugins/bulk-import-backend/api-docs/Models/ImportRequest.md
plugins/bulk-import-backend/src/openapi.d.ts
plugins/bulk-import-backend/src/openapidocument.ts
plugins/bulk-import-backend/src/schema/openapi.yaml
plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
plugins/bulk-import-backend/src/service/router.test.ts

This PR is an addendum to https://github.com/janus-idp/backstage-plugins/pull/1979
Currently, the dry-run operation always checks for the presence of a CODEOWNERS file. We want to skip this check if the client does not request it explicitly.
This is needed in the UI. Otherwise, the UI will not allow creating a bulk import PR even if the user did not select the checkbox to use the CODEOWNERS file as entity owner.
To support this, a new `codeOwnersFileAsEntityOwner` field has been added to each item in the ImportRequest object.
ref https://issues.redhat.com/browse/RHIDP-3339
/cc @debsmita1 @ciiay

feat(bulk-import): allow skipping the CODEOWNERS dry-run check [RHIDP-3339]

---

plugins/bulk-import-backend/src/helpers/catalogInfoGenerator.test.ts
plugins/bulk-import-backend/src/helpers/catalogInfoGenerator.ts
plugins/bulk-import-backend/src/helpers/pagination.ts
plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
plugins/bulk-import-backend/src/service/handlers/importStatus.ts
plugins/bulk-import-backend/src/service/handlers/repositories.ts
plugins/bulk-import-backend/src/service/router.test.ts
plugins/bulk-import-backend/src/service/router.ts

This PR improves the overall bulk-import user experience by improving the performance of the `GET /imports` endpoint.
It should also fix the issue where the list of imports returned would sometimes not be accurate (some repositories just imported would not show up in this list depending on the page and size requested).
Before this PR, listing imports would take several seconds (and even more depending on the number of repositories accessible from the GH integrations). Example below where it took **~35 seconds** to return a response:
```
$ time http -A bearer -a "${ADMIN_CURL_TOKEN}" GET http://localhost:7007/api/bulk-import/imports pagePerIntegration==1 sizePerIntegration==10000
[
{
"approvalTool": "GIT",
"id": …
```

feat(bulk-import): improve performance of the `GET /imports` endpoint [RHIDP-3680]

---

plugins/3scale-backend/README.md
plugins/3scale-backend/package.json

Jira Issue: https://issues.redhat.com/browse/RHIDP-3544
The `3scale-backend` plugin has been migrated to the [backstage/community-plugins](https://github.com/backstage/community-plugins/tree/main/workspaces/redhat-argocd/plugins) repository in support of our [sunsetting](https://issues.redhat.com/browse/RHIDP-3227) efforts.
This Pull Request is adding a note within the [backstage-plugins](https://github.com/janus-idp/backstage-plugins/tree/main/plugins) repository about the `3scale-backend` plugin being deprecated. It is also setting the package.json files to private "private": true, to prevent accidental publishing of deprecated plugin.

chore: add deprecate note to the 3scale plugin

---

plugins/rbac-backend/src/validation/policies-validation.test.ts
plugins/rbac-backend/src/validation/policies-validation.ts
plugins/rbac/src/api/RBACBackendClient.ts
plugins/rbac/src/components/CreateRole/AddedMembersTable.test.tsx
plugins/rbac/src/components/CreateRole/AddedMembersTableColumn.tsx
plugins/rbac/src/components/CreateRole/RoleForm.tsx
plugins/rbac/src/components/EditRole.test.tsx
plugins/rbac/src/components/EditRole.tsx
plugins/rbac/src/components/RoleOverview/MembersCard.tsx
plugins/rbac/src/components/RoleOverview/PermissionsCard.tsx
plugins/rbac/src/components/RolesList/RolesListColumns.tsx
plugins/rbac/src/hooks/useMembers.ts
plugins/rbac/src/utils/rbac-utils.test.ts
plugins/rbac/src/utils/rbac-utils.ts

Creating role with name that contains ':' or '/' creates role that can't be used.
Invalidate names that does not conform with format:
- Strings of length at least 1, and at most 63
- Must consist of sequences of [a-z0-9A-Z] possibly separated by one of [-_.]
Invalidate namespaces that does not conform with format:
- must be sequences of [a-zA-Z0-9], possibly separated by -, at most 63 characters in total.  
Deletes function `getKindNamespaceName` and uses instead more robust `parseEntityRef`. This change was originally introduced to support `:`, can be reverted.
Reference:
https://backstage.io/docs/features/software-catalog/descriptor-format/#name-required
https://issues.redhat.com/browse/RHIDP-3580

fix(rbac): validate name and namespace of entities

---

plugins/orchestrator-common/src/constants.ts

use latest sonataflow nightly container image available in quay.io.

chore(orchestrator): bump default sonata image version to 2024-04-17

---

plugins/tekton/package.json
plugins/topology/package.json

Fixes:
https://issues.redhat.com/browse/RHIDP-3710, https://issues.redhat.com/browse/RHIDP-3466
**Description:** 
The sideEffects key in a package.json file is used to inform bundlers like Webpack about the presence of side effects in your code. This key plays a crucial role in optimizing the bundle size during the build process by enabling tree shaking, which is the process of eliminating unused code from the final bundle.
In the context of JavaScript, a side effect refers to any operation or code that affects something outside its scope, such as modifying a global variable, performing I/O operations, or altering the DOM. Pure functions, on the other hand, have no side effects—they return the same output given the same input and do not alter external states.
With sideEffects false, …

fix(topology): fixes custom styles loading

---

plugins/bulk-import-backend/README.md
plugins/bulk-import-backend/dist-dynamic/package.json
plugins/bulk-import-backend/dist-dynamic/yarn.lock
plugins/bulk-import-backend/package.json
plugins/bulk-import-backend/src/helpers/auditLogUtils.ts
plugins/bulk-import-backend/src/helpers/auth.ts
plugins/bulk-import-backend/src/service/router.ts

This PR adds audit log to the bulk-import backend router.
Fixes https://issues.redhat.com/browse/RHIDP-2748
See https://github.com/rm3l/janus-idp-backstage-plugins/blob/RHIDP-2748--audit-log-bulk-import-backend/plugins/bulk-import-backend/README.md?rgh-link-date=2024-08-27T08%3A06%3A14Z#audit-logging for a complete description of the event names sent by the Bulk Import Backend. The event names are prefixed with `BulkImport`, as now recommended (https://github.com/janus-idp/backstage-plugins/pull/2090).
You can also check the backend logs after sending out a request to any of the Bulk Import Backend API endpoints, e.g.:
``` …
```

feat(bulk-import): add audit log to the backend router [RHIDP-2748]

---

plugins/orchestrator-form-react/CHANGELOG.md
plugins/orchestrator-form-react/package.json

This reverts commit 5698cc55368bc966bbb3408fe80c498755dae800.
Erroneous downgrade of `@janus-idp/backstage-plugin-orchestrator-common` and `@janus-idp/backstage-plugin-orchestrator-form-api`

fix(orchestrator): revert "chore(release): 1.0.0 [skip ci]"

---

plugins/orchestrator-backend/src/service/api/v1.ts
plugins/orchestrator-backend/src/service/api/v2.ts
plugins/orchestrator-backend/src/service/router.ts
plugins/orchestrator/src/api/MockOrchestratorClient.ts
plugins/orchestrator/src/api/OrchestratorClient.test.ts
plugins/orchestrator/src/api/OrchestratorClient.ts
plugins/orchestrator/src/api/api.ts

Use v2 endpoints in orchestrator plugin UI for aborting workflows.
Warning: This DELETES corresponding v1 endpoints.

feat(orchestrator): use v2 endpoint for abortWorkflow

---

plugins/shared-react/package.json

Fixes:
https://issues.redhat.com/browse/RHTAPBUGS-1310
Description:
with sideEffects property to set to false, CSS files are not ignored by webpack tree-shaking.  This PR adds css to the webpack builds.
custom css are supported loaders for backstage https://backstage.io/docs/tooling/cli/build-system/#loaders
https://webpack.js.org/guides/tree-shaking/ 
Screenshots:
**Tekton Plugin:** 
**Before:**
**After:**
---
**Topology Plugin:** 
**Before:**
**After:**
cc: @invincibleJai

fix(shared-react): include css files in shared react folder

---

plugins/rbac-backend/src/file-permissions/csv-file-watcher.test.ts
plugins/rbac-backend/src/file-permissions/csv-file-watcher.ts
plugins/rbac-backend/src/file-permissions/file-watcher.ts
plugins/rbac-backend/src/file-permissions/yaml-conditional-file-watcher.test.ts
plugins/rbac-backend/src/file-permissions/yaml-conditional-file-watcher.ts
plugins/rbac-backend/src/service/permission-policy.ts

Clean up RBAC conditional policies, permission policies, roles from files after removing external files from configuration
https://issues.redhat.com/browse/RHIDP-3601

fix(rbac): clean up policies when policies files are detached

---

plugins/audit-log-node/package.json

This reverts commit dddb1021c6ad1131ff7ba33b4d2f0762e54df4f0.
For some reason, the MSR process downgraded `@janus-idp/backstage-plugin-audit-log-node` from 1.4.0 to 1.0.0, causing dirty `yarn.lock` issues in PRs.
Fixes https://issues.redhat.com/browse/RHIDP-3824
/cc @nickboldt @schultzp2020 @PatAKnight @AndrienkoAleksandr

chore(release): revert version downgrade of `@janus-idp/backstage-plugin-audit-log-node` from 1.4.0 to 1.0.0

---

plugins/orchestrator-backend/src/service/api/v1.ts
plugins/orchestrator-backend/src/service/api/v2.test.ts
plugins/orchestrator-backend/src/service/api/v2.ts
plugins/orchestrator-backend/src/service/router.ts
plugins/orchestrator/src/api/MockOrchestratorClient.ts
plugins/orchestrator/src/api/OrchestratorClient.test.ts
plugins/orchestrator/src/api/OrchestratorClient.ts
plugins/orchestrator/src/api/api.ts
plugins/orchestrator/src/components/WorkflowEditor/WorkflowEditor.tsx

Use v2 endpoints in orchestrator plugin UI for getting workflow source.
Warning: This DELETES corresponding v1 endpoints.

feat(orchestrator): use v2 endpoint fot getWorkflowSource

---

plugins/bulk-import-backend/package.json
plugins/kiali/dev/index.tsx
plugins/kiali/src/components/Logos/Logos.tsx
plugins/kiali/src/components/MTls/MTLSIcon.tsx
yarn.lock

close #1527
---
I don't know why `require` assets are not transformed by backstage's build config, and `kiali` is not included in `app`, so `/// <reference types="@backstage/cli/asset-types" />` must be add somewhere in the plugin itself, so I add it in `plugins/kiali/dev/index.tsx`, after this change all assets are included in `dist/assets` correctly now.

fix(kiali): assets missing in dist

---

plugins/bulk-import-backend/catalog-info.yaml

Introduces OpenApi definition.
To see swagger endpoints, add to `app-config.local.yaml`:
```
- type: file
target: ../../plugins/bulk-import-backend/catalog-info.yaml
```
(Or use url once merged.)
[RHIDP-3797](https://issues.redhat.com/browse/RHIDP-3797)

feat(bulk-import): introduce api catalog info

---

plugins/bulk-import-backend/dist-dynamic/package.json
plugins/bulk-import-backend/dist-dynamic/yarn.lock
plugins/bulk-import-backend/package.json
plugins/bulk-import/package.json
plugins/orchestrator-form-react/package.json
yarn.lock

For some reason the release started to fail for `@janus-idp/backstage-plugin-bulk-import-backend-dynamic` after the audit log [PR](https://github.com/janus-idp/backstage-plugins/pull/1966) was merged. Failed release can be found [here](https://github.com/janus-idp/backstage-plugins/actions/runs/10581736766/job/29319768586).
To hopefully fix this, I moved `@janus-idp/backstage-plugin-audit-log-node` from a dependency to a peerDependency. I got the inspiration from the [Orchestrator backend plugin](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/orchestrator-backend/package.json#L112). 
@rm3l I am not 100% on if this is the actual problem or not but figure that I could open this PR and we could discuss it here.
Also, included in the PR is a fix for some of the other plugins …

chore(deps): move audit log dep to peerDependencies

---

plugins/bulk-import-common/package.json

Again with the downgrade of a plugin by MSR. Here is a PR to revert and fix the release.
@AndrienkoAleksandr this downgrade caused your fix to fail to release.

chore(release): revert downgrade of bulk import common

---

plugins/rbac-backend/package.json
plugins/rbac-backend/src/database/casbin-adapter-factory.test.ts
plugins/rbac-backend/src/database/casbin-adapter-factory.ts
plugins/rbac-backend/src/service/policy-builder.ts

Support RejectUnauthorized ssl option for postgres db. 
Pr is rebased and improved work https://github.com/janus-idp/backstage-plugins/pull/1613
Fixes: https://issues.redhat.com/browse/RHIDP-2409
You can test this pr with localhost. 
1. Create folder docker-postgres-ssl in the your directory:
```bash
mkdir -p ~/docker-postgres-ssl
```
2. Generate ca certificate:
```bash
cd ~/docker-postgres-ssl
openssl req -new -x509 -days 365 -nodes -out server.crt -keyout server.key -subj "/CN=localhost"
```
3. Execute docker postgres container with access to server.key and server.crt files from container:
```bash
docker run --hostname=48c66dd5ec67 \
--env=GOSU_VERSION=1.17 \
--env=PGDATA=/var/lib/postgresql/data \
--env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresq …
```

fix(rbac): support RejectUnauthorized ssl option for postgres

---

plugins/bulk-import-backend/CHANGELOG.md
plugins/bulk-import-backend/dist-dynamic/package.json
plugins/bulk-import-backend/package.json

This reverts commit a8ae32706e001eadd7a667e3a1f5e356792951d1.
Looks like another MSR issue after https://github.com/janus-idp/backstage-plugins/pull/2131 was merged ([release job logs](https://github.com/janus-idp/backstage-plugins/actions/runs/10793064428/job/29934131723)), causing dirty `yarn.lock` files in PRs like https://github.com/janus-idp/backstage-plugins/pull/2146
/cc @PatAKnight @AndrienkoAleksandr

chore(release): revert downgrade of bulk-import-backend plugin

---

plugins/bulk-import-backend/src/service/githubApiService.ts
plugins/bulk-import-backend/src/service/handlers/bulkImports.test.ts
plugins/bulk-import-backend/src/service/handlers/bulkImports.ts

The branch linked to an import PR could be outdated compared to the default branch.
To fix the issue reported in https://issues.redhat.com/browse/RHIDP-3901, the backend now ensures:
- that the import branch is up-to-date (best effort) prior to creating the import PR in case the branch already exists
- that the import branch is also deleted when the import PR is closed (when deleting an import job)
https://issues.redhat.com/browse/RHIDP-3901
See https://issues.redhat.com/browse/RHIDP-3901 for the repro steps.
Before the changes here, import PR could end up in Conflict on GH:
Now with the changes here, the backend attempts to keep …

fix(bulk-import): make sure import branch is up-to-date to prevent potential conflicts or unchanged files in GH [RHIDP-3901]

---

plugins/quay/dev/__data__/security_vulnerabilities.ts
plugins/quay/dev/__data__/tags.ts
plugins/quay/dev/index.tsx
plugins/quay/src/components/QuayRepository/tableHeading.tsx
plugins/quay/src/lib/utils.test.ts
plugins/quay/src/lib/utils.ts
plugins/quay/src/types.ts
plugins/quay/tests/quay.spec.ts

**Fixes:** 
https://issues.redhat.com/browse/RHTAPBUGS-1309
Enable Security scan column by adding sort comparator in quay plugin. 
This PR adds following changes:
- sort comparator for security scan
- additional mock data for dev mode
- unit tests.
**Screenshots**:
**How to test?:**
1. run yarn start in plugins/quay folder to run the application in dev mode.
cc: @jrichter1

fix(quay): fix the security scan sorting in quay plugin

---

plugins/bulk-import/README.md
plugins/bulk-import/src/components/AddRepositories/AddRepositoriesFormFooter.tsx
plugins/bulk-import/src/components/AddRepositories/AddRepositoriesPage.tsx
plugins/bulk-import/src/components/BulkImportPage.tsx
plugins/bulk-import/src/components/PreviewFile/KeyValueTextField.tsx
plugins/bulk-import/src/components/PreviewFile/PreviewFile.tsx
plugins/bulk-import/src/components/PreviewFile/PreviewFileSidebar.tsx
plugins/bulk-import/src/components/PreviewFile/PreviewFileSidebarDrawerContent.tsx
plugins/bulk-import/src/components/PreviewFile/PreviewPullRequest.test.tsx
plugins/bulk-import/src/components/PreviewFile/PreviewPullRequest.tsx
plugins/bulk-import/src/components/PreviewFile/PreviewPullRequestForm.test.tsx
plugins/bulk-import/src/components/PreviewFile/PreviewPullRequests.test.tsx
plugins/bulk-import/src/components/Repositories/CatalogInfoAction.tsx
plugins/bulk-import/src/components/Repositories/EditCatalogInfo.tsx
plugins/bulk-import/src/components/Repositories/RepositoriesList.test.tsx
plugins/bulk-import/src/components/Repositories/RepositoriesList.tsx
plugins/bulk-import/src/components/Repositories/RepositoriesListToolbar.tsx
plugins/bulk-import/src/hooks/useAddedRepositories.ts
plugins/bulk-import/src/hooks/useRepositories.ts
plugins/bulk-import/src/types/types.ts
plugins/bulk-import/src/utils/repository-utils.test.tsx
plugins/bulk-import/src/utils/repository-utils.tsx

**Resolves:**
https://issues.redhat.com/browse/RHIDP-3942
**Fixes:**
- Handled invalid entity YAML in the pull request (empty file or entity yaml without `apiVersion` or `kind` or `metadata.name` is considered invalid)
- As of today, the preview panel supports the visualization of only one entity from a catalog-info.yaml file. If the entity YAML file has multiple entities, the preview panel will show only the first entity
- Fixed the `navigate to` url after creating the import
- Removes the repository query param from the import page URL if the repository is not added or the URL/branch is invalid
- Added error handling in the side panel

fix(bulk-import): bulk import fixes

---

plugins/bulk-import-backend/CHANGELOG.md
plugins/bulk-import-backend/dist-dynamic/package.json
plugins/bulk-import-backend/package.json

Yet another MSR issue after https://github.com/janus-idp/backstage-plugins/pull/2156 has been merged: https://github.com/janus-idp/backstage-plugins/actions/runs/10834290717/job/30063107649
This reverts commit 35b1bca5e8aa3532227a5e5632d86434f07cede3.
@debsmita1 This should allow releasing the bulk-import frontend plugin correctly.
/cc @PatAKnight @AndrienkoAleksandr

chore(release): revert downgrade of several plugins

---

plugins/lightspeed/src/components/LightspeedChatBox.tsx

Fixes: https://issues.redhat.com/browse/RHIDP-3980

fix(lightspeed): use lightspeed icon image as bot avatar image

---

plugins/bulk-import-backend/api-docs/Apis/ImportApi.md
plugins/bulk-import-backend/api-docs/Apis/OrganizationApi.md
plugins/bulk-import-backend/api-docs/Apis/RepositoryApi.md
plugins/bulk-import-backend/src/helpers/catalogInfoGenerator.ts
plugins/bulk-import-backend/src/openapi.d.ts
plugins/bulk-import-backend/src/openapidocument.ts
plugins/bulk-import-backend/src/schema/openapi.yaml
plugins/bulk-import-backend/src/service/githubApiService.ts
plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
plugins/bulk-import-backend/src/service/handlers/organizations.ts
plugins/bulk-import-backend/src/service/handlers/repositories.ts
plugins/bulk-import-backend/src/service/router.test.ts
plugins/bulk-import-backend/src/service/router.ts

As reported in https://issues.redhat.com/browse/RHIDP-3859, searching in the bulk import pages is currently done client-side and only works on the visible rows (due to how data is returned by the backend in paginated chunks).
To address this issue, this PR implements search in the backend. This is done by introducing a new optional `search` query parameter to the endpoints below:
- `GET /organizations[?search=<orgName>]`: searches in the organization names (from the organizations accessible from the configured Github integrations)
- `GET /repositories[?search=<repoName>]`: searches in the repository names (from the repositories accessible from the configured Github integrations)
- `GET /organizations/:orgName/repositories[?search=<repoName>]`: …

feat(bulk-import): implement server-side search [RHIDP-3884]

---

plugins/bulk-import-backend/dist-dynamic/yarn.lock
plugins/feedback-backend/dist-dynamic/yarn.lock
plugins/kiali-backend/dist-dynamic/yarn.lock
plugins/ocm-backend/dist-dynamic/yarn.lock
plugins/orchestrator-backend/dist-dynamic/yarn.lock
plugins/rbac-backend-module-test/dist-dynamic/yarn.lock
yarn.lock

Mostly a bump to update express to v4.21.0 which updates a number of transitive dependencies that fix the following CVEs:
* CVE-2024-45590
* CVE-2024-43799
* CVE-2024-45296
Fixes: 
https://issues.redhat.com/browse/RHIDP-3917
https://issues.redhat.com/browse/RHIDP-3945

chore(deps): fix CVE-2024-45590, CVE-2024-43799, CVE-2024-45296

---

plugins/bulk-import-backend/src/helpers/catalogInfoGenerator.ts
plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
plugins/bulk-import-backend/src/service/handlers/importStatus.ts
plugins/bulk-import-backend/src/service/router.test.ts

This PR forces a refresh of the Location when the backend returns an Import as `ADDED` (which, as a reminder, means that the repository now has a `catalog-info.yaml` file in its default branch - either because it was already present when the Import was requested, or the import PR has been merged).
This is to make the Entities from the `catalog-info.yaml` show up quickly in the Backstage catalog.
This mimics the behavior of the "Register existing component" feature in Backstage: after you import a URL to a valid catalog-info.yaml, you can view the Entities right away in the catalog.
**NOTES**:
- I noticed that the refresh works quite immediately if the repository already has a `catalog-info.yaml` file in its default branch when it is bulk-imported …

fix(bulk-import): refresh the Location entity when the Import is `ADDED`

---

plugins/orchestrator-form-api/package.json

`@janus-idp/backstage-plugin-orchestrator-form-api` has been downgraded causing our release to be broken again. This PR plans to fix it.
[Downgrade](https://github.com/janus-idp/backstage-plugins/commit/d5ea54683edb4c04c8fab6a16d6fbc427d115eee) in question.

chore(release): revert downgrade of orchestrator form api

---

plugins/rbac-backend/README.md

Aims to further clarify some of the differences between the old backend system and new backend system. Adds a note that the section `Setup Permission Framework` is only relevant for the old backend system. Updates the section `Configuring the Backend` to include the removal of `@backstage/plugin-permission-backend/alpha` and `@backstage/plugin-permission-backend-module-allow-all-policy`
- Fixes: [RHIDP-3706](https://issues.redhat.com/browse/RHIDP-3706)
The need for this arose from the issue #2082

docs(rbac): add more clarification around requirements for old and new backend

---

plugins/topology/manifests/clusterrole.yaml

Bug : https://issues.redhat.com/projects/RHIDP/issues/RHIDP-4020?
1. Readme of topology 
2. clusterrole.yaml

docs(topology): adding vm vmi in clusterrole file for read access

---

plugins/bulk-import-backend/src/helpers/catalogInfoGenerator.ts
plugins/bulk-import-backend/src/service/githubApiService.ts
plugins/bulk-import-backend/src/service/handlers/bulkImports.test.ts
plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
plugins/bulk-import-backend/src/service/router.test.ts

This PR makes sure to also include existing Location entities (like the ones that might have been added through the GH auto-discovery plugin) as potential Import jobs.
And, to make sure the bulk import backend does not return any kind of Locations, it returns only the repos that are accessible from the configured GH integrations.
https://issues.redhat.com/browse/RHIDP-4021
This fixes the following issues:
- adding any public repos in the app-config.yaml would make it be shown as an Import job, even if that repo is not accessible from any of the configured GH integrations
- repos auto-added by the GH discovery plugin would not be shown as Import jobs, leading users to try to bulk-import them (they are shown in the …

fix(bulk-import): handle Location entities created from other sources like the GH discovery as Import candidates [RHIDP-4021]

---

plugins/catalog-backend-module-scaffolder-relation-processor/CHANGELOG.md
plugins/catalog-backend-module-scaffolder-relation-processor/dist-dynamic/package.json
plugins/catalog-backend-module-scaffolder-relation-processor/package.json

This reverts commit 31930b1f2da0d4654aa4fa714aea3a05795fbc60.
Yet another MSR issue after the merging of https://github.com/janus-idp/backstage-plugins/pull/2178. 
Release logs: https://github.com/janus-idp/backstage-plugins/actions/runs/10885652616/job/30203777287

chore(release): revert downgrade of `catalog-backend-module-scaffolder-relation-processor`

---

plugins/rbac/src/components/CreateRole/AddMembersForm.tsx

Fixes: https://issues.redhat.com/browse/RHDHBUGS-73
This PR fixes this issue by limiting the initial users/groups shown to 100 and once the user starts to search the search happens accross the whole data-set (tested with 45k users) and only top 100 results are rendered, for more options users can refine their search to get to the required user/group.
https://github.com/user-attachments/assets/2ed9bc2d-3d8f-4cd7-ba48-d87fa2aae637

fix(rbac): improve members dropdown to handle large no. of users/groups

---

plugins/lightspeed/package.json

- Since we don't want the lightspeed plugin to be published at v1.x.x as of now, we are planning to deprecate the already published 1.x.x versions(3 published) of frontend plugin and manually release a v0.1.1.

fix(lightspeed): downversion lightspeed frontend to v0.1.1

---

plugins/shared-react/package.json
plugins/shared-react/src/components/common/DeleteDialogContext.tsx
plugins/shared-react/src/components/common/DrawerContext.tsx
plugins/shared-react/src/components/common/StatusIconAndText.test.tsx
plugins/shared-react/src/components/index.ts
yarn.lock

Copies the current version of the shared react over to the 1.3.x to ensure that we get caught back up.
This plugin is need for a number of other 1.3.x plugin updates.

chore(release): catch shared react 1.3.x up with showcase 1.3.x

---

plugins/bulk-import-backend/dist-dynamic/yarn.lock
plugins/feedback-backend/dist-dynamic/yarn.lock
plugins/kiali-backend/dist-dynamic/yarn.lock
plugins/ocm-backend/dist-dynamic/yarn.lock
plugins/orchestrator-backend/dist-dynamic/yarn.lock
plugins/rbac-backend-module-test/dist-dynamic/yarn.lock
yarn.lock

Backport from https://github.com/janus-idp/backstage-plugins/pull/2162: 
Mostly a bump to update express to v4.21.0 which updates a number of transitive dependencies that fix the following CVEs:
* CVE-2024-45590
* CVE-2024-43799
* CVE-2024-45296
Fixes:
https://issues.redhat.com/browse/RHIDP-3917
https://issues.redhat.com/browse/RHIDP-3945
https://issues.redhat.com/browse/RHIDP-3897
https://issues.redhat.com/browse/RHIDP-3933

chore(deps): [1.3.x]  manual cherrypick of 2162

---

plugins/scaffolder-annotator-action/dist-dynamic/package.json
plugins/scaffolder-annotator-action/package.json
plugins/scaffolder-annotator-action/src/actions/annotator/annotator.test.ts
plugins/scaffolder-annotator-action/src/actions/annotator/annotator.ts
plugins/scaffolder-annotator-action/src/actions/customActions/createScaffoldedFromAction.ts
plugins/scaffolder-annotator-action/src/actions/customActions/createTimestampAction.ts

Copies the current version of the scaffolder backend module annotator over to the 1.3.x to ensure that we get caught back up.
Scaffolder backend module annotator version in the showcase 1.3.x branch: [1.3.0](https://github.com/janus-idp/backstage-showcase/blob/1.3.x/packages/backend/package.json#L48)
Version in the PR is 1.3.1, [PR](https://github.com/janus-idp/backstage-showcase/pull/1630) opened up in the showcase repo to bump this plugin one more time.

chore(release): catch scaffolder annotator 1.3.x up with showcase 1.3.x

---

plugins/ocm-backend/dist-dynamic/package.json
plugins/ocm-backend/dist-dynamic/yarn.lock
plugins/ocm-backend/package.json
plugins/ocm-backend/src/service/router.ts

Copies the current version of the ocm backend over to the 1.3.x to ensure that we get caught back up.
Ocm backend version in the showcase 1.3.x branch: [4.4.1](https://github.com/janus-idp/backstage-showcase/blob/1.3.x/dynamic-plugins/imports/package.json#L26)
Ocm backend version in the PR is 4.4.2, [PR](https://github.com/janus-idp/backstage-showcase/pull/1662) opened up in the showcase repo to bump this plugin one more time.

chore(release): catch ocm 1.3.x up with showcase 1.3.x

---

plugins/quay/CHANGELOG.md
plugins/quay/dev/__data__/security_vulnerabilities.ts
plugins/quay/dev/__data__/tags.ts
plugins/quay/dev/index.tsx
plugins/quay/package.json
plugins/quay/src/components/QuayRepository/tableHeading.tsx
plugins/quay/src/lib/utils.test.ts
plugins/quay/src/lib/utils.ts
plugins/quay/src/types.ts
plugins/quay/tests/quay.spec.ts

Copies the current version of the quay plugin over to the 1.3.x to ensure that we get caught back up.
quay version in the showcase 1.3.x branch: [1.11.7](https://github.com/janus-idp/backstage-showcase/blob/1.3.x/dynamic-plugins/imports/package.json#L27)
[Shared react](https://github.com/janus-idp/backstage-plugins/pull/2206) version 2.10.3 is also required for this plugin.

chore(release): catch quay 1.3.x up with showcase 1.3.x

---

plugins/topology/CHANGELOG.md
plugins/topology/README.md
plugins/topology/manifests/clusterrole.yaml
plugins/topology/package.json
plugins/topology/src/common/components/Status.tsx
plugins/topology/src/components/Topology/TopologySideBar/TopologyVirtualMachineDetails.tsx
plugins/topology/src/utils/selector.ts
plugins/topology/src/utils/vm-status-utils.ts
plugins/topology/src/vm-const.ts

Copies the current version of the topology plugin over to the 1.3.x to ensure that we get caught back up.
Topology version in the showcase 1.3.x branch: [1.27.5](https://github.com/janus-idp/backstage-showcase/blob/1.3.x/dynamic-plugins/imports/package.json#L32)
[Shared react](https://github.com/janus-idp/backstage-plugins/pull/2206) version 2.10.3 is also required for this plugin.

chore(release): catch topology 1.3.x up with showcase 1.3.x

---

plugins/orchestrator-backend/src/service/SonataFlowService.test.ts
plugins/orchestrator-backend/src/service/SonataFlowService.ts

In some cases, workflows fail without providing any information about the root cause, making debugging difficult.
For example: 
The backstage log contains:
```
backend:start: {"level":"error","message":"Error when fetching process instances: [GraphQL] Variable 'instanceId' has an invalid value: Variable 'instanceId' has coerced Null value for NonNull type 'String!'","plugin":"orchestrator","service":"backstage","timestamp":"2024-09-19 17:33:03"}
backend:start: {"actor":{"actorId":"user:development/guest","hostname":"localhost","ip":"::ffff:127.0.0.1","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"},"errors":[{"message":"[GraphQL] Variable 'instanceId' has an invalid value: Variable 'instanceId' has coerced Null value for NonNull type …
```

fix(orchestrator): improve error handling in SonataFlowService fetch

---

package.json

chore: tagRelease.sh: bump to 3.2.5 in 1.2.x branch + regen yarn.lock

---

plugins/topology-common/package.json

This reverts commit 992a331bf23b3a823d45fa42549deaf9acc54d18.
This was caused by another MSR failure - see
https://github.com/janus-idp/backstage-plugins/actions/runs/11021241904/job/30607878372

chore(release): revert unexpected downgrade of `backstage-plugin-topology-common`

---

plugins/rbac-backend/src/role-manager/ancestor-search-memo.ts
plugins/rbac-backend/src/role-manager/role-manager.test.ts
plugins/rbac-backend/src/role-manager/role-manager.ts

Allow to disable group inheritance feature.

feat(rbac): allow to disable group inheritance

---

plugins/rbac-backend/src/service/policy-builder.ts

Fix ownerRefs alias after upgrade backstage to 1.29
Fixes: 
https://issues.redhat.com/browse/RHIDP-4069

fix(rbac): fix ownerRefs alias after upgrade backstage to 1.29

---

plugins/bulk-import-backend/CHANGELOG.md
plugins/bulk-import-backend/dist-dynamic/package.json
plugins/bulk-import-backend/package.json

MSR downgrade of the bulk import backend plugin
Causing failing release 
Blocking some plugins from releasing
Problem [commit](https://github.com/janus-idp/backstage-plugins/commit/8b4413f73cee6195101cad9276d01836edc56b6a#diff-4b1e942efa156720791d944f042a15ecccae5b91e7f44b56a791866f35fd6f15)

chore(release): revert downgrade by MSR of bulk import backend

---

plugins/bulk-import-backend/CHANGELOG.md
plugins/bulk-import-backend/dist-dynamic/package.json
plugins/bulk-import-backend/package.json

MSR downgrade of the bulk import backend plugin
Causing failing release 
Will block some plugins from releasing
Problem [commit](https://github.com/janus-idp/backstage-plugins/commit/c6e5c5b1d3eaee76b0f606ab51b38e281303b060#diff-4b1e942efa156720791d944f042a15ecccae5b91e7f44b56a791866f35fd6f15L83)

chore(release): revert downgrade of bulk import backend by MSR

---

plugins/lightspeed/README.md

This PR adds the documentation on how to load the lightspeed plugin as a dynamic-plugin in RHDH and in backstage-showcase repository.
Screenshots:

docs(lightspeed): update lightspeed documentation with dynamic plugin section

---

packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts

This change updates the export-dynamic-plugin command's default behavior to widen the check used to determine if an embedded dependency needs to be built.  If an embedded dependency is outside of the yarn workspace and does not appear to be a source package (where "main" is a file ending in ".ts") then it will not be rebuilt during export-dynamic-plugin.  This caters for cases such as a backend plugin doing a runtime import of an ESM module, the ESM module can be built and embedded into the dynamic plugin and be available on the package path at runtime.
Part of fixing [RHIDP-4148](https://issues.redhat.com/browse/RHIDP-4148)
@04kash with the new CLI version from this the `export-dynamic` command for keycloak-backend would need to be changed to remove the `--no-embed-as-dependencies` flag.

fix(cli): avoid packing "binary" packages

---

plugins/orchestrator-form-react/CHANGELOG.md
plugins/orchestrator-form-react/package.json

The MSR release job seems to have failed after merging #2223 :
https://github.com/janus-idp/backstage-plugins/actions/runs/11159096004/job/31016793572
This reverts commit 5cf6602004c09b037d31aade078b45b3e02f0608, and should allow releasing the packages that have been updated recently (like `bulk-import-backend` and `bulk-import-common`).

chore(release): revert unexpected downgrade of `backstage-plugin-orchestrator-form-react` by MSR

---

plugins/ocm-common/catalog-info.yaml

Fixes a copy and paste error that this two components has the same name:
https://github.com/janus-idp/backstage-plugins/blob/5a4c3df939db940ab91f065cde22b250fee4d6cf/plugins/ocm-backend/catalog-info.yaml#L5-L7
and
https://github.com/janus-idp/backstage-plugins/blob/5a4c3df939db940ab91f065cde22b250fee4d6cf/plugins/ocm-common/catalog-info.yaml#L5-L7
This should fix:

fix(ocm-common): fix catalog info (duplicate)

---

plugins/tekton-common/package.json

The MSR release job seems to have failed after merging #2289 :
https://github.com/janus-idp/backstage-plugins/actions/runs/11160738980/job/31021831485
This reverts commit a0b89990cc6597b0b356e0679fec26981ed8872a.

chore(release): revert unexpected downgrade of `backstage-plugin-tekton-common` by MSR

---

plugins/tekton/src/__fixtures__/1-pipelinesData.ts
plugins/tekton/src/components/PipelineRunList/PipelineRunList.tsx

**Fixes:**
https://issues.redhat.com/browse/RHTAPBUGS-1306
Fixed sorting of the Tekton Pipelins runs Table.
This PR adds following changes:
- added dependencies while changes happen in pipelines runs table data, to make sure showing correct data
- made unique uid for mock data for dev mode
**Screenshots**:
**How to test?:**
1. run yarn start in plugins/tekton folder to run the application in dev mode.

fix: tekton table sorting

---

plugins/orchestrator/src/components/WorkflowResult.tsx

A link needs to contain both key and value to be rendered, otherwise its skipped on the Workflow result card.
Fixes: [FLPATH-1749](https://issues.redhat.com//browse/FLPATH-1749)

fix(orchestrator): avoid empty links in workflow result

---

plugins/bulk-import-common/package.json
yarn.lock

This reverts commit 101260d.
MSR job triggered by #2225:
https://github.com/janus-idp/backstage-plugins/actions/runs/11169002009/job/31048727205
Otherwise, this would likely prevent releasing future versions of the `bulk-import-common` or other packages, as we can see in https://github.com/janus-idp/backstage-plugins/actions/runs/11176753341/job/31070768894 (triggered by https://github.com/janus-idp/backstage-plugins/pull/2297).

chore(release): revert unexpected downgrade of `backstage-plugin-bulk-import-common` by MSR

---

plugins/quay-common/package.json

This reverts commit [561d19b](https://github.com/janus-idp/backstage-plugins/commit/561d19b088d574a2ab7a4e2238a038088e53594f).

chore(release): revert unexpected downgrade of backstage-plugin-quay-common by MSR

---

plugins/ocm-backend/CHANGELOG.md
plugins/ocm-backend/dist-dynamic/package.json
plugins/ocm-backend/package.json

There were some updates that happened to the OCM plugin post 1.2 release that were not synced to the 1.2.x branch.  This PR cherry picks the changes from the 4.0.7 and 4.0.8 releases (plugin metadata and Janus CLI version update)

chore(release): 1.2.x - Sync OCM plugins with the latest 1.2 version in Showcase

---

plugins/orchestrator-backend/package.json
plugins/orchestrator-common/package.json
plugins/orchestrator-form-api/package.json
plugins/orchestrator-form-react/CHANGELOG.md
plugins/orchestrator-form-react/package.json
plugins/orchestrator/package.json

chore: mark the 5 orchestrator plugins PRIVATE so MSR stops trying to re-release orchestrator-form-react 1.0.5
Revert "chore(release): 1.0.5 [skip ci]"
This reverts commit daa14e34051d425bd1c7b0351dc733dff4b9355d.
N/A
N/A

chore: mark the 5 orchestrator plugins PRIVATE so MSR stops trying to re-release orchestrator-form-react 1.0.5

---

packages/cli/README.md
packages/cli/src/commands/build/buildFrontend.ts
packages/cli/src/commands/build/command.ts
packages/cli/src/commands/index.ts
packages/cli/src/commands/install/steps/dependencies.ts
packages/cli/src/commands/start/command.ts
packages/cli/src/lib/builder/config.ts
packages/cli/src/lib/bundler/config.ts
packages/cli/src/lib/bundler/packageDetection.ts
packages/cli/src/lib/bundler/types.ts
packages/cli/src/lib/config.ts
packages/cli/src/lib/packager/productionPack.ts
packages/cli/src/lib/version.ts

This update adds comments to areas of the CLI code that were modified from the original fork.  This commit also updates the CLI readme to list what commands are added and updates the documentation links to point to the current dynamic plugins documentation.  This change fixes [RHIDP-2168](https://issues.redhat.com/browse/RHIDP-2168).

chore(cli): document forked changes

---

plugins/feedback-backend/CHANGELOG.md
plugins/feedback-backend/dist-dynamic/package.json
plugins/feedback-backend/package.json
plugins/kiali-backend/CHANGELOG.md
plugins/kiali-backend/dist-dynamic/package.json
plugins/kiali-backend/package.json
plugins/kubernetes-actions/CHANGELOG.md
plugins/kubernetes-actions/dist-dynamic/package.json
plugins/kubernetes-actions/package.json
plugins/orchestrator-backend/CHANGELOG.md
plugins/orchestrator-backend/dist-dynamic/package.json
plugins/orchestrator-backend/package.json
yarn.lock

These plugins need to be updated to the version that's aligned with 1.2.x
Need to make updates to Express (see 1.3 [PR](https://github.com/janus-idp/backstage-plugins/pull/2162/files#diff-b810b15125af407f9308629f2aaf637ba8a2715fcf0629784d237823254825f1))  which affects this list of plugins
June 5, janus-cli update to 1.10 seems to be the cut-off date

chore(release): 1.2.x : Sync kubernetes-action, feedback-backend, kiali-backend, orchestrator-backend  plugins

---

.github/workflows/pr.yaml
package.json

chore: drop support for node18 as of 1.4 ([RHIDP-3372](https://issues.redhat.com//browse/RHIDP-3372))
N/A
N/A

chore: drop support for node18 as of 1.4 (RHIDP-3372)

---

plugins/nexus-repository-manager/README.md
plugins/nexus-repository-manager/package.json

Jira Issue: [RHIDP-3803](https://issues.redhat.com/browse/RHIDP-3803)
The `nexus-repository-manager` plugin has been migrated to the [backstage/community-plugins](https://github.com/backstage/community-plugins/tree/main/workspaces/nexus-repository-manager/plugins) repository in support of our [sunsetting](https://issues.redhat.com/browse/RHIDP-3227) efforts.
This PR adds note about this plugin being deprecated and also setting the plugin to private in `package.json` to prevent publishing of deprecated plugin.

chore: add deprecate note to nexus-repository-manager plugin

---

CONTRIBUTING.md
package.json
plugins/kiali/DEVELOPMENT.md

One extra run script that makes it easier to switch between backstage/rhdh projects.
Adds `yarn dev` to start frontend and backend together.
`yarn start:backstage` still work, of course.

chore: start frontend and backend with yarn dev

---

plugins/orchestrator-backend/dist-dynamic/package.json
plugins/orchestrator-backend/dist-dynamic/yarn.lock
plugins/orchestrator-backend/package.json

This fix makes export-dynamic treat @janus-idp/backstage-plugin-orchestrator-common as an additional package, instead of embedding it as a code.
Without this fix the following [code](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/orchestrator-backend/src/service/router.ts#L115) breaks:
```typescript
router.use(
'/docs',
express.static(
resolvePackagePath(
'@janus-idp/backstage-plugin-orchestrator-common',
'src/generated/docs/html',
),
),
);
```

fix(orchestrator): fix dynamic plugin build

---

plugins/keycloak-backend/src/lib/read.test.ts
plugins/keycloak-backend/src/lib/read.ts
plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts

Avoid undefined values for Keycloak group members to prevent type errors during group ingestion. Also, fix missing realms, as they could theoretically cause type errors, though very rarely. Log errors with a warning level when retrieving the Keycloak user list.
Fixes: https://issues.redhat.com/browse/RHIDP-3785
Upstream issue: https://github.com/janus-idp/backstage-plugins/issues/2112
Unfortunately, I reproduced the bug synthetically. I don't have access to a very large database to confirm the fix with 100% certainty.

fix(keycloak): avoid undefined values for keycloak group members

---

plugins/orchestrator-backend/src/helpers/queryBuilder.test.ts
plugins/orchestrator-backend/src/helpers/queryBuilder.ts
plugins/orchestrator-backend/src/service/DataIndexService.test.ts
plugins/orchestrator-backend/src/service/__fixtures__/mockProcessInstanceArgumentsData.ts

Add the capability to filter by fields that are modelled as IDArgument in DataIndex.
Supported operator are EQ, IN and ISNull [1]
```bash
curl --request POST \                                                                                                                                                                                                                                                                                                                                                 gloria@fedora
--url http://localhost:7007/api/orchestrator/v2/workflows/instances \
-H "Authorization: $token" \
--header "Content-Type: application/json" \
--data '{  
"filters": { 
"field": "id", 
"operator": "EQ", 
"value": "dcf9a3cf-3cab-47bf-b521-f5def87f0392" 
}, 
"paginationInfo": { 
"offset": …
```

feat(orchestrator): add filter by IDArgument

---

plugins/rbac-backend/src/service/plugin-endpoint.test.ts
plugins/rbac-backend/src/service/plugin-endpoints.ts
plugins/rbac-backend/src/service/policy-builder.test.ts
plugins/rbac-backend/src/service/policy-builder.ts

Triggered by [this disucssion](https://github.com/janus-idp/backstage-plugins/pull/2225/files/6c33a8607216c53648261ccf5285b92f9ac87b79#r1781671369) under [this PR](https://github.com/janus-idp/backstage-plugins/pull/2225) to migrate RBAC plugin to use the new backend.
This PR changes the constructor to use 2 objects as the arguments instead: `deps` for mandatory parameters and `optional` for optional ones.
Fixes [RHIDP-4318](https://issues.redhat.com/browse/RHIDP-4318)

fix(rbac): refactor PluginPermissionMetadataCollector constructor

---

plugins/keycloak-backend/package.json
plugins/keycloak-backend/src/extensions.ts
plugins/keycloak-backend/src/lib/config.test.ts
plugins/keycloak-backend/src/lib/read.test.ts
plugins/keycloak-backend/src/lib/read.ts
plugins/keycloak-backend/src/lib/transformers.ts
plugins/keycloak-backend/src/lib/types.ts
plugins/keycloak-backend/src/module/catalogModuleKeycloakEntityProvider.test.ts
plugins/keycloak-backend/src/module/catalogModuleKeycloakEntityProvider.ts
plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.test.ts
plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts
yarn.lock

- Delete unused dev dependencies
- Use `mockServices rootConfig` instead of `ConfigReader` in tests
[RHIDP-4056](https://issues.redhat.com/browse/RHIDP-4056)

fix(keycloak-backend): delete unused dev dependencies and update test

---

plugins/orchestrator-form-react/package.json

orchestrator-form-react does not use orchestrator-common
the customers will be using this package directly in their custom plugin, so it's critical it won't be updated for no reason

fix(orchestrator): remove unnecessary dependency 

---

.changeset/green-trees-fly.md
.changeset/hip-walls-kiss.md
plugins/ocm/README.md
plugins/ocm/dev/index.tsx
plugins/ocm/package.json
plugins/ocm/src/components/common.tsx
plugins/ocm/src/index.ts
plugins/ocm/src/plugin.ts
plugins/shared-react/src/components/common/Status.tsx
plugins/shared-react/src/components/common/StatusIconAndText.tsx
yarn.lock

Resolves:
https://issues.redhat.com/browse/RHIDP-3796
Screenshot:
Test setup
OCM plugin setup
- Create a namespace “deb-test”
- Install the Advanced Cluster Management for Kubernetes operator
- Create MultiClusterHub Custom resource under deb-test namespace
- Execute steps [https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.10/html/install/installing#custom-im[…]ull-secret](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.10/html/install/installing#custom-im%5B%E2%80%A6%5Dull-secret) from 1.4.2 - 1.4.5
- oc create secret generic my-image-secret -n deb-test --from-file=.dockerconfigjson=./pull-secret.txt --type=kubernetes.io/dockerconfigjson
```
apiVersion: …
```

fix(ocm): replace usage of pf-icons to mui icons

---

.changeset/nine-peas-boil.md
packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts

This change updates the CLI to use `--no-immutable` when a plugin package or monorepo `yarn.lock` file is used during the `export-dynamic-plugin` command. Explicitly passing this flag avoids the default Yarn 3.x behavior of `--immutable` when the command is run in a CI environment.
@schultzp2020 @davidfestal fyi

fix(cli): allow mutable install for monorepo yarn.lock

---

packages/app/src/components/Root/Root.tsx

**Fixes:**
[RHIDP-4662](https://issues.redhat.com/browse/RHIDP-4662)
Small change to fix the logo position after we updated the app to MUI v5 (long time ago):
**Before:**
**After:**

fix(app): fix logo padding when using MUI v5 makeStyles

---

.changeset/spicy-pens-press.md
plugins/kubernetes-actions/package.json
plugins/ocm-backend/package.json
plugins/ocm-backend/src/constants.ts
plugins/ocm-backend/src/providers/ManagedClusterProvider.ts
plugins/shared-react/package.json
plugins/tekton/package.json
plugins/topology/package.json
yarn.lock

Fixes:
https://issues.redhat.com/browse/RHIDP-4441
This upgrades the following packages
- ocm-backend
- shared-react
- kubernetes-action
- topology
- tekton
Note: 1.3.x fix for Argocd will be contributed from backstage/community-plugin.
Fix CVE
[CVE-2024-21534
](https://bugzilla.redhat.com/show_bug.cgi?id=2317968)

fix(deps): update kubernetes-client version to fix a CVE

---

.changeset/fuzzy-dryers-lie.md
plugins/rbac-backend/docs/group-hierarchy.md
plugins/rbac-backend/src/role-manager/ancestor-search-memo.ts
plugins/rbac-backend/src/role-manager/role-manager.test.ts
plugins/rbac-backend/src/role-manager/role-manager.ts
plugins/rbac-backend/src/service/policy-builder.ts

Fixes https://issues.redhat.com/browse/RHIDP-4069

chore(release): update RBAC to delivery bug fixes for RHDH 1.3.1

---

.changeset/early-trainers-dance.md
plugins/keycloak-backend/__fixtures__/data.ts
plugins/keycloak-backend/__fixtures__/helpers.ts
plugins/keycloak-backend/package.json
plugins/keycloak-backend/src/lib/read.test.ts
plugins/keycloak-backend/src/lib/read.ts
plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts

https://issues.redhat.com/browse/RHIDP-3785
https://issues.redhat.com/browse/RHIDP-4391

chore(release): backport keycloak fixes but without upgrade keycloak client

---

CONTRIBUTING.md

Add instructions on how to migrate plugins to backstage/community-plugins and redhat-developer/rhdh-plugins in `CONTRIBUTING.md`

docs: added instructions on migrating plugins to BCP/rhdh-plugins

---

.changeset/odd-onions-sort.md
plugins/keycloak-backend/dist-dynamic/package.json
plugins/keycloak-backend/package.json

Looks like the keycloak plugin was released under a `major` update instead of a `patch`. This PR reverts back to the original version and adds a patch changeset so that we can release it properly.

chore(release): revert the major update so that we can release under a patch

---

.github/CODEOWNERS

add packages/cli to CODEOWNERS

chore: add CODEOWNERS for /packages/cli 

---

.changeset/healthy-parrots-invite.md
plugins/ocm/src/components/ClusterStatusPage/ClusterStatusPage.tsx
plugins/ocm/src/components/common.tsx

Fixes: [RHIDP-4602](https://issues.redhat.com/browse/RHIDP-4602)
Fix a layout issue on the OCM ClusterStatusPage.
In 1.2 it looked like this:
In 1.3 the icon was changed and wasn't aligned anymore;
With this change:

fix(ocm): fix unaligned status icon and message

---

plugins/lightspeed-backend/src/handlers/chatHistory.ts
plugins/lightspeed-backend/src/service/router.test.ts
plugins/lightspeed-backend/src/service/router.ts

This PR implements the following changes required for frontend.
1. sends the user conversation history from the store to the langchain stream method.
2. add message created timestamp. i.e `created_at` and `role` in  `response_metadata` object. 
---
**Unit tests:**
POST /v1/query
✓ should not have any history for the initial conversation (25 ms)
✓ should call the stream with conversation history (17 ms)
✓ should contain ai and human message timestamp (218 ms)

feat(lightspeed-backend): send conversation history to langchain streams

---

.changeset/pretty-humans-pump.md
packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-code.ts

This change updates the CLI to use `--no-immutable` when a plugin package or monorepo `yarn.lock` file is used during the `export-dynamic-plugin` command with deprecated flags. Explicitly passing this flag avoids the default Yarn 3.x behavior of `--immutable` when the command is run in a CI environment.
Signed-off-by: Paul Schultz <pschultz@pobox.com>

fix(cli): allow mutable install for monorepo yarn.lock with deprecated flags

---

.changeset/quick-dryers-train.md
plugins/kubernetes-actions/dist-dynamic/package.json
plugins/kubernetes-actions/dist-dynamic/yarn.lock
plugins/kubernetes-actions/package.json
plugins/ocm-backend/dist-dynamic/package.json
plugins/ocm-backend/dist-dynamic/yarn.lock
plugins/ocm-backend/package.json
plugins/ocm-backend/src/constants.ts
plugins/ocm-backend/src/providers/ManagedClusterProvider.ts
plugins/shared-react/package.json
plugins/tekton/package.json
plugins/topology/package.json
yarn.lock

Manual cherry pick of https://github.com/janus-idp/backstage-plugins/pull/2356
Fixes:
https://issues.redhat.com/browse/RHIDP-4440
This upgrades the following packages
- ocm-backend
- shared-react
- kubernetes-action
- topology
- tekton
Note: 1.3.x fix for Argocd will be contributed from backstage/community-plugin.
Fix CVE
[CVE-2024-21534
](https://bugzilla.redhat.com/show_bug.cgi?id=2317968)

fix(deps): update kubernetes-client to fix CVE-2024-21534

---

.changeset/thirty-pets-buy.md
plugins/rbac-backend/src/admin-permissions/admin-creation.test.ts
plugins/rbac-backend/src/admin-permissions/admin-creation.ts
plugins/rbac-backend/src/policies/permission-policy.test.ts

Fix rbac-backend plugin startup.
Fix test warning/error related to activated file watchers. 
Fixes https://issues.redhat.com/browse/RHIDP-4732

fix(rbac): fix rbac-backend startup

---

CONTRIBUTING.md

Update Migration Guidelines to include note about keeping migrated plugin upto date with the changes made in the Janus repo.

chore: update Migration Guidelines in CONTRIBUTING.md

---

.changeset/eighty-tips-learn.md
.changeset/mean-eagles-dress.md
packages/cli/package.json
packages/cli/src/commands/index.ts
packages/cli/src/commands/package-dynamic-plugins/command.ts
yarn.lock

This change changes the CLI package-dynamic-plugins command to take advantage of some dynamic plugin projects that have followed the convention of maintaining a app-config.janus-idp.yaml in the root of the plugin source directory.  When this file is present, it will be read in as the command processes dynamic plugins in the monorepo and then included in the example dynamic-plugins.yaml configuration printed out when the command successfully completes.  This change also adjusts the control flow where this is printed out to ensure it's after successful completion of the container image.
This seemed like a nice enhancement to have while working on a dynamic plugin monorepo, here's an example of how this looks on a small project with a frontend plugin that contains an …

fix(cli): improve local development experience

---

plugins/orchestrator/src/components/WorkflowResult.tsx

fix(orchestrator): make WorkflowResult rebust on malformed input

---

.changeset/neat-pigs-lie.md
plugins/orchestrator-backend/src/helpers/filterBuilder.ts
plugins/orchestrator-backend/src/helpers/filterBuilders.test.ts
plugins/orchestrator-backend/src/service/DataIndexService.test.ts
plugins/orchestrator-backend/src/service/DataIndexService.ts
plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.test.ts
plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.ts
plugins/orchestrator-common/src/generated/.METADATA.sha1
plugins/orchestrator-common/src/openapi/openapi.yaml

Add filter by enum.
At the moment, there is no an easy way to identify enumerators from the DataIndex GraphQL schema. 
Each enum needs to be manually supported. At this stage, the only supported enum is `status` from `ProcessInstanceDTO`
with operators `Equal` and `In` .
[FLPATH-1759](https://issues.redhat.com/browse/FLPATH-1759)

feat(orchestrator): add filter by enum

---

.changeset/stale-experts-share.md
.changeset/sweet-pens-drive.md
.changeset/tame-months-admire.md

since release action failed for this PR https://github.com/janus-idp/backstage-plugins/pull/2517 in export-dynamic part, and since the packages we really need to be released do not include the backend, I'm creating this changeset PR to only include the form packages

fix(orchestrator): another attempt to have orchestrator form packages released

---

plugins/topology-common/README.md
plugins/topology/README.md

Related to: https://issues.redhat.com/browse/RHIDP-4257

chore: add deprecate note for topology plugins

---

.changeset/quiet-carrots-mix.md
plugins/audit-log-node/package.json
plugins/keycloak-backend/package.json
yarn.lock

Missed some files from https://github.com/janus-idp/backstage-plugins/pull/2343

chore: bump express versions for audit-log-node and keycloak-backend

---

.changeset/old-trees-tease.md
packages/cli/src/commands/package-dynamic-plugins/command.ts

This commit changes the CLI to try generating a command to export a plugin package as a dynamic plugin if the plugin package doesn't have an export-dynamic script defined.
This fixes [RHIDP-4828](https://issues.redhat.com/browse/RHIDP-4828)

fix(cli): use cli directly as a fallback

---

.changeset/cyan-tigers-jam.md
plugins/orchestrator-form-api/src/api.ts
plugins/orchestrator-form-react/src/components/OrchestratorFormWrapper.tsx

backport https://github.com/janus-idp/backstage-plugins/pull/2562
The plugin containing the custom form decorator needs the initial form data to initialize the custom widgets correctly.
This change will enable resolving https://issues.redhat.com/browse/FLPATH-1878

fix(orchestrator): pass also initial form data to custom decorator

---

.changeset/packages-cli.md
.changeset/plugins-aap-backend.md
.changeset/plugins-audit-log-node.md
.changeset/plugins-kiali-backend.md
.changeset/plugins-kiali.md
.changeset/plugins-kubernetes-actions.md
.changeset/plugins-scaffolder-annotator-action.md
.changeset/plugins-shared-react.md
.changeset/plugins-web-terminal.md
package.json
packages/cli/.versionhistory.md
plugins/aap-backend/.versionhistory.md
plugins/audit-log-node/.versionhistory.md
plugins/kiali-backend/.versionhistory.md
plugins/kiali/.versionhistory.md
plugins/kubernetes-actions/.versionhistory.md
plugins/scaffolder-annotator-action/.versionhistory.md
plugins/shared-react/.versionhistory.md
plugins/web-terminal/.versionhistory.md

- **feat: checkPluginVersion.sh bump ./ to 3.5.0 in main**
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
- **feat: checkPluginVersion.sh bump packages/cli to 1.19.0 in main**
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
- **feat: checkPluginVersion.sh bump plugins/aap-backend to 2.3.0 in main**
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
- **feat: checkPluginVersion.sh bump plugins/audit-log-node to 1.8.0 in main**
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
- **feat: checkPluginVersion.sh bump plugins/kiali to 1.35.0 in main**
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
- **feat: checkPluginVersion.sh bump plugins/kiali-backend to 1.21.0 in main**
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
- **feat: …

feat: checkPluginVersion.sh bump plugins for 1.4.0 release

---

.changeset/long-pants-allow.md
packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts
packages/cli/src/commands/index.ts

This change introduces two new flags to the CLI to handle transitive dependencies on packages containing native modules.  `--allow-native-package [package-name...]` to selectively allow native packages when exporting a dynamic plugin and allowing it's installation into the exported dynamic plugin and `--suppress-native-package [package-name..]` which replaces the native package with an empty package during export, preventing the native package's inclusion into the exported dynamic plugin's private dependencies.

feat(cli): add flags to handle native deps

---

.changeset/warm-clouds-compete.md
plugins/orchestrator-form-react/src/components/OrchestratorForm.tsx
plugins/orchestrator-form-react/src/components/OrchestratorFormWrapper.tsx
plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.tsx

1. businessKey fixed to be only a parent assessment workflow, to avoid having workflow runs shown as assessed by themselves, and then rerun shows the inputs as readonly.
2. fixed rerendering of form on every change, which was caused by passing formData to decorator. This constant rerendering causes the form to be unusable. instead only the initial data should be passed to the decorator.

fix(orchestrator): multiple bug fixes related to execution form

---

.changeset/hungry-turtles-sin.md
packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts

This change adjusts the directory used when the CLI attempts a require call when discovering a built embedded package from using the dynamic plugin package to using the package of the discovered built embedded package.
This fixes [RHIDP-5014](https://issues.redhat.com/browse/RHIDP-5014)

fix(cli): adjust embedded module searching

---

.changeset/rich-crews-provide.md
packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts

This change updates the CLI so that stdout of the `yarn install` command is redirected to a file.  On successful completion of `yarn install` and validation of the exported dynamic plugin the output file will be removed, otherwise the output file will be available for troubleshooting.
This fixes [RHIDP-5136](https://issues.redhat.com/browse/RHIDP-5136)

fix(cli): redirect yarn install output

---

.changeset/red-meals-help.md
packages/cli/src/commands/package-dynamic-plugins/command.ts

This change fixes an issue in the `package-dynamic-plugins` command that prevents it from running properly in a single plugin project which does not have workspaces.

fix(cli): support single packages better

---

.changeset/silly-nails-smell.md
packages/cli/src/commands/index.ts
packages/cli/src/commands/package-dynamic-plugins/command.ts

This also adds `--platfrom` flag that overrides the default `linux/amd64` platform
fixes https://issues.redhat.com/browse/RHIDP-5440

feat(janus-idp/cli): package-dynamic-plugins default to linux/amd64 platform

---

.changeset/sour-masks-study.md
plugins/audit-log-node/package.json
plugins/kiali-backend/package.json
yarn.lock

Updates to Express v4.21.2 in order to bump path-to-regexp to v0.1.12
Fixes:
CVE-2024-52798
[RHIDP-5177](https://issues.redhat.com/browse/RHIDP-5177)

chore(deps): [release-1.4] Bump path-to-regexp to v0.1.12 to fix CVE-2024-52798

---

.changeset/shiny-snakes-tan.md
packages/cli/src/commands/index.ts
packages/cli/src/commands/package-dynamic-plugins/command.ts

This removes `-m` (`--marketplace`) flag from `package-dynamic-plugins` command that was added in https://github.com/janus-idp/backstage-plugins/pull/2609
This is currently not used for anything. There will be new, more generic implementation added later on. More about that at https://issues.redhat.com/browse/RHIDP-5290

feat(janus-idp/cli): remove marketplace flag

---

.changeset/stale-penguins-tan.md
packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-code.ts
packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts
packages/cli/src/commands/export-dynamic-plugin/backend-utils.ts

This change updates the cli's --ignore-version-check flag to also ignore the check performed on a embedded transitive dependencies that are moved to peer dependencies, when it is known that the mismatch is runtime compatible.
Fixes [RHIDP-4505](https://issues.redhat.com/browse/RHIDP-4505)
@04kash @schultzp2020 FYI

fix(cli): extend --ignore-version-check

---

package.json

This PR updates the version field in the package.json file from 3.3.4 to 3.3.5 to align with the latest release requirements.
Reason for the change: Ensure the repository reflects the correct semantic versioning for the upcoming release.

chore: bump version to 3.3.5 in package.json

---

.changeset/silent-hounds-live.md

Use minor version instead of major for next shared-react release

fix(shared-react): use minor version instead of major for next release

---

.changeset/packages-cli.md
.changeset/plugins-audit-log-node.md
.changeset/plugins-shared-react.md
.changeset/plugins-web-terminal.md
package.json
packages/cli/.versionhistory.md
plugins/audit-log-node/.versionhistory.md
plugins/shared-react/.versionhistory.md
plugins/web-terminal/.versionhistory.md

- **feat: checkPluginVersion.sh bump ./ to 3.6.0 in main**
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
- **feat: checkPluginVersion.sh bump packages/cli to 3.3.0 in main**
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
- **feat: checkPluginVersion.sh bump plugins/audit-log-node to 1.9.0 in main**
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
- **feat: checkPluginVersion.sh bump plugins/shared-react to 2.17.0 in main**
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
- **feat: checkPluginVersion.sh bump plugins/web-terminal to 1.14.0 in main**
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>

feat: checkPluginVersion.sh bump plugins for 1.5.0 release

---

.changeset/plenty-masks-buy.md
packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts
packages/cli/src/commands/export-dynamic-plugin/frontend.ts

Yarn v1 support for file protocol used in conjunction with resolution is limited, so that in some cases the `export-dynamic-plugin` command may fail on `yarn v1`.
This PR  accommodates this limitation without changing the existing behavior and generated output for yarn v3.

fix: cli incompatibility with yarn v1

---

.changeset/plugins-audit-log-node.md

Since the `audit-log-node` plugin was [removed from the repository](https://github.com/janus-idp/backstage-plugins/pull/2641), [this changeset](https://github.com/janus-idp/backstage-plugins/blob/main/.changeset/plugins-audit-log-node.md) needs to be deleted as well. The release workflow is attempting to release this non-existent package because of the changeset, which is causing [the workflow to fail](https://github.com/janus-idp/backstage-plugins/actions/runs/13707841310/job/38337388474).

chore: remove audit-log-node changeset to fix release workflow

---

.changeset/metal-plums-bow.md
packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts

This change ensures the CLI overrides any existing resolutions in a plugin's package.json to ensure the dynamic plugin's package.json properly refers to embedded packages.  This fixes cases where a plugin package is using resolutions for more control of the dependencies to support offline builds.
This fixes [RHIDP-6448](https://issues.redhat.com/browse/RHIDP-6448)

fix(cli): override manually added resolutions

---

.changeset/fresh-mirrors-help.md
packages/cli/src/commands/package-dynamic-plugins/command.ts

This change ensures package-dynamic-plugin takes the package name as-is from the exported plugin package, rather than derive the name based on the original plugin package and role.  This change also ensures that plugin metadata comes from the exported package.  Finally this change removes some output that isn't necessary when detecting plugin configuration files.
Fixes [RHIDP-6652](https://issues.redhat.com/browse/RHIDP-6652)

fix(cli): use the correct package name

---

.changeset/odd-planes-reply.md
packages/cli/src/commands/export-dynamic-plugin/command.ts

Currently, for backend dynamic plugin packages, the config schema json file is generated in `dist/configSchema.json`.
It's unfortunate since, on the frontend side in the upcoming upstream dynamic frontend plugin support based on module federation, it would be generated in  `dist/.config-schema.json`, as it is for complete bundled apps (notice the added `.`there). And surely in the upstream dynamic plugins support we don't want to expect a different config schema file location for frontend & backend plugins.
This PRs prepares for better compatibility with upstream by generating the config schema in both `dist/configSchema.json` (for backward compatibility with RHDH) and `dist/.config-schema.json` for consistency and compatibility with upstream.

fix: make plugin config schema generation compatible with upstream.

---

.changeset/rude-bobcats-shake.md
packages/cli/src/commands/package-dynamic-plugins/command.ts

This change restores the package-dynamic-plugin's conversion of the exported dynamic plugin's package name to a flat file path.
Fixes [RHIDP-6789](https://issues.redhat.com/browse/RHIDP-6789)

fix(cli): create appropriate plugin directory name

---

.changeset/giant-spies-tap.md
.changeset/swift-plums-join.md
packages/cli/src/commands/export-dynamic-plugin/command.ts
packages/cli/src/commands/package-dynamic-plugins/command.ts

Fix role retrieval bug in the `metadata` command, and introduce backstage `support-versions` check during export.

fix: role retrieval bug in the `metadata` command, and introduce backstage `support-versions` check during export.

---

.changeset/old-cooks-reply.md
packages/cli/src/commands/index.ts
packages/cli/src/commands/package-dynamic-plugins/command.ts

Add `buildah` as an option to build container images, since it doesnt require a running daemon such a podman or docker
Signed-off-by: Marcel Hild <hild@b4mad.net>

feat(cli): extend container tool to buildah

---

.changeset/purple-rabbits-roll.md
packages/cli/src/commands/export-dynamic-plugin/backend.ts

This change updates the existing condition where the CLI caters for when a package main script points to a .ts file.  This addresses an update to the default behavior for how modules are handled by `require`.
This fixes [RHIDP-6698](https://issues.redhat.com/browse/RHIDP-6698)

fix(cli): cater for new potential error

---

.changeset/forty-numbers-serve.md
packages/cli/MIGRATION.md
packages/cli/README.md
packages/cli/package.json
packages/cli/src/commands/export-dynamic-plugin/command.ts
packages/cli/src/commands/index.ts
packages/cli/src/commands/package-dynamic-plugins/command.ts

- add deprecation warning to commands that were moved to a new [rhdh-cli](https://github.com/redhat-developer/rhdh-cli)
- add a quick migration guide
 
fixes: https://issues.redhat.com/browse/RHIDP-7062 

feat(cli): add deprecation warnings to package-dynamic-plugins and export-dynamic-plugin
